namespace Electron2D;

public static partial class ResourceFileTypes
{
    private static AcceptDialog CreateAcceptDialogFileNode() => new();
    private static ConfirmationDialog CreateConfirmationDialogFileNode() => new();
    private static OptionButton CreateOptionButtonFileNode() => new();
    private static TabContainer CreateTabContainerFileNode() => new();
    private static PopupMenu CreatePopupMenuFileNode() => new();
    private static Popup CreatePopupFileNode() => new Popup();
    private static PopupPanel CreatePopupPanelFileNode() => new PopupPanel();
    private static void RegisterBuiltInNodes()
    {
        RegisterNode("AcceptDialog", CreateAcceptDialogFileNode);
        RegisterNode("ConfirmationDialog", CreateConfirmationDialogFileNode);
        RegisterNode("AnimatableBody", CreateAnimatableBodyFileNode);
        RegisterNode("AnimatedSprite", CreateAnimatedSpriteFileNode);
        RegisterNode("AnimationMixer", CreateAnimationMixerFileNode);
        RegisterNode("AnimationPlayer", CreateAnimationPlayerFileNode);
        RegisterNode("AnimationTree", CreateAnimationTreeFileNode);
        RegisterNode("Area", CreateAreaFileNode);
        RegisterNode("AspectRatioContainer", CreateAspectRatioContainerFileNode);
        RegisterNode("AudioListener", CreateAudioListenerFileNode);
        RegisterNode("AudioStreamEmitter", CreateAudioStreamEmitterFileNode);
        RegisterNode("AudioStreamPlayer", CreateAudioStreamPlayerFileNode);
        RegisterNode("BackBufferCopy", CreateBackBufferCopyFileNode);
        RegisterNode("BoxContainer", CreateBoxContainerFileNode);
        RegisterNode("OptionButton", CreateOptionButtonFileNode);
        RegisterNode("Button", CreateButtonFileNode);
        RegisterNode("Camera", CreateCameraFileNode);
        RegisterNode("CanvasGroup", CreateCanvasGroupFileNode);
        RegisterNode("CanvasLayer", CreateCanvasLayerFileNode);
        RegisterNode("CenterContainer", CreateCenterContainerFileNode);
        RegisterNode("CharacterBody", CreateCharacterBodyFileNode);
        RegisterNode("CheckBox", CreateCheckBoxFileNode);
        RegisterNode("CheckButton", CreateCheckButtonFileNode);
        RegisterNode("CollisionPolygon", CreateCollisionPolygonFileNode);
        RegisterNode("CollisionShape", CreateCollisionShapeFileNode);
        RegisterNode("Container", CreateContainerFileNode);
        RegisterNode("Control", CreateControlFileNode);
        RegisterNode("DampedSpringJoint", CreateDampedSpringJointFileNode);
        RegisterNode("FlowContainer", CreateFlowContainerFileNode);
        RegisterNode("GridContainer", CreateGridContainerFileNode);
        RegisterNode("GrooveJoint", CreateGrooveJointFileNode);
        RegisterNode("HBoxContainer", CreateHBoxContainerFileNode);
        RegisterNode("HFlowContainer", CreateHFlowContainerFileNode);
        RegisterNode("HScrollBar", CreateHScrollBarFileNode);
        RegisterNode("HSlider", CreateHSliderFileNode);
        RegisterNode("HSplitContainer", CreateHSplitContainerFileNode);
        RegisterNode("HTTPRequest", CreateHTTPRequestFileNode);
        RegisterNode("ItemList", CreateItemListFileNode);
        RegisterNode("Label", CreateLabelFileNode);
        RegisterNode("Line", CreateLineFileNode);
        RegisterNode("LineEdit", CreateLineEditFileNode);
        RegisterNode("MarginContainer", CreateMarginContainerFileNode);
        RegisterNode("MeshInstance", CreateMeshInstanceFileNode);
        RegisterNode("MultiMeshInstance", CreateMultiMeshInstanceFileNode);
        RegisterNode("MultiplayerSpawner", CreateMultiplayerSpawnerFileNode);
        RegisterNode("MultiplayerSynchronizer", CreateMultiplayerSynchronizerFileNode);
        RegisterNode("NinePatchRect", CreateNinePatchRectFileNode);
        RegisterNode("Popup", CreatePopupFileNode);
        RegisterNode("PopupMenu", CreatePopupMenuFileNode);
        RegisterNode("PopupPanel", CreatePopupPanelFileNode);
        RegisterNode("Panel", CreatePanelFileNode);
        RegisterNode("PanelContainer", CreatePanelContainerFileNode);
        RegisterNode("Parallax", CreateParallaxFileNode);
        RegisterNode("ParallaxBackground", CreateParallaxBackgroundFileNode);
        RegisterNode("ParallaxLayer", CreateParallaxLayerFileNode);
        RegisterNode("Path", CreatePathFileNode);
        RegisterNode("PathFollow", CreatePathFollowFileNode);
        RegisterNode("PinJoint", CreatePinJointFileNode);
        RegisterNode("Polygon", CreatePolygonFileNode);
        RegisterNode("RayCast", CreateRayCastFileNode);
        RegisterNode("RemoteTransform", CreateRemoteTransformFileNode);
        RegisterNode("RigidBody", CreateRigidBodyFileNode);
        RegisterNode("ScrollContainer", CreateScrollContainerFileNode);
        RegisterNode("ShapeCast", CreateShapeCastFileNode);
        RegisterNode("SplitContainer", CreateSplitContainerFileNode);
        RegisterNode("StaticBody", CreateStaticBodyFileNode);
        RegisterNode("SubViewport", CreateSubViewportFileNode);
        RegisterNode("SubViewportContainer", CreateSubViewportContainerFileNode);
        RegisterNode("TabContainer", CreateTabContainerFileNode);
        RegisterNode("TabBar", CreateTabBarFileNode);
        RegisterNode("TextureButton", CreateTextureButtonFileNode);
        RegisterNode("TextureProgressBar", CreateTextureProgressBarFileNode);
        RegisterNode("TextureRect", CreateTextureRectFileNode);
        RegisterNode("Timer", CreateTimerFileNode);
        RegisterNode("VBoxContainer", CreateVBoxContainerFileNode);
        RegisterNode("VFlowContainer", CreateVFlowContainerFileNode);
        RegisterNode("VScrollBar", CreateVScrollBarFileNode);
        RegisterNode("VSlider", CreateVSliderFileNode);
        RegisterNode("VSplitContainer", CreateVSplitContainerFileNode);
        RegisterNode("VisibleOnScreenEnabler", CreateVisibleOnScreenEnablerFileNode);
        RegisterNode("VisibleOnScreenNotifier", CreateVisibleOnScreenNotifierFileNode);
        RegisterNode("Window", CreateWindowFileNode);
    }
    private static AnimatableBody CreateAnimatableBodyFileNode() => new();
    private static AnimatedSprite CreateAnimatedSpriteFileNode() => new();
    private static AnimationMixer CreateAnimationMixerFileNode() => new();
    private static AnimationPlayer CreateAnimationPlayerFileNode() => new();
    private static AnimationTree CreateAnimationTreeFileNode() => new();
    private static Area CreateAreaFileNode() => new();
    private static AspectRatioContainer CreateAspectRatioContainerFileNode() => new();
    private static AudioListener CreateAudioListenerFileNode() => new();
    private static AudioStreamEmitter CreateAudioStreamEmitterFileNode() => new();
    private static AudioStreamPlayer CreateAudioStreamPlayerFileNode() => new();
    private static BackBufferCopy CreateBackBufferCopyFileNode() => new();
    private static BoxContainer CreateBoxContainerFileNode() => new();
    private static Button CreateButtonFileNode() => new();
    private static Camera CreateCameraFileNode() => new();
    private static CanvasGroup CreateCanvasGroupFileNode() => new();
    private static CanvasLayer CreateCanvasLayerFileNode() => new();
    private static CenterContainer CreateCenterContainerFileNode() => new();
    private static CharacterBody CreateCharacterBodyFileNode() => new();
    private static CheckBox CreateCheckBoxFileNode() => new();
    private static CheckButton CreateCheckButtonFileNode() => new();
    private static CollisionPolygon CreateCollisionPolygonFileNode() => new();
    private static CollisionShape CreateCollisionShapeFileNode() => new();
    private static Container CreateContainerFileNode() => new();
    private static Control CreateControlFileNode() => new();
    private static DampedSpringJoint CreateDampedSpringJointFileNode() => new();
    private static FlowContainer CreateFlowContainerFileNode() => new();
    private static GridContainer CreateGridContainerFileNode() => new();
    private static GrooveJoint CreateGrooveJointFileNode() => new();
    private static HBoxContainer CreateHBoxContainerFileNode() => new();
    private static HFlowContainer CreateHFlowContainerFileNode() => new();
    private static HScrollBar CreateHScrollBarFileNode() => new();
    private static HSlider CreateHSliderFileNode() => new();
    private static HSplitContainer CreateHSplitContainerFileNode() => new();
    private static HTTPRequest CreateHTTPRequestFileNode() => new();
    private static ItemList CreateItemListFileNode() => new();
    private static Label CreateLabelFileNode() => new();
    private static Line CreateLineFileNode() => new();
    private static LineEdit CreateLineEditFileNode() => new();
    private static MarginContainer CreateMarginContainerFileNode() => new();
    private static MeshInstance CreateMeshInstanceFileNode() => new();
    private static MultiMeshInstance CreateMultiMeshInstanceFileNode() => new();
    private static MultiplayerSpawner CreateMultiplayerSpawnerFileNode() => new();
    private static MultiplayerSynchronizer CreateMultiplayerSynchronizerFileNode() => new();
    private static NinePatchRect CreateNinePatchRectFileNode() => new();
    private static Panel CreatePanelFileNode() => new();
    private static PanelContainer CreatePanelContainerFileNode() => new();
    private static Parallax CreateParallaxFileNode() => new();
    private static ParallaxBackground CreateParallaxBackgroundFileNode() => new();
    private static ParallaxLayer CreateParallaxLayerFileNode() => new();
    private static Path CreatePathFileNode() => new();
    private static PathFollow CreatePathFollowFileNode() => new();
    private static PinJoint CreatePinJointFileNode() => new();
    private static Polygon CreatePolygonFileNode() => new();
    private static RayCast CreateRayCastFileNode() => new();
    private static RemoteTransform CreateRemoteTransformFileNode() => new();
    private static RigidBody CreateRigidBodyFileNode() => new();
    private static ScrollContainer CreateScrollContainerFileNode() => new();
    private static ShapeCast CreateShapeCastFileNode() => new();
    private static SplitContainer CreateSplitContainerFileNode() => new();
    private static StaticBody CreateStaticBodyFileNode() => new();
    private static SubViewport CreateSubViewportFileNode() => new();
    private static SubViewportContainer CreateSubViewportContainerFileNode() => new();
    private static TabBar CreateTabBarFileNode() => new();
    private static TextureButton CreateTextureButtonFileNode() => new();
    private static TextureProgressBar CreateTextureProgressBarFileNode() => new();
    private static TextureRect CreateTextureRectFileNode() => new();
    private static Timer CreateTimerFileNode() => new();
    private static VBoxContainer CreateVBoxContainerFileNode() => new();
    private static VFlowContainer CreateVFlowContainerFileNode() => new();
    private static VScrollBar CreateVScrollBarFileNode() => new();
    private static VSlider CreateVSliderFileNode() => new();
    private static VSplitContainer CreateVSplitContainerFileNode() => new();
    private static VisibleOnScreenEnabler CreateVisibleOnScreenEnablerFileNode() => new();
    private static VisibleOnScreenNotifier CreateVisibleOnScreenNotifierFileNode() => new();
    private static Window CreateWindowFileNode() => new();
}
