my %targets = (
    "electron2d-apple" => {
        inherit_from => [ "darwin-common" ],
        bn_ops => "SIXTY_FOUR_BIT_LONG",
    },
    "electron2d-wasm" => {
        inherit_from => [ "linux-generic32" ],
    },
);
