my %targets = (
    "electron2d-win-x86" => {
        inherit_from => [ "VC-WIN32" ],
        cflags => "/Gs0 /GF /Gy /MT",
        multilib => "", shlib_variant => "-Electron2D",
    },
    "electron2d-win-x64" => {
        inherit_from => [ "VC-WIN64A" ],
        cflags => "/Gs0 /GF /Gy /MT",
        multilib => "", shlib_variant => "-Electron2D",
    },
    "electron2d-win-arm64" => {
        inherit_from => [ "VC-WIN64-ARM" ],
        # Forced probes corrupt the saved LR in small MSVC ARM64 /O2 frames.
        cflags => "/GF /Gy /MT",
        multilib => "", shlib_variant => "-Electron2D",
    },
);
