#!/usr/bin/env python3
"""Generate the GitHub Wiki from the compiled API snapshot and XML comments."""

import argparse
import hashlib
import json
import re
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MARKER = "<!-- Generated by tools/wiki/generate.py. Do not edit by hand. -->\n"
KINDS = {
    "type": "T", "constructor": "M", "method": "M", "operator": "M",
    "property": "P", "indexer": "P", "event": "E", "enumValue": "F",
    "field": "F", "constant": "F",
}
DOMAIN_NAMES = {
    "core": "Core", "input": "Input", "scene": "Scene", "localization": "Localization",
    "resources": "Resources", "display": "Display", "rendering": "Rendering",
    "navigation": "Navigation", "physics": "Physics", "audio": "Audio",
}
OLD_CATEGORY = {
    "API-Core": "core", "API-Scene-Tree": "scene", "API-Resources": "resources",
    "API-Math-and-Data": "core", "API-Input": "input",
    "API-Display-and-Localization": "display", "API-Rendering": "rendering",
    "API-Animation-and-Tweening": "scene", "API-Audio": "audio",
    "API-Physics": "physics", "API-UI-and-Text": "rendering",
    "API-Scripting-Metadata": "core",
}
OLD_TYPES = {
    "Object": "ElectronObject", "Node2D": "Entity", "AnimatedSprite2D": "AnimatedSprite",
    "Area2D": "Area", "Camera2D": "Camera", "Texture2D": "Texture",
    "Transform2D": "Transform", "PhysicsServer2D": "PhysicsServer",
    "PhysicsDirectSpaceState2D": "PhysicsDirectSpaceState",
    "CapsuleShape2D": "CapsuleShape", "CharacterBody2D": "CharacterBody",
    "CircleShape2D": "CircleShape", "CollisionObject2D": "CollisionObject",
    "CollisionShape2D": "CollisionShape", "ConcavePolygonShape2D": "ConcavePolygonShape",
    "ConvexPolygonShape2D": "ConvexPolygonShape", "PhysicsBody2D": "PhysicsBody",
    "RayCast2D": "RayCast", "RectangleShape2D": "RectangleShape",
    "RigidBody2D": "RigidBody", "SegmentShape2D": "SegmentShape",
    "Shape2D": "Shape", "Sprite2D": "Sprite", "StaticBody2D": "StaticBody",
    "Rect2I": "Rect2i", "Vector2I": "Vector2i", "Rid": "RID",
    "SizeFlags": "Control.SizeFlags", "BoxContainerAlignmentMode": "BoxContainer.AlignmentMode",
}


def plain(element):
    if element is None:
        return ""
    parts = []

    def visit(node):
        if node.text:
            parts.append(node.text)
        for child in node:
            if child.tag == "see":
                parts.append(child.attrib.get("cref", "").split(":", 1)[-1])
            elif child.tag == "paramref":
                parts.append(child.attrib.get("name", ""))
            elif child.tag == "c":
                parts.append("`" + "".join(child.itertext()).strip() + "`")
            else:
                visit(child)
            if child.tail:
                parts.append(child.tail)

    visit(element)
    return re.sub(r"\s+", " ", "".join(parts)).strip()


def xml_id(record):
    value = record["id"].split(":", 1)[1].replace("..ctor", ".#ctor")
    head, separator, parameters = value.partition("(")
    head = re.sub(
        r"<([^<>]+)>",
        lambda match: ("``" if record["kind"] != "type" and match.start() > head.rfind(".") else "`")
        + str(match.group(1).count(",") + 1),
        head,
    )
    value = head + separator + parameters
    value = re.sub(r"<([^<>]+)>", lambda m: "{" + m.group(1).replace(" ", "") + "}", value)
    value = re.sub(r"\{([^{}]+)\}", lambda m: "{" + m.group(1).replace(" ", "") + "}", value)
    value = value.removesuffix("()")
    return KINDS[record["kind"]] + ":" + value


def anchor(record):
    return "member-" + hashlib.sha1(record["id"].encode()).hexdigest()[:12]


def escape(value):
    return value.replace("|", "\\|").replace("\n", " ")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", type=Path, default=ROOT / "bin/wiki",
                        help="wiki clone or generated candidate directory (default: bin/wiki)")
    parser.add_argument("--check", action="store_true", help="fail if output differs")
    args = parser.parse_args()
    output = args.output.resolve()
    data = json.loads((ROOT / "docs/coverage/data/electron2d.json").read_text())
    xml_path = ROOT / "bin/Release/net10.0/Electron2D.xml"
    if not xml_path.is_file():
        parser.error("build the Release runtime first; Electron2D.xml is missing")
    xml = {item.attrib["name"]: item for item in ET.parse(xml_path).iter("member")}
    types = {r["declaringType"]: r for r in data if r["kind"] == "type"}
    members = defaultdict(list)
    for record in data:
        if record["kind"] != "type":
            members[record["declaringType"]].append(record)
    inventory = (ROOT / "docs/inventory.md").read_text()
    domains = {}
    for line in inventory.splitlines():
        match = re.search(r"\]\(domains/([a-z-]+)\.md\)", line)
        if match:
            for page in re.findall(r"\]\(classes/([^()]+\.md)\)", line):
                domains.setdefault(Path(page).stem, match.group(1))
    names = {full.removeprefix("Electron2D.") for full in types}

    def kind(record):
        match = re.search(r"\b(class|struct|enum|interface|delegate)\b", record["signature"])
        return match.group(1) if match else "type"

    def category(name):
        if name in domains:
            return domains[name]
        if "." in name and name.split(".")[0] in domains:
            return domains[name.split(".")[0]]
        return "other"

    def page_name(name):
        return name.replace(".", "-").replace("<", "-of-").replace(">", "").replace(", ", "-and-")

    if len({page_name(name) for name in names}) != len(names):
        raise ValueError("two public types map to the same wiki page")

    def type_link(name):
        return f"[{name}]({page_name(name)})"

    nav = "[Home](Home) | [API by Category](API-by-Category) | [Complete API Index](API-Reference) | [API Status](API-Status)"
    pages = {}
    for full, record in sorted(types.items()):
        name = full.removeprefix("Electron2D.")
        desc = xml.get(xml_id(record))
        summary = plain(desc.find("summary")) if desc is not None else ""
        cat = category(name)
        cat_link = f"[API {DOMAIN_NAMES[cat]}](API-{DOMAIN_NAMES[cat]})" if cat != "other" else "[Other](API-Other)"
        lines = [MARKER, nav, "", f"<!-- Page title: {name} -->", "", "| Field | Value |", "| --- | --- |",
                 f"| Full name | `{full}` |", "| Namespace | `Electron2D` |",
                 f"| Kind | `{kind(record)}` |",
                 f"| Category | {cat_link} |", "", "## Overview", "", summary or "See the declaration and member documentation below.",
                 "", "## Syntax", "", "```csharp", record["signature"], "```", ""]
        remarks = plain(desc.find("remarks")) if desc is not None else ""
        if remarks:
            lines += ["### Remarks", "", remarks, ""]
        base = record.get("baseType")
        if base and base in types:
            lines += [f"**Inherits:** {type_link(base.removeprefix('Electron2D.'))}", ""]
        source_page = ROOT / "docs/classes" / f"{name}.md"
        if source_page.exists():
            lines += [f"[Detailed engine reference](https://github.com/edwardgushchin/Electron2D/blob/main/docs/classes/{name}.md)", ""]
        own = sorted(members[full], key=lambda r: (r["kind"], r["name"], r["id"]))
        if own:
            lines += ["## Members", "", "| Member | Kind | Summary |", "| --- | --- | --- |"]
            for member in own:
                doc = xml.get(xml_id(member))
                brief = plain(doc.find("summary")) if doc is not None else ""
                label = member["signature"].replace("`", "'")
                lines.append(f"| [`{escape(label)}`](#{anchor(member)}) | {member['kind']} | {escape(brief)} |")
            lines += ["", "## Member Details", ""]
            for member in own:
                doc = xml.get(xml_id(member))
                lines += [f"<a id=\"{anchor(member)}\"></a>", f"### {member['name']}", "",
                          f"Kind: `{member['kind']}`", "", "```csharp", member["signature"], "```", ""]
                if doc is not None:
                    for tag, title in (("summary", "Summary"), ("remarks", "Remarks"), ("value", "Value"), ("returns", "Returns")):
                        value = plain(doc.find(tag))
                        if value:
                            lines += [f"#### {title}", "", value, ""]
                    params = [(p.attrib.get("name", ""), plain(p)) for p in doc.findall("param")]
                    if params:
                        lines += ["#### Parameters", ""]
                        lines += [f"- `{key}`: {value}" for key, value in params]
                        lines.append("")
                    exceptions = [(e.attrib.get("cref", ""), plain(e)) for e in doc.findall("exception")]
                    if exceptions:
                        lines += ["#### Exceptions", ""]
                        lines += [f"- `{key}`: {value}" for key, value in exceptions]
                        lines.append("")
        pages[page_name(name) + ".md"] = "\n".join(lines).rstrip() + "\n"

    grouped = defaultdict(list)
    for name in sorted(names, key=str.casefold):
        grouped[category(name)].append(name)
    category_pages = []
    for key in [*DOMAIN_NAMES, "other"]:
        if not grouped[key]:
            continue
        label = DOMAIN_NAMES.get(key, "Other")
        slug = "API-" + label
        category_pages.append((slug, label, len(grouped[key])))
        pages[slug + ".md"] = MARKER + "\n" + nav + f"\n\n<!-- Page title: API {label} -->\n\n# {label}\n\n" + "\n".join(f"- {type_link(name)}" for name in grouped[key]) + "\n"
    pages["API-by-Category.md"] = MARKER + "\n" + nav + "\n\n<!-- Page title: API by Category -->\n\nBrowse the public runtime API by domain.\n\n| Category | Types |\n| --- | ---: |\n" + "\n".join(f"| [{label}]({slug}) | {count} |" for slug, label, count in category_pages) + "\n"
    index_rows = []
    for name in sorted(names, key=str.casefold):
        record = types["Electron2D." + name]
        doc = xml.get(xml_id(record))
        summary = plain(doc.find("summary")) if doc is not None else ""
        index_rows.append(f"| {type_link(name)} | {kind(record)} | {escape(summary)} |")
    pages["API-Reference.md"] = MARKER + "\n" + nav + f"\n\n<!-- Page title: API Reference -->\n\nComplete generated public type index: {len(types)} types.\n\n| Type | Kind | Summary |\n| --- | --- | --- |\n" + "\n".join(index_rows) + "\n"
    pages["Home.md"] = MARKER + f"\n# Electron2D\n\nElectron2D is a C# and .NET 10 game engine for 2D projects. This wiki is generated from the compiled public runtime API and its XML documentation.\n\n- [API by Category](API-by-Category)\n- [Complete API Index](API-Reference) — {len(types)} current types\n- [API Status](API-Status)\n- [Platform verification](https://github.com/edwardgushchin/Electron2D/blob/main/docs/platform-verification.md)\n\nThe runtime is under active development. Read the type pages for exact signatures and the maintained [engine documentation](https://github.com/edwardgushchin/Electron2D/blob/main/docs/README.md) for behavior and limitations.\n"
    pages["API-Status.md"] = MARKER + "\n" + nav + "\n\n# API status\n\nThese pages describe declarations in the current compiled public API. A declaration alone does not establish semantic or platform verification. Consult the maintained [engine documentation](https://github.com/edwardgushchin/Electron2D/blob/main/docs/README.md) and [platform verification matrix](https://github.com/edwardgushchin/Electron2D/blob/main/docs/platform-verification.md).\n"
    pages["API-Compatibility.md"] = MARKER + "\n" + nav + "\n\n# API status\n\nThe former preview table has been superseded by the [current API status](API-Status) and [complete API index](API-Reference).\n"
    pages["_Sidebar.md"] = MARKER + "\n# Electron2D\n\n- [Home](Home)\n- [API by Category](API-by-Category)\n- [Complete API Index](API-Reference)\n- [API Status](API-Status)\n\n## API Areas\n\n" + "\n".join(f"- [{label}]({slug})" for slug, label, _ in category_pages) + "\n\n## Common API\n\n" + "\n".join(f"- {type_link(name)}" for name in ("Node", "CanvasItem", "Entity", "SceneTree", "Resource", "Vector2", "Input", "Sprite", "Area", "RigidBody") if name in names) + "\n"
    pages["_Footer.md"] = MARKER + "\n" + nav + "\n"
    # Existing bookmarks retain a generated explanation when a preview name vanished.
    if output.is_dir():
        for old in output.glob("*.md"):
            if old.name in pages or not old.read_text().startswith("<!-- Generated by "):
                continue
            stem = old.stem
            if stem.startswith("API-") and stem in OLD_CATEGORY:
                target = "API-" + DOMAIN_NAMES[OLD_CATEGORY[stem]]
            else:
                target_name = OLD_TYPES.get(stem, stem.replace("-", "."))
                target = page_name(target_name) if target_name in names else "API-Reference"
            pages[old.name] = MARKER + f"\n# {stem.replace('-', '.')}\n\nThis former page is superseded by [{target.replace('-', ' ')}]({target}). Use the current API signature and documentation there.\n"
    for name, body in pages.items():
        if re.search("godot", body, re.IGNORECASE):
            raise ValueError(f"external engine name in generated page: {name}")
        for target in re.findall(r"\]\(([^)#]+)(?:#[^)]*)?\)", body):
            if "://" not in target and target + ".md" not in pages:
                raise ValueError(f"broken wiki link: {name} -> {target}")
    if output.is_dir():
        foreign = [path.name for path in output.glob("*.md") if path.name not in pages]
        if foreign:
            raise ValueError(f"unmanaged wiki pages: {', '.join(foreign)}")
    changed = [name for name, body in pages.items() if not (output / name).exists() or (output / name).read_text() != body]
    if args.check:
        if changed:
            raise SystemExit(f"{len(changed)} wiki pages need regeneration")
    else:
        output.mkdir(parents=True, exist_ok=True)
        for name in changed:
            (output / name).write_text(pages[name])
    print(f"{len(types)} public types, {len(data)} declarations, {len(pages)} wiki pages, {len(changed)} changed")


if __name__ == "__main__":
    main()
