using System.Globalization;
using System.Text;
namespace Electron2D;

public partial class RichTextLabel
{
    private static Color ValidColor(Color color) { if (!color.IsFinite()) throw new ArgumentException("Color must be finite."); return color; }
    /// <summary>Pushes the themed normal font role.</summary>
    public void PushNormal() => Push(_format with { Role = FontRole.Normal, Font = null });
    /// <summary>Pushes the themed bold font role.</summary>
    public void PushBold() => Push(_format with { Role = FontRole.Bold, Font = null });
    /// <summary>Pushes the themed italics font role.</summary>
    public void PushItalics() => Push(_format with { Role = FontRole.Italics, Font = null });
    /// <summary>Pushes the themed bolditalics font role.</summary>
    public void PushBoldItalics() => Push(_format with { Role = FontRole.BoldItalics, Font = null });
    /// <summary>Pushes the themed mono font role.</summary>
    public void PushMono() => Push(_format with { Role = FontRole.Mono, Font = null });
    /// <summary>Pushes finite color styling.</summary><param name="color">Finite color.</param>
    public void PushColor(Color color) => Push(_format with { Color = ValidColor(color) });
    /// <summary>Pushes finite bgcolor styling.</summary><param name="color">Finite color.</param>
    public void PushBGColor(Color color) => Push(_format with { BG = ValidColor(color) });
    /// <summary>Pushes finite fgcolor styling.</summary><param name="color">Finite color.</param>
    public void PushFGColor(Color color) => Push(_format with { FG = ValidColor(color) });
    /// <summary>Pushes finite outlinecolor styling.</summary><param name="color">Finite color.</param>
    public void PushOutlineColor(Color color) => Push(_format with { OutlineColor = ValidColor(color) });
    /// <summary>Pushes a borrowed font and optional positive font size.</summary><param name="font">Live font.</param><param name="fontSize">Zero inherits size.</param>
    public void PushFont(Font font, int fontSize = 0) { ArgumentNullException.ThrowIfNull(font); if (font.IsDisposed) throw new ObjectDisposedException(nameof(font)); if (fontSize < 0) throw new ArgumentOutOfRangeException(nameof(fontSize)); Push(_format with { Font = font, Size = fontSize }); }
    /// <summary>Pushes a positive font size.</summary><param name="fontSize">Positive pixel size.</param>
    public void PushFontSize(int fontSize) { Font.ValidateSize(fontSize); Push(_format with { Size = fontSize }); }
    /// <summary>Pushes a nonnegative glyph outline width.</summary><param name="outlineSize">Pixel width.</param>
    public void PushOutlineSize(int outlineSize) { if (outlineSize < 0) throw new ArgumentOutOfRangeException(nameof(outlineSize)); Push(_format with { OutlineSize = outlineSize }); }
    /// <summary>Pushes underline styling.</summary><param name="color">Transparent or null follows the text color.</param>
    public void PushUnderline(Color? color = null) => Push(_format with { Underline = true, UnderlineColor = color is { } c ? ValidColor(c) : null });
    /// <summary>Pushes strikethrough styling.</summary><param name="color">Transparent or null follows the text color.</param>
    public void PushStrikethrough(Color? color = null) => Push(_format with { Strike = true, StrikeColor = color is { } c ? ValidColor(c) : null });
    /// <summary>Pushes a shaping language.</summary><param name="language">Nonnull language.</param>
    public void PushLanguage(string language) { ArgumentNullException.ThrowIfNull(language); Push(_format with { Language = language }); }
    /// <summary>Pushes a hover description.</summary><param name="description">Nonnull hint.</param>
    public void PushHint(string description) { ArgumentNullException.ThrowIfNull(description); Push(_format with { Hint = description }); }
    /// <summary>Pushes typed borrowed link metadata.</summary><typeparam name="T">Metadata type.</typeparam><param name="data">Borrowed payload.</param><param name="underlineMode">Link underline policy.</param><param name="tooltip">Nonnull optional hover text.</param>
    public void PushMeta<T>(T data, MetaUnderline underlineMode = MetaUnderline.Always, string tooltip = "") { ArgumentNullException.ThrowIfNull(tooltip); if (!Enum.IsDefined(underlineMode)) throw new ArgumentOutOfRangeException(nameof(underlineMode)); Push(_format with { Meta = RichTextMetadata.Create(data), MetaUnderline = underlineMode, MetaTooltip = tooltip }); }
    /// <summary>Pushes paragraph indentation.</summary><param name="level">Nonnegative tab levels.</param>
    public void PushIndent(int level) { if (level < 0) throw new ArgumentOutOfRangeException(nameof(level)); MutableRich(); if (Current.Parts.Count > 0) Newline(); Push(_format with { Indent = level }); Add(new(PartKind.Marker, _format)); }
    /// <summary>Pushes an ordered or bulleted list.</summary><param name="level">Nonnegative indentation.</param><param name="type">List domain.</param><param name="capitalize">Uppercase numeric markers.</param><param name="bullet">Nonnull bullet text.</param>
    public void PushList(int level, ListType type, bool capitalize, string bullet = "•") { if (level < 0 || !Enum.IsDefined(type)) throw new ArgumentOutOfRangeException(nameof(level)); ArgumentNullException.ThrowIfNull(bullet); MutableRich(); if (Current.Parts.Count > 0) Newline(); Push(_format with { Indent = level, List = type, Capitalize = capitalize, Bullet = bullet }); Add(new(PartKind.Marker, _format)); }
    /// <summary>Starts an explicitly configured paragraph context.</summary><param name="alignment">Horizontal alignment.</param><param name="baseDirection">Text direction.</param><param name="language">Nonnull shaping language.</param><param name="stParser">Structured parser.</param><param name="justificationFlags">Fill flags.</param><param name="tabStops">Copied tab positions.</param>
    public void PushParagraph(HorizontalAlignment alignment, TextDirection baseDirection = TextDirection.Auto, string language = "", StructuredTextParser stParser = StructuredTextParser.Default, TextJustificationFlags justificationFlags = (TextJustificationFlags)163, float[]? tabStops = null)
    { MutableRich(); ArgumentNullException.ThrowIfNull(language); if (!Enum.IsDefined(alignment) || !Enum.IsDefined(baseDirection) || !Enum.IsDefined(stParser)) throw new ArgumentOutOfRangeException(nameof(alignment)); if (tabStops != null && tabStops.Any(v => !float.IsFinite(v) || v < 0)) throw new ArgumentException("Invalid tab positions.", nameof(tabStops)); if (Current.Parts.Count > 0) Newline(); Push(_format with { Paragraph = new(alignment, baseDirection, language, stParser, justificationFlags, tabStops is null ? [] : (float[])tabStops.Clone()) }); ApplyParagraph(Current); Changed(); }
    /// <summary>Pushes a borrowed custom effect and its shared typed parameter context.</summary><param name="effect">Live resource.</param><param name="env">Borrowed arguments.</param>
    public void PushCustomFX(RichTextEffect effect, RichTextEffectEnvironment env) { ArgumentNullException.ThrowIfNull(effect); ArgumentNullException.ThrowIfNull(env); if (effect.IsDisposed) throw new ObjectDisposedException(nameof(effect)); PushFX("custom", env, effect); }
    private void PushFX(string kind, RichTextEffectEnvironment env, RichTextEffect? effect = null)
    { var fx = new FX { Kind = kind, Effect = effect, Env = env, Parent = _format.Effects, Started = _elapsed, Start = GetTotalCharacterCount() }; _ownedFX.Add(fx); Push(_format with { Effects = fx }); }
    /// <summary>Adds a horizontal rule.</summary><param name="width">Nonnegative width.</param><param name="height">Nonnegative height.</param><param name="color">Finite tint or white.</param><param name="alignment">Horizontal position.</param><param name="widthInPercent">Width is a percentage of content width.</param><param name="heightInPercent">Height is a percentage of content width.</param>
    public void AddHR(int width = 90, int height = 2, Color? color = null, HorizontalAlignment alignment = HorizontalAlignment.Center, bool widthInPercent = true, bool heightInPercent = false)
    { if (!Enum.IsDefined(alignment)) throw new ArgumentOutOfRangeException(nameof(alignment)); if (width < 0 || height < 0) throw new ArgumentOutOfRangeException(nameof(width)); Add(new(PartKind.Rule, _format) { Width = width, Height = height, Color = ValidColor(color ?? Colors.White), WidthPercent = widthInPercent, HeightPercent = heightInPercent, Text = ((int)alignment).ToString(CultureInfo.InvariantCulture) }); }
    /// <summary>Adds an unkeyed borrowed inline image.</summary><param name="image">Live texture.</param><param name="width">Nonnegative width.</param><param name="height">Nonnegative height.</param><param name="color">Tint or white.</param><param name="inlineAlign">Object alignment.</param><param name="region">Source region or zero for the texture.</param><param name="pad">Pads smaller source images.</param><param name="tooltip">Hover text.</param><param name="widthUnit">Width units.</param><param name="heightUnit">Height units.</param><param name="altText">Assistive description.</param>
    public void AddImage(Texture image, float width = 0, float height = 0, Color? color = null, InlineAlignment inlineAlign = InlineAlignment.Center, Rect2 region = default, bool pad = false, string tooltip = "", ImageUnit widthUnit = ImageUnit.Pixel, ImageUnit heightUnit = ImageUnit.Pixel, string altText = "") => AddImageCore(image, width, height, color, inlineAlign, region, null, pad, tooltip, widthUnit, heightUnit, altText);
    /// <summary>Adds an image with an exact typed update key.</summary><typeparam name="T">Key type.</typeparam><param name="image">Borrowed texture.</param><param name="key">Borrowed key.</param><param name="width">Width.</param><param name="height">Height.</param><param name="color">Tint.</param><param name="inlineAlign">Alignment.</param><param name="region">Source region.</param><param name="pad">Padding mode.</param><param name="tooltip">Hover text.</param><param name="widthUnit">Width unit.</param><param name="heightUnit">Height unit.</param><param name="altText">Assistive description.</param>
    public void AddImage<T>(T key, Texture image, float width = 0, float height = 0, Color? color = null, InlineAlignment inlineAlign = InlineAlignment.Center, Rect2 region = default, bool pad = false, string tooltip = "", ImageUnit widthUnit = ImageUnit.Pixel, ImageUnit heightUnit = ImageUnit.Pixel, string altText = "") => AddImageCore(image, width, height, color, inlineAlign, region, new ImageKey<T>(key), pad, tooltip, widthUnit, heightUnit, altText);
    private static void ValidateInline(InlineAlignment alignment) { if ((uint)alignment > 15) throw new ArgumentOutOfRangeException(nameof(alignment)); }
    private static void ValidateImage(Texture image, float width, float height, Rect2 region, string tooltip, ImageUnit wu, ImageUnit hu, string alt)
    { ArgumentNullException.ThrowIfNull(image); if (image.IsDisposed) throw new ObjectDisposedException(nameof(image)); if (!float.IsFinite(width) || !float.IsFinite(height) || width < 0 || height < 0 || !region.IsFinite() || region.Size.X < 0 || region.Size.Y < 0) throw new ArgumentException("Invalid image dimensions."); ArgumentNullException.ThrowIfNull(tooltip); ArgumentNullException.ThrowIfNull(alt); if (!Enum.IsDefined(wu) || !Enum.IsDefined(hu)) throw new ArgumentOutOfRangeException(nameof(wu)); }
    private void AddImageCore(Texture image, float width, float height, Color? color, InlineAlignment align, Rect2 region, ImageKey? key, bool pad, string tooltip, ImageUnit wu, ImageUnit hu, string alt)
    { ValidateImage(image, width, height, region, tooltip, wu, hu, alt); ValidateInline(align); Add(new(PartKind.Image, _format) { Texture = image, Width = width, Height = height, Color = ValidColor(color ?? Colors.White), Alignment = align, Region = region, Key = key, Pad = pad, Tooltip = tooltip, WidthUnit = wu, HeightUnit = hu, Alt = alt }); }
    /// <summary>Updates matching image keys under the specified mask.</summary><typeparam name="T">Exact key type.</typeparam><param name="key">Matching key.</param><param name="mask">Fields to replace.</param><param name="image">Live replacement texture when the Texture mask is set; otherwise ignored.</param><param name="width">Width.</param><param name="height">Height.</param><param name="color">Tint.</param><param name="inlineAlign">Alignment.</param><param name="region">Source region.</param><param name="pad">Padding.</param><param name="tooltip">Hover text.</param><param name="widthUnit">Width units.</param><param name="heightUnit">Height units.</param>
    public void UpdateImage<T>(T key, ImageUpdateMask mask, Texture? image, float width = 0, float height = 0, Color? color = null, InlineAlignment inlineAlign = InlineAlignment.Center, Rect2 region = default, bool pad = false, string tooltip = "", ImageUnit widthUnit = ImageUnit.Pixel, ImageUnit heightUnit = ImageUnit.Pixel)
    { MutableRich(); if ((mask & ImageUpdateMask.Texture) != 0) { ArgumentNullException.ThrowIfNull(image); if (image.IsDisposed) throw new ObjectDisposedException(nameof(image)); } if (!float.IsFinite(width) || !float.IsFinite(height) || width < 0 || height < 0 || !region.IsFinite() || region.Size.X < 0 || region.Size.Y < 0) throw new ArgumentException("Invalid image dimensions."); ArgumentNullException.ThrowIfNull(tooltip); if (!Enum.IsDefined(widthUnit) || !Enum.IsDefined(heightUnit)) throw new ArgumentOutOfRangeException(nameof(widthUnit)); ValidateInline(inlineAlign); if (((int)mask & ~255) != 0) throw new ArgumentOutOfRangeException(nameof(mask)); var tint = ValidColor(color ?? Colors.White); foreach (var part in AllParts(_main)) { if (part.Kind != PartKind.Image || !(part.Key?.Matches(key) ?? key is null)) continue; if ((mask & ImageUpdateMask.Texture) != 0) part.Texture = image; if ((mask & ImageUpdateMask.Size) != 0) { part.Width = width; part.Height = height; } if ((mask & ImageUpdateMask.Color) != 0) part.Color = tint; if ((mask & ImageUpdateMask.Alignment) != 0) part.Alignment = inlineAlign; if ((mask & ImageUpdateMask.Region) != 0) part.Region = region; if ((mask & ImageUpdateMask.Pad) != 0) part.Pad = pad; if ((mask & ImageUpdateMask.Tooltip) != 0) part.Tooltip = tooltip; if ((mask & ImageUpdateMask.WidthUnit) != 0) { part.WidthUnit = widthUnit; part.HeightUnit = heightUnit; } } Changed(); }
    private static IEnumerable<Part> AllParts(Frame frame) { foreach (var paragraph in frame.Paragraphs) foreach (var part in paragraph.Parts) { yield return part; if (part.Table is { } table) foreach (var cell in table.Cells) foreach (var child in AllParts(cell.Frame)) yield return child; } }
    /// <summary>Adds the paragraph's independently shaped initial drop cap.</summary><param name="text">Nonnull cap text.</param><param name="font">Borrowed font.</param><param name="size">Positive size.</param><param name="dropcapMargins">Left/top/right/bottom margins.</param><param name="color">Cap color.</param><param name="outlineSize">Nonnegative outline width.</param><param name="outlineColor">Outline tint.</param>
    public void PushDropcap(string text, Font font, int size, Rect2 dropcapMargins = default, Color? color = null, int outlineSize = 0, Color? outlineColor = null)
    { ArgumentNullException.ThrowIfNull(text); ArgumentNullException.ThrowIfNull(font); Font.ValidateSize(size); if (font.IsDisposed) throw new ObjectDisposedException(nameof(font)); if (outlineSize < 0 || !dropcapMargins.IsFinite()) throw new ArgumentException("Invalid drop cap geometry."); Add(new(PartKind.Dropcap, _format) { Text = text, DropFont = font, DropSize = size, DropMargins = dropcapMargins, Color = ValidColor(color ?? Colors.White), DropOutline = outlineSize, DropOutlineColor = ValidColor(outlineColor ?? new Color(0, 0, 0, 0)) }); }
    /// <summary>Pushes an inline table.</summary><param name="columns">Positive column count.</param><param name="inlineAlign">Inline alignment.</param><param name="alignToRow">-1 or row alignment index.</param><param name="name">Nonnull assistive name.</param>
    public void PushTable(int columns, InlineAlignment inlineAlign = InlineAlignment.Top, int alignToRow = -1, string name = "")
    { MutableRich(); ValidateInline(inlineAlign); if (alignToRow < -1) throw new ArgumentOutOfRangeException(nameof(alignToRow)); if (columns < 1 || columns > 65536) throw new ArgumentOutOfRangeException(nameof(columns)); ArgumentNullException.ThrowIfNull(name); var table = new Table(columns) { AlignRow = alignToRow, Name = name }; Add(new(PartKind.Table, _format) { Table = table, Alignment = inlineAlign }); Push(_format); _table = table; }
    /// <summary>Pushes the next table cell frame.</summary>
    public void PushCell() { MutableRich(); if (_table == null) throw new InvalidOperationException("A cell requires an active table."); var cell = new Cell(); _table.Cells.Add(cell); Push(_format); _frame = cell.Frame; }
    private Cell CellNow() => _frame.Cell ?? throw new InvalidOperationException("The operation requires an active cell.");
    /// <summary>Configures table expansion weight and shrink participation.</summary><param name="column">Existing column.</param><param name="expand">Expansion.</param><param name="ratio">Positive weight.</param><param name="shrink">Shrink participation.</param>
    public void SetTableColumnExpand(int column, bool expand, int ratio = 1, bool shrink = true) { MutableRich(); if (_table == null || (uint)column >= _table.Columns.Length || ratio < 1) throw new ArgumentOutOfRangeException(nameof(column)); var item = _table.Columns[column]; item.Expand = expand; item.Ratio = ratio; item.Shrink = shrink; Changed(); }
    /// <summary>Sets a table column's assistive name.</summary><param name="column">Existing column.</param><param name="name">Nonnull name.</param>
    public void SetTableColumnName(int column, string name) { MutableRich(); ArgumentNullException.ThrowIfNull(name); if (_table == null || (uint)column >= _table.Columns.Length) throw new ArgumentOutOfRangeException(nameof(column)); _table.Columns[column].Name = name; }
    /// <summary>Sets cell border tint.</summary><param name="color">Finite color.</param>
    public void SetCellBorderColor(Color color) { MutableRich(); CellNow().Border = ValidColor(color); Changed(); }
    /// <summary>Sets alternating cell row backgrounds.</summary><param name="oddRowBG">Odd tint.</param><param name="evenRowBG">Even tint.</param>
    public void SetCellRowBackgroundColor(Color oddRowBG, Color evenRowBG) { MutableRich(); var cell = CellNow(); var odd = ValidColor(oddRowBG); var even = ValidColor(evenRowBG); cell.Odd = odd; cell.Even = even; Changed(); }
    /// <summary>Sets left/top/right/bottom cell padding.</summary><param name="padding">Finite nonnegative margins.</param>
    public void SetCellPadding(Rect2 padding) { MutableRich(); if (!padding.IsFinite() || padding.Position.X < 0 || padding.Position.Y < 0 || padding.Size.X < 0 || padding.Size.Y < 0) throw new ArgumentException("Invalid padding.", nameof(padding)); CellNow().Padding = padding; Changed(); }
    /// <summary>Overrides cell minimum and maximum sizes.</summary><param name="minSize">Finite nonnegative minimum.</param><param name="maxSize">Finite nonnegative maximum; zero is unlimited.</param>
    public void SetCellSizeOverride(Vector2 minSize, Vector2 maxSize) { MutableRich(); if (!minSize.IsFinite() || !maxSize.IsFinite() || minSize.X < 0 || minSize.Y < 0 || maxSize.X < 0 || maxSize.Y < 0) throw new ArgumentException("Invalid size bounds."); var cell = CellNow(); cell.Minimum = minSize; cell.Maximum = maxSize; Changed(); }
}
