/*
 * Electron2D
 * MIT License
 * Copyright (c) 2025-2026 Eduard Gushchin <eduardgushchin@yandex.ru>
 * SPDX-License-Identifier: MIT
 */

const english = {
  "board.title": "Electron2D Task Board",
  "board.search": "Search tasks",
  "board.searchPlaceholder": "Search tasks…",
  "board.filters": "Filters",
  "board.resetFilters": "Reset filters",
  "board.priority": "Priority",
  "board.allPriorities": "All priorities",
  "board.tags": "Tags",
  "board.allTags": "All tags",
  "board.selectedTags": "{0} tags selected",
  "board.archive": "Archive",
  "board.refresh": "Refresh board",
  "board.tagSettings": "Manage board tags",
  "board.createTask": "Create task",
  "board.ariaLabel": "Task board",
  "board.showAllColumn": "Show all tasks in the “{0}” column",
  "board.showAll": "Show all tasks",
  "board.collapseColumn": "Collapse the “{0}” column",
  "board.collapse": "Collapse column",
  "board.expandColumn": "Expand the “{0}” column",
  "board.expand": "Expand column",
  "board.moreTasks": "+ {0} more",
  "indicator.blockers": "Blocking reasons",
  "indicator.dependencies": "Dependencies",
  "indicator.labels": "Labels",
  "indicator.deadline": "Deadline",
  "indicator.checklist": "Acceptance checklist",
  "indicator.attachments": "Attached files",
  "indicator.awaitingDecision": "Awaiting user decision",
  "indicator.done": "Done",
  "task.loading": "Loading task details…",
  "task.sections": "Task sections",
  "task.tab.overview": "Overview",
  "task.tab.details": "Details",
  "task.tab.dependencies": "Dependencies",
  "task.tab.activity": "Activity",
  "task.edit": "Edit",
  "task.attach": "Attach file",
  "task.addTag": "Add tag",
  "task.archive": "Archive",
  "task.reopen": "Return to work",
  "task.reopenReason": "Reopened by the user in VS Code Task Board.",
  "task.submit": "Submit for acceptance",
  "task.submitPrompt": "Submission comment",
  "task.accept": "Accept",
  "task.acceptPrompt": "Acceptance reason",
  "task.acceptReason": "Accepted by the user in VS Code Task Board.",
  "task.acceptUnavailable": "All acceptance criteria must be passed before this task can be accepted.",
  "task.requestChanges": "Return to work",
  "task.requestChangesPrompt": "What needs to change",
  "task.unarchive": "Restore from archive",
  "task.close": "Close",
  "task.editLabel": "Edit task",
  "task.waitForLoading": "Wait for the task to load",
  "task.back": "Back to previous task",
  "task.closeDetails": "Close task details",
  "task.createDialogTitle": "Create task",
  "task.create": "Create",
  "task.creating": "Creating…",
  "task.cancelCreate": "Cancel",
  "task.closeCreate": "Close task creation",
  "task.titleRequired": "Required field",
  "task.formDeadlineOptional": "Deadline (optional)",
  "task.deadlineInvalid": "Enter an existing date in YYYY-MM-DD format.",
  "task.createFailed": "The task could not be created. Check the values and try again.",
  "task.copyNumber": "Copy task number",
  "task.numberCopied": "Task number copied",
  "task.breadcrumb": "TASKS",
  "task.formDeadline": "Deadline (YYYY-MM-DD, leave empty to clear)",
  "tags.create": "Create a tag",
  "tags.edit": "Edit tag",
  "tags.delete": "Delete tag",
  "tags.selectForTask": "Select a tag or create a global one",
  "tags.selectAction": "Choose what to do with “{0}”",
  "tags.namePrompt": "Tag name",
  "tags.colorPrompt": "Tag color (legacy name or #RRGGBB)",
  "tags.colorInvalid": "Use Gray, Blue, Green, Yellow, Orange, Red, Purple, or an exact #RRGGBB value.",
  "tags.noneAvailable": "All available tags are already assigned",
  "overview.goal": "Goal",
  "overview.steps": "What needs to be done",
  "overview.context": "Context",
  "overview.contextIntro": "Task type: `{0}`. Readiness: `{1}`.",
  "overview.notSpecifiedLower": "not specified",
  "overview.stopCondition": "Stop condition: {0}",
  "overview.summary": "Summary",
  "overview.linkedFiles": "Linked files",
  "overview.attachments": "Attached files",
  "overview.directories": "Project directories/areas",
  "chat.title": "Chat with agent",
  "chat.agent": "Agent",
  "chat.user": "You",
  "chat.empty": "No messages yet. Ask the agent about this task.",
  "chat.placeholder": "Message the agent about this task…",
  "chat.send": "Send",
  "chat.cancel": "Cancel",
  "chat.permissionOnce": "Allow once",
  "chat.permissionSession": "Allow for session",
  "chat.permissionReject": "Reject",
  "chat.connecting": "Connecting to the agent…",
  "chat.alreadyRunning": "This task already has an active agent run.",
  "chat.staleTask": "The task changed. Reload it before sending a message.",
  "chat.contextChanged": "The task context changed during the agent run. The response was not stored; review the new revision and send again.",
  "chat.cancelled": "Agent run cancelled.",
  "chat.noActiveRun": "There is no active agent run for this task.",
  "details.status": "Status",
  "details.taskNumber": "Task number",
  "details.priority": "Priority",
  "details.tags": "Tags",
  "details.relatedTasks": "Related tasks",
  "details.readiness": "Readiness",
  "details.taskType": "Task type",
  "details.acceptanceState": "Acceptance state",
  "details.notSpecified": "Not specified",
  "details.created": "Created",
  "details.updated": "Last updated",
  "details.criteria": "Acceptance criteria",
  "details.contract": "Execution contract",
  "details.allowed": "May change",
  "details.forbidden": "Must not change",
  "details.result": "Expected result",
  "details.stopConditions": "Stop conditions",
  "details.ready": "Ready to start",
  "details.commands": "Required checks",
  "dependencies.search": "Search dependencies",
  "dependencies.add": "Add relation",
  "dependencies.cliOnly": "Relations are changed through e2d tasks dependency",
  "dependencies.task": "Task",
  "dependencies.relation": "Relation",
  "dependencies.status": "Status",
  "dependencies.priority": "Priority",
  "dependencies.all": "All",
  "dependencies.blocking": "Blocks",
  "dependencies.blocked": "Blocked",
  "dependencies.related": "Related",
  "dependencies.missingSnapshot": "Task is missing from the snapshot",
  "dependencies.none": "No dependencies found.",
  "dependencies.blocks": "Blocks {0}",
  "dependencies.blockedBy": "Blocked by {0}",
  "dependencies.parent": "Parent task",
  "dependencies.missing": "Missing",
  "dependencies.select": "Select a dependency.",
  "dependencies.eyebrow": "Dependency",
  "dependencies.component": "Component",
  "dependencies.currentRelation": "Relation to current task",
  "dependencies.blockingNote": "The current task cannot start until {0} is completed.",
  "dependencies.relatedNote": "The relation belongs to {0}.",
  "dependencies.description": "Description",
  "dependencies.descriptionAfterOpen": "Description is available after opening the related task.",
  "dependencies.openTask": "Open task",
  "activity.allEvents": "All events",
  "activity.search": "Search activity…",
  "activity.system": "System",
  "activity.none": "No events found.",
  "activity.filter": "Event filter",
  "activity.taskPatched": "Task updated: {0}",
  "activity.taskPatchedEmpty": "Task updated",
  "activity.statusChanged": "Status changed: {0} → {1}. Reason: {2}",
  "overview.planEmpty": "Work plan is not specified.",
  "overview.contextEmpty": "Additional context is not specified.",
  "files.remove": "Remove",
  "files.none": "Linked files are not specified.",
  "files.openLabel": "Open file {0}",
  "files.open": "Open {0}",
  "files.previewLabel": "Preview image {0} in Task Board",
  "files.previewTitle": "Image preview — {0}",
  "files.closePreview": "Close image preview",
  "files.directoriesNone": "Directories are not specified.",
  "files.commandsNone": "Commands are not specified.",
  "files.section": "Files",
  "files.attachmentsNone": "No attached files.",
  "files.useAsCover": "Use as card cover",
  "files.coverSelected": "Card cover",
  "files.automaticCover": "Choose cover automatically",
  "criteria.none": "No criteria added.",
  "readiness.none": "Readiness conditions are not specified.",
  "common.notSpecified": "Not specified.",
  "common.notSpecifiedValue": "Not specified",
  "task.loadFailed": "Failed to load task details. {0}",
  "task.retry": "Retry",
  "task.formTitle": "Task title",
  "task.formDescription": "Description (Markdown)",
  "task.formPriority": "Priority",
  "dependencies.missingShort": "missing",
  "common.none": "None",
  "extension.trustedRequired": "Electron2D Task Board requires a trusted workspace.",
  "extension.workspaceClosed": "The workspace for {0} is no longer open.",
  "extension.taskListTrusted": "Task list requires a trusted workspace.",
  "extension.noBoard": "No task board is available.",
  "extension.noActiveTasks": "No active tasks.",
  "extension.taskListUnavailable": "Task list unavailable: {0}",
  "extension.openTask": "Open Task",
  "extension.noTaskboard": "No .taskboard/board.e2tasks was found in the open workspace.",
  "extension.selectWorkspace": "Select the workspace folder whose task board should open",
  "extension.panelTitle": "Task Board",
  "extension.panelNotOpen": "Task board panel is not open.",
  "extension.invalidMessage": "The task board ignored an invalid webview message.",
  "extension.attachTitle": "Attach a file to {0}",
  "extension.acceptTask": "Accept task",
  "extension.requestChanges": "Request changes",
  "extension.confirmDecision": "{0} {1}?",
  "errors.moveNotApplicable": "The move is no longer applicable after refreshing the task board.",
  "errors.taskRevisionConflictRefreshed": "{0} The task was refreshed. The action was not performed; repeat it on the current data.",
  "errors.unsafePath": "The path is not a safe path inside the project.",
  "errors.outsideProject": "The file is outside the project.",
  "errors.notFile": "The path does not refer to a regular file.",
  "errors.openFile": "Failed to open linked file “{0}”: {1}",
  "status.ready.label": "Ready",
  "status.ready.description": "Default status for a new or reopened task. The card stays here when dependencies are complete and there are no manual blockers.",
  "status.inProgress.label": "In progress",
  "status.inProgress.description": "Work is being performed. Normal start is allowed from Ready or Blocked only after dependencies are complete; request changes and reopen can also return a task here.",
  "status.blocked.label": "Blocked",
  "status.blocked.description": "Work is explicitly stopped, or a Ready task has incomplete or cancelled dependencies or a manual blocker. It returns to Ready after the causes are removed.",
  "status.review.label": "Review",
  "status.review.description": "Work is complete. Open means internal review; Submitted means waiting for the user's decision in the same column.",
  "status.done.label": "Done",
  "status.done.description": "A trusted human accepted the task from Review with acceptanceState Submitted. A regular agent or noninteractive CLI cannot assign this status.",
  "status.cancelled.label": "Cancelled",
  "status.cancelled.description": "Work was explicitly cancelled from Ready, In progress or Blocked; reopen returns it to canonical Ready by default.",
  "model.noDescription": "No description added.",
  "markdown.listItem": "list item",
  "markdown.linkText": "text",
  "markdown.mentionName": "name",
  "markdown.text": "text",
  "markdown.code": "code",
  "markdown.image": "Image"
} as const;

export type LocalizationKey = keyof typeof english;
export type SupportedLocale = "en" | "ru";

const russian: Readonly<Record<LocalizationKey, string>> = {
  "board.title": "Доска задач Electron2D",
  "board.search": "Поиск задач",
  "board.searchPlaceholder": "Поиск задач…",
  "board.filters": "Фильтры",
  "board.resetFilters": "Сбросить фильтры",
  "board.priority": "Приоритет",
  "board.allPriorities": "Все приоритеты",
  "board.tags": "Теги",
  "board.allTags": "Все теги",
  "board.selectedTags": "Выбрано тегов: {0}",
  "board.archive": "Архив",
  "board.refresh": "Обновить доску",
  "board.tagSettings": "Управление тегами доски",
  "board.createTask": "Создать задачу",
  "board.ariaLabel": "Доска задач",
  "board.showAllColumn": "Показать все задачи колонки «{0}»",
  "board.showAll": "Показать все задачи",
  "board.collapseColumn": "Свернуть колонку «{0}»",
  "board.collapse": "Свернуть колонку",
  "board.expandColumn": "Развернуть колонку «{0}»",
  "board.expand": "Развернуть колонку",
  "board.moreTasks": "+ {0} ещё",
  "indicator.blockers": "Причины блокировки",
  "indicator.dependencies": "Зависимости",
  "indicator.labels": "Метки",
  "indicator.deadline": "Срок выполнения",
  "indicator.checklist": "Критерии приёмки",
  "indicator.attachments": "Прикреплённые файлы",
  "indicator.awaitingDecision": "Ожидает решения пользователя",
  "indicator.done": "Завершено",
  "task.loading": "Загрузка подробностей задачи…",
  "task.sections": "Разделы задачи",
  "task.tab.overview": "Обзор",
  "task.tab.details": "Детали",
  "task.tab.dependencies": "Зависимости",
  "task.tab.activity": "Активность",
  "task.edit": "Редактировать",
  "task.attach": "Прикрепить файл",
  "task.addTag": "Добавить тег",
  "task.archive": "В архив",
  "task.reopen": "Вернуть в работу",
  "task.reopenReason": "Задача возвращена в работу пользователем в VS Code Task Board.",
  "task.submit": "Передать на приёмку",
  "task.submitPrompt": "Комментарий к передаче",
  "task.accept": "Принять",
  "task.acceptPrompt": "Причина приёмки",
  "task.acceptReason": "Задача принята пользователем в VS Code Task Board.",
  "task.acceptUnavailable": "Для приёмки нужно сначала закрыть все критерии.",
  "task.requestChanges": "Вернуть в работу",
  "task.requestChangesPrompt": "Что нужно изменить",
  "task.unarchive": "Вернуть из архива",
  "task.close": "Закрыть",
  "task.editLabel": "Редактировать задачу",
  "task.waitForLoading": "Дождитесь загрузки задачи",
  "task.back": "Назад к предыдущей задаче",
  "task.closeDetails": "Закрыть подробности задачи",
  "task.createDialogTitle": "Создание задачи",
  "task.create": "Создать",
  "task.creating": "Создание…",
  "task.cancelCreate": "Отмена",
  "task.closeCreate": "Закрыть создание задачи",
  "task.titleRequired": "Обязательное поле",
  "task.formDeadlineOptional": "Срок (необязательно)",
  "task.deadlineInvalid": "Укажите существующую дату в формате ГГГГ-ММ-ДД.",
  "task.createFailed": "Не удалось создать задачу. Проверьте значения и повторите попытку.",
  "task.copyNumber": "Копировать номер задачи",
  "task.numberCopied": "Номер задачи скопирован",
  "task.breadcrumb": "ЗАДАЧИ",
  "task.formDeadline": "Срок (ГГГГ-ММ-ДД, оставьте пустым, чтобы убрать)",
  "tags.create": "Создать тег",
  "tags.edit": "Изменить тег",
  "tags.delete": "Удалить тег",
  "tags.selectForTask": "Выберите тег или создайте общий",
  "tags.selectAction": "Выберите действие для тега «{0}»",
  "tags.namePrompt": "Название тега",
  "tags.colorPrompt": "Цвет тега (legacy-имя или #RRGGBB)",
  "tags.colorInvalid": "Используйте Gray, Blue, Green, Yellow, Orange, Red, Purple или точное значение #RRGGBB.",
  "tags.noneAvailable": "Все доступные теги уже назначены",
  "overview.goal": "Цель",
  "overview.steps": "Что нужно сделать",
  "overview.context": "Контекст",
  "overview.contextIntro": "Тип задачи: `{0}`. Готовность: `{1}`.",
  "overview.notSpecifiedLower": "не указан",
  "overview.stopCondition": "Стоп-условие: {0}",
  "overview.summary": "Сводка",
  "overview.linkedFiles": "Связанные файлы",
  "overview.attachments": "Прикреплённые файлы",
  "overview.directories": "Каталоги/области проекта",
  "chat.title": "Чат с агентом",
  "chat.agent": "Agent",
  "chat.user": "Вы",
  "chat.empty": "Сообщений пока нет. Спросите агента об этой задаче.",
  "chat.placeholder": "Сообщение агенту об этой задаче…",
  "chat.send": "Отправить",
  "chat.cancel": "Отменить",
  "chat.permissionOnce": "Разрешить один раз",
  "chat.permissionSession": "Разрешить для сессии",
  "chat.permissionReject": "Отклонить",
  "chat.connecting": "Подключение к агенту…",
  "chat.alreadyRunning": "Для этой задачи уже выполняется запрос к агенту.",
  "chat.staleTask": "Задача изменилась. Обновите её перед отправкой сообщения.",
  "chat.contextChanged": "Контекст задачи изменился во время работы агента. Ответ не сохранён; проверьте новую ревизию и отправьте сообщение снова.",
  "chat.cancelled": "Работа агента отменена.",
  "chat.noActiveRun": "Для этой задачи нет активного запуска агента.",
  "details.status": "Статус",
  "details.taskNumber": "Номер задачи",
  "details.priority": "Приоритет",
  "details.tags": "Теги",
  "details.relatedTasks": "Связанные задачи",
  "details.readiness": "Готовность",
  "details.taskType": "Тип задачи",
  "details.acceptanceState": "Состояние приёмки",
  "details.notSpecified": "Не указано",
  "details.created": "Создано",
  "details.updated": "Последнее обновление",
  "details.criteria": "Критерии приёмки",
  "details.contract": "Контракт выполнения",
  "details.allowed": "Можно менять",
  "details.forbidden": "Нельзя менять",
  "details.result": "Ожидаемый результат",
  "details.stopConditions": "Стоп-условия",
  "details.ready": "Готово к началу",
  "details.commands": "Обязательные проверки",
  "dependencies.search": "Поиск по зависимостям",
  "dependencies.add": "Добавить связь",
  "dependencies.cliOnly": "Связи изменяются через e2d tasks dependency",
  "dependencies.task": "Задача",
  "dependencies.relation": "Связь",
  "dependencies.status": "Статус",
  "dependencies.priority": "Приоритет",
  "dependencies.all": "Все",
  "dependencies.blocking": "Блокирует",
  "dependencies.blocked": "Заблокировано",
  "dependencies.related": "Связанные",
  "dependencies.missingSnapshot": "Задача отсутствует в снимке",
  "dependencies.none": "Зависимости не найдены.",
  "dependencies.blocks": "Блокирует {0}",
  "dependencies.blockedBy": "Заблокирована {0}",
  "dependencies.parent": "Родительская задача",
  "dependencies.missing": "Отсутствует",
  "dependencies.select": "Выберите зависимость.",
  "dependencies.eyebrow": "Зависимость",
  "dependencies.component": "Компонент",
  "dependencies.currentRelation": "Связь с текущей задачей",
  "dependencies.blockingNote": "Текущая задача не может быть начата до завершения {0}.",
  "dependencies.relatedNote": "Связь относится к {0}.",
  "dependencies.description": "Описание",
  "dependencies.descriptionAfterOpen": "Описание доступно после открытия связанной задачи.",
  "dependencies.openTask": "Открыть задачу",
  "activity.allEvents": "Все события",
  "activity.search": "Поиск по активности…",
  "activity.system": "Системные",
  "activity.none": "События не найдены.",
  "activity.filter": "Фильтр событий",
  "activity.taskPatched": "Задача обновлена: {0}",
  "activity.taskPatchedEmpty": "Задача обновлена",
  "activity.statusChanged": "Статус изменён: {0} → {1}. Причина: {2}",
  "overview.planEmpty": "План работ не указан.",
  "overview.contextEmpty": "Дополнительный контекст не указан.",
  "files.remove": "Удалить",
  "files.none": "Связанные файлы не указаны.",
  "files.openLabel": "Открыть файл {0}",
  "files.open": "Открыть {0}",
  "files.previewLabel": "Открыть изображение {0} в Task Board",
  "files.previewTitle": "Просмотр изображения — {0}",
  "files.closePreview": "Закрыть просмотр изображения",
  "files.directoriesNone": "Каталоги не указаны.",
  "files.commandsNone": "Команды не заданы.",
  "files.section": "Файлы",
  "files.attachmentsNone": "Прикреплённых файлов нет.",
  "files.useAsCover": "Использовать как обложку",
  "files.coverSelected": "Обложка карточки",
  "files.automaticCover": "Выбирать обложку автоматически",
  "criteria.none": "Критерии не добавлены.",
  "readiness.none": "Условия готовности не заданы.",
  "common.notSpecified": "Не задано.",
  "common.notSpecifiedValue": "Не указана",
  "task.loadFailed": "Не удалось загрузить подробности задачи. {0}",
  "task.retry": "Повторить",
  "task.formTitle": "Название задачи",
  "task.formDescription": "Описание (Markdown)",
  "task.formPriority": "Приоритет",
  "dependencies.missingShort": "отсутствует",
  "common.none": "Нет",
  "extension.trustedRequired": "Для Electron2D Task Board требуется доверенная рабочая область.",
  "extension.workspaceClosed": "Рабочая область для {0} больше не открыта.",
  "extension.taskListTrusted": "Для списка задач требуется доверенная рабочая область.",
  "extension.noBoard": "Доска задач недоступна.",
  "extension.noActiveTasks": "Активных задач нет.",
  "extension.taskListUnavailable": "Список задач недоступен: {0}",
  "extension.openTask": "Открыть задачу",
  "extension.noTaskboard": "В открытой рабочей области не найден .taskboard/board.e2tasks.",
  "extension.selectWorkspace": "Выберите папку рабочей области, доску которой нужно открыть",
  "extension.panelTitle": "Доска задач",
  "extension.panelNotOpen": "Панель доски задач не открыта.",
  "extension.invalidMessage": "Доска задач проигнорировала некорректное сообщение webview.",
  "extension.attachTitle": "Прикрепить файл к {0}",
  "extension.acceptTask": "Принять задачу",
  "extension.requestChanges": "Запросить изменения",
  "extension.confirmDecision": "{0} {1}?",
  "errors.moveNotApplicable": "Перемещение больше неприменимо после обновления доски задач.",
  "errors.taskRevisionConflictRefreshed": "{0} Задача обновлена. Действие не выполнено; повторите его на актуальных данных.",
  "errors.unsafePath": "Путь не является безопасным путём внутри проекта.",
  "errors.outsideProject": "Файл находится за пределами проекта.",
  "errors.notFile": "Указанный путь не является обычным файлом.",
  "errors.openFile": "Не удалось открыть связанный файл «{0}»: {1}",
  "status.ready.label": "Готово к работе",
  "status.ready.description": "Статус новой или повторно открытой задачи по умолчанию. Карточка находится здесь, когда зависимости завершены и ручные блокировки отсутствуют.",
  "status.inProgress.label": "В работе",
  "status.inProgress.description": "Работа выполняется. Обычный старт разрешён из готовности или блокировки только при завершённых зависимостях; запрос изменений и повторное открытие также возвращают задачу сюда.",
  "status.blocked.label": "Заблокировано",
  "status.blocked.description": "Работа явно остановлена либо готовая задача имеет незавершённые или отменённые зависимости либо ручную блокировку. После снятия причин она возвращается в готовность.",
  "status.review.label": "На проверке",
  "status.review.description": "Рабочая фаза завершена. Open означает внутреннюю проверку, Submitted — ожидание решения пользователя в той же колонке.",
  "status.done.label": "Завершено",
  "status.done.description": "Задача принята доверенным человеком из Review с acceptanceState Submitted. Обычный агент или неинтерактивный CLI не может назначить этот статус.",
  "status.cancelled.label": "Отменено",
  "status.cancelled.description": "Работа явно отменена из готовности, выполнения или блокировки; повторное открытие по умолчанию возвращает канонический статус Ready.",
  "model.noDescription": "Описание не добавлено.",
  "markdown.listItem": "элемент списка",
  "markdown.linkText": "текст",
  "markdown.mentionName": "имя",
  "markdown.text": "текст",
  "markdown.code": "код",
  "markdown.image": "Изображение"
};

export const localizationResources: Readonly<Record<SupportedLocale, Readonly<Record<LocalizationKey, string>>>> = {
  en: english,
  ru: russian
};

export interface Localizer {
  readonly locale: SupportedLocale;
  t(key: LocalizationKey, ...values: readonly unknown[]): string;
}

export function resolveLocale(language: string | undefined): SupportedLocale {
  return /^ru(?:-|$)/i.test(language?.trim() ?? "") ? "ru" : "en";
}

export function createLocalizer(language: string | undefined): Localizer {
  const locale = resolveLocale(language);
  const resources = localizationResources[locale];
  return {
    locale,
    t: (key, ...values) => resources[key].replace(/\{(\d+)\}/g, (_match, index: string) =>
      String(values[Number(index)] ?? ""))
  };
}
