<Project>
  <PropertyGroup>
    <Electron2DVersion>0.1.0-alpha.1</Electron2DVersion>
    <Electron2DNativePackageVersion>$(Electron2DVersion)</Electron2DNativePackageVersion>
    <Electron2DSDLVersion>3.4.18</Electron2DSDLVersion>
    <Electron2DNativePython Condition="'$(Electron2DNativePython)' == '' and $([MSBuild]::IsOSPlatform('Windows'))">python</Electron2DNativePython>
    <Electron2DNativePython Condition="'$(Electron2DNativePython)' == ''">python3</Electron2DNativePython>
    <Electron2DBuildNativeFromSource Condition="'$(Electron2DBuildNativeFromSource)' == ''">false</Electron2DBuildNativeFromSource>
    <_Electron2DPrivateNativeRID Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</_Electron2DPrivateNativeRID>
    <_Electron2DPrivateNativeRID Condition="'$(_Electron2DPrivateNativeRID)' == ''">$(NETCoreSdkRuntimeIdentifier)</_Electron2DPrivateNativeRID>
  </PropertyGroup>
</Project>
