<Project>
  <PropertyGroup>
    <_Electron2DTLSBuild>$(MSBuildThisFileDirectory)../obj/tls-native/$(_Electron2DPrivateNativeRID)</_Electron2DTLSBuild>
  </PropertyGroup>
  <ItemGroup Condition="'$(Electron2DBuildNativeFromSource)' == 'true' and '$(Electron2DNativePlatform)' == 'MacOS'">
    <_Electron2DTLSNative Include="$(_Electron2DTLSBuild)/libElectron2DCrypto.3.dylib;$(_Electron2DTLSBuild)/libElectron2DSSL.3.dylib" />
    <None Include="@(_Electron2DTLSNative)" Link="runtimes/$(_Electron2DPrivateNativeRID)/native/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Pack="false" Visible="false" />
  </ItemGroup>
  <Target Name="BuildElectron2DTLSNative" BeforeTargets="PrepareForBuild;GetCopyToOutputDirectoryItems;ComputeFilesToPublish" Condition="'$(Electron2DBuildNativeFromSource)' == 'true' and '$(Electron2DNativePlatform)' == 'MacOS'" Inputs="$(MSBuildThisFileDirectory)native/build_tls.py;$(MSBuildThisFileDirectory)native-package.props" Outputs="@(_Electron2DTLSNative)">
    <Exec Command="python3 -B &quot;$(MSBuildThisFileDirectory)native/build_tls.py&quot; $(_Electron2DPrivateNativeRID) &quot;$(_Electron2DTLSBuild)&quot;" />
  </Target>
</Project>
