#!/usr/bin/env python3
"""Regenerate the pinned Unicode uppercase tables; --check verifies recorded output hashes offline."""
import argparse
import hashlib
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "tools/text-case.json"
UCD = "https://raw.githubusercontent.com/unicode-org/unicodetools/0509b4b256ff75c65300c8aaecb9e6ec816d9520/unicodetools/data/ucd/17.0.0/"
ICU = "https://raw.githubusercontent.com/unicode-org/icu/21d1eb0f306e1141c10931e914dfc038c06121da/icu4c/source/common/"
INPUTS = {
    "ucase.cpp": (ICU + "ucase.cpp", "a94ccf6f96d2f3eb7bd3008529a38d0d032abaab0fd4f5ef038d7460742f3045"),
    "ucasemap_imp.h": (ICU + "ucasemap_imp.h", "d1acc77c08324bd726c1a4e49f52f6a969910f0d77dd7d97bfddb72e0e841764"),
    "ICU-LICENSE": ("https://raw.githubusercontent.com/unicode-org/icu/21d1eb0f306e1141c10931e914dfc038c06121da/LICENSE", "e55522d81edc687a341a4411e0776e54ca654e90147f354a90458aaced4116af"),
    "UnicodeData.txt": (UCD + "UnicodeData.txt", "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"),
    "SpecialCasing.txt": (UCD + "SpecialCasing.txt", "efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588"),
    "PropList.txt": (UCD + "PropList.txt", "130dcddcaadaf071008bdfce1e7743e04fdfbc910886f017d9f9ac931d8c64dd"),
    "DerivedCoreProperties.txt": (UCD + "DerivedCoreProperties.txt", "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08"),
    "ustrcase.cpp": (ICU + "ustrcase.cpp", "e5d6cae3829094a2bfb2e7a8ee294e97a369bc3f7397262eff0f99299cfb4d9c"),
}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def ranges(values):
    result = []
    for value in sorted(values):
        if result and result[-1] + 1 == value:
            result[-1] = value
        else:
            result.extend((value, value))
    return result


def prop(text, name):
    values = set()
    for raw in text.splitlines():
        line = raw.split("#")[0].strip()
        if not line:
            continue
        fields = [part.strip() for part in line.split(";")]
        if fields[1] != name:
            continue
        limits = fields[0].split("..")
        first, last = int(limits[0], 16), int(limits[-1], 16)
        values.update(range(first, last + 1))
    return values


def span(name, values):
    result = f"    private static ReadOnlySpan<uint> {name} =>\n    [\n"
    for i in range(0, len(values), 12):
        result += "        " + ", ".join(f"0x{value:X}" for value in values[i:i+12]) + ",\n"
    return result + "    ];\n\n"


def generate(text):
    simple, nonzero, above = {}, set(), set()
    for line in text["UnicodeData.txt"].splitlines():
        fields = line.split(";")
        cp = int(fields[0], 16)
        if fields[12]:
            simple[cp] = int(fields[12], 16)
        ccc = int(fields[3])
        if ccc:
            nonzero.add(cp)
        if ccc == 230:
            above.add(cp)
    expansions = {}
    for raw in text["SpecialCasing.txt"].splitlines():
        line = raw.split("#")[0].strip()
        if not line:
            continue
        fields = [part.strip() for part in line.split(";")]
        if fields[4]:
            continue
        cp = int(fields[0], 16)
        upper = [int(value, 16) for value in fields[3].split()]
        if len(upper) == 1:
            if upper[0] != cp:
                simple[cp] = upper[0]
        else:
            expansions[cp] = upper
    out = "// Generated by tools/update-text-case.py from pinned Unicode 17 and ICU 78.3 data.\n// Unicode License V3: licence/TextCase-LICENSE.txt.\nnamespace Electron2D;\n\ninternal static partial class TextCase\n{\n"
    pairs = [value for pair in sorted(simple.items()) for value in pair]
    out += span("UpperPairs", pairs)
    out += span("NonzeroCombiningRanges", ranges(nonzero))
    out += span("AboveCombiningRanges", ranges(above))
    out += span("SoftDottedRanges", ranges(prop(text["PropList.txt"], "Soft_Dotted")))
    out += span("CasedRanges", ranges(prop(text["DerivedCoreProperties.txt"], "Cased")))
    out += span("CaseIgnorableRanges", ranges(prop(text["DerivedCoreProperties.txt"], "Case_Ignorable")))
    bits = {"HAS_VOWEL": 0x1000, "HAS_YPOGEGRAMMENI": 0x2000, "HAS_ACCENT": 0x4000, "HAS_DIALYTIKA": 0x8000}
    for source, name, count in [("data0370", "Greek0370", 144), ("data1F00", "Greek1F00", 256)]:
        body = re.search(r"static const uint16_t " + source + r"\[\] = \{(.*?)\};", text["ustrcase.cpp"], re.S)[1]
        body = re.sub(r"//[^\n]*", "", body)
        values = []
        for expression in body.split(","):
            if expression.strip():
                value = 0
                for token in expression.split("|"):
                    token = token.strip()
                    value |= bits[token] if token in bits else int(token, 0)
                values.append(value)
        assert len(values) == count
        out += span(name, values)
    out += "    private static string? Expansion(uint scalar) => scalar switch\n    {\n"
    for cp, values in sorted(expansions.items()):
        encoded = "".join(f"\\u{x:04X}" if x <= 0xFFFF else f"\\U{x:08X}" for x in values)
        out += f'        0x{cp:X} => "{encoded}",\n'
    out += "        _ => null\n    };\n}\n"
    return out.encode(), {"simpleUppercaseMappings": len(simple), "fullUppercaseExpansions": len(expansions), "greekEntries": 400}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source-dir", type=Path)
    args = parser.parse_args()
    if args.check:
        data = json.loads(MANIFEST.read_text())
        for name, sha in data["outputs"].items():
            if digest((ROOT / name).read_bytes()) != sha:
                raise SystemExit("Generated uppercase data differs: " + name)
        print("Unicode uppercase generated hashes verified")
        return
    text = {}
    for name, (url, sha) in INPUTS.items():
        content = (args.source_dir / name).read_bytes() if args.source_dir else urllib.request.urlopen(url, timeout=30).read()
        if digest(content) != sha:
            raise SystemExit("Pinned uppercase input hash mismatch: " + name)
        text[name] = content.decode("utf-8")
    output, counts = generate(text)
    name = "src/Servers/Text/TextCase.Data.cs"
    (ROOT / name).write_bytes(output)
    license_text = text["ICU-LICENSE"].split("Chinese/Japanese Word Break Dictionary Data")[0].rstrip()
    license_text = license_text.rsplit("----------------------------------------------------------------------", 1)[0].rstrip() + "\n"
    license_name = "licence/TextCase-LICENSE.txt"
    (ROOT / license_name).write_text(license_text)
    data = {"unicodeVersion": "17.0.0", "icuRelease": "78.3", "icuCommit": "21d1eb0f306e1141c10931e914dfc038c06121da", "license": "licence/TextCase-LICENSE.txt", "inputs": [{"name": n, "url": u, "sha256": h} for n, (u, h) in INPUTS.items()], "outputs": {name: digest(output), license_name: digest(license_text.encode())}, "counts": counts, "conformance": {"oracle": "ICU 78.3, explicit-length UTF-16", "scalarLocaleProfiles": 6672384, "contextProfiles": 332080, "portableGoldenCases": 348, "testSource": "tests/Electron2D.Tests/TextCaseTests.cs"}}
    MANIFEST.write_text(json.dumps(data, indent=2) + "\n")
    print(json.dumps(counts))


if __name__ == "__main__":
    main()
