using Electron2D;

internal static class AnimationStateMachineTests
{
    private static readonly PropertyDescriptor<Probe, double> X = new("X", n => n.X, (n, v) => { n.X = v; n.Hook?.Invoke(); });
    internal static void Run() { Authoring(); Fades(); Routes(); Timing(); Boundaries(); Groups(); SharingAndFailure(); Effects(); TestingAndWarm(); Console.WriteLine("Animation state-machine checks passed."); }
    private static void Authoring()
    {
        using var machine = new AnimationNodeStateMachine(); using var leaf = new AnimationNodeAnimation(); using var edge = new AnimationNodeStateMachineTransition();
        Check(machine.GetNodeList().SequenceEqual(new[] { "End", "Start" }) && machine.StateMachineType == AnimationStateMachineType.Root && !machine.ResetEnds && !machine.AllowTransitionToSelf, "Machine defaults.");
        Check(edge.AdvanceMode == AnimationAdvanceMode.Enabled && edge.SwitchMode == AnimationSwitchMode.Immediate && edge.Reset && edge.Priority == 1 && edge.XFadeTime == 0, "Edge defaults.");
        Reject<ArgumentException>(() => machine.AddNode("bad/name", leaf)); Reject<ArgumentException>(() => machine.AddNode("loop", machine)); using var ordinary = new AnimationNode(); Reject<ArgumentException>(() => machine.AddNode("ordinary", ordinary));
        machine.AddNode("a", leaf, new(1, 2)); machine.AddNode("b", leaf); machine.SetGraphOffset(new(3, 4)); machine.AddTransition("Start", "a", edge); machine.AddTransition("a", "b", edge);
        Reject<ArgumentException>(() => machine.AddTransition("a", "a", edge)); Reject<ArgumentException>(() => machine.AddTransition("a", "b", edge)); Reject<ArgumentException>(() => machine.RemoveNode("Start")); Reject<ArgumentException>(() => machine.ReplaceNode("End", leaf));
        Reject<ArgumentOutOfRangeException>(() => edge.XFadeTime = -1); Reject<ArgumentOutOfRangeException>(() => edge.XFadeTime = double.NaN); Reject<ArgumentOutOfRangeException>(() => edge.Priority = -1); Reject<ArgumentOutOfRangeException>(() => edge.SwitchMode = (AnimationSwitchMode)99);
        var notices = 0; edge.AdvanceConditionChanged += () => notices++; var key = new AnimationParameter<bool>("ready", false); edge.AdvanceCondition = key; edge.AdvanceCondition = key; Check(notices == 2, "Equal condition assignments notify.");
        machine.RenameNode("a", "renamed"); Check(machine.GetTransitionTo(0) == "renamed" && machine.GetTransitionFrom(1) == "renamed" && machine.GetNodePosition("renamed") == new Vector2(1, 2), "Rename updates edges and metadata.");
        using var copy = (AnimationNodeStateMachine)machine.Duplicate(); using var deep = (AnimationNodeStateMachine)machine.Duplicate(true); Check(ReferenceEquals(copy.GetNode("b"), leaf) && ReferenceEquals(copy.GetTransition(0), edge), "Shallow borrowing."); Check(!ReferenceEquals(deep.GetNode("b"), leaf) && ReferenceEquals(deep.GetNode("b"), deep.GetNode("renamed")) && ReferenceEquals(deep.GetTransition(0), deep.GetTransition(1)), "Deep aliases.");
        var deepLeaf = deep.GetNode("b"); var deepEdge = deep.GetTransition(0); machine.RemoveNode("renamed"); Check(machine.GetTransitionCount() == 0 && !leaf.IsDisposed && !edge.IsDisposed && copy.HasTransition("renamed", "b"), "Independent topology and borrowed lifetime."); deepLeaf.Dispose(); deepEdge.Dispose();
    }
    private static void Fades()
    {
        using var setup = new Setup(); using var edge = new AnimationNodeStateMachineTransition { XFadeTime = 1 }; setup.Machine.AddTransition("a", "b", edge); var events = new List<string>(); setup.Playback.StateStarted += s => events.Add("+" + s); setup.Playback.StateFinished += s => events.Add("-" + s);
        setup.Tree.Advance(0); Near(setup.Target.X, 10); setup.Playback.Travel("b"); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "b" && setup.Playback.GetFadingFromNode() == "a", "Selection changes after source sample."); Near(setup.Target.X, 10);
        setup.Tree.Advance(.5); Near(setup.Target.X, 20); Near(setup.Playback.GetFadingPosition(), .5); Near(setup.Playback.GetFadingLength(), 1); Near(setup.Playback.GetCurrentLength(), 4); Near(setup.Playback.GetFadingFromLength(), 4);
        setup.Tree.Advance(.5); Near(setup.Target.X, 30); Check(setup.Playback.GetFadingFromNode() == "" && events.IndexOf("+b") < events.IndexOf("-a"), "Outgoing finish follows destination start.");
        setup.Playback.Start("a"); setup.Tree.Advance(0); Near(setup.Target.X, 10); using var curve = new Curve(); curve.AddPoint(new(0, 0)); curve.AddPoint(new(.5f, .25f)); curve.AddPoint(new(1, 1)); edge.XFadeCurve = curve; setup.Playback.Travel("b"); setup.Tree.Advance(0); setup.Tree.Advance(.5); Near(setup.Target.X, 15);
        setup.Playback.Next(); setup.Tree.Advance(0); Check(setup.Playback.GetFadingFromNode() == "a", "Next without any selected successor preserves fade."); setup.Playback.Stop(); setup.Tree.Advance(0); Check(!setup.Playback.IsPlaying() && setup.Playback.GetTravelPath().Length == 0 && setup.Playback.GetFadingFromNode() == "", "Stop cleanup.");
        setup.Playback.Start("a", false); setup.Tree.Advance(0); Check(setup.Playback.IsPlaying() && setup.Playback.ResourceLocalToScene, "Restart and local controller.");
        edge.XFadeCurve = null; edge.XFadeTime = 0; setup.Playback.Travel("b"); setup.Tree.Advance(0); setup.Tree.Advance(0); Near(setup.Target.X, 30);
        setup.Machine.AddTransition("b", "End", edge); setup.Playback.Travel("End"); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "End" && setup.Playback.IsPlaying(), "End exits while retaining active control.");
    }
    private static void Routes()
    {
        using var setup = new Setup(); setup.Machine.SetNodePosition("a", new(0, 0)); setup.Machine.SetNodePosition("b", new(1, 0)); setup.Machine.SetNodePosition("c", new(2, 0));
        using var direct = new AnimationNodeStateMachineTransition { Priority = 10, SwitchMode = AnimationSwitchMode.AtEnd }; using var via = new AnimationNodeStateMachineTransition { SwitchMode = AnimationSwitchMode.AtEnd }; setup.Machine.AddTransition("a", "c", direct); setup.Machine.AddTransition("a", "b", via); setup.Machine.AddTransition("b", "c", via); setup.Tree.Advance(0);
        setup.Playback.Travel("c"); setup.Tree.Advance(0); Check(setup.Playback.GetTravelPath().SequenceEqual(new[] { "b", "c" }), "Geometric priority route."); var snapshot = setup.Playback.GetTravelPath(); snapshot[0] = "bad"; Check(setup.Playback.GetTravelPath()[0] == "b", "Route snapshot ownership.");
        setup.Playback.Next(); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "b" && setup.Playback.GetTravelPath().SequenceEqual(new[] { "c" }), "Next bypasses AtEnd once."); setup.Playback.Next(); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "c", "Route continues.");
        setup.Playback.Start("a"); setup.Tree.Advance(0); via.AdvanceMode = AnimationAdvanceMode.Disabled; direct.AdvanceMode = AnimationAdvanceMode.Disabled; setup.Tree.Advance(.75); setup.Playback.Travel("c", false); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "c" && setup.Playback.GetTravelPath().Length == 0, "Disabled routes teleport.");
        setup.Tree.Advance(.5); var prior = setup.Playback.GetCurrentPlayPosition(); setup.Playback.Travel("c"); setup.Tree.Advance(0); Near(setup.Playback.GetCurrentPlayPosition(), prior); setup.Machine.AllowTransitionToSelf = true; setup.Playback.Travel("c"); setup.Tree.Advance(0); Near(setup.Playback.GetCurrentPlayPosition(), 0);
        Reject<ArgumentException>(() => setup.Playback.Start("absent")); Reject<ArgumentException>(() => setup.Playback.Travel("a/c"));
    }
    private static void Timing()
    {
        using var setup = new Setup(); using var edge = new AnimationNodeStateMachineTransition { SwitchMode = AnimationSwitchMode.AtEnd, XFadeTime = 1 }; setup.Machine.AddTransition("a", "b", edge); setup.Tree.Advance(0); setup.Playback.Travel("b"); setup.Tree.Advance(2.9); Check(setup.Playback.GetCurrentNode() == "a", "AtEnd waits."); setup.Tree.Advance(.1); Check(setup.Playback.GetCurrentNode() == "b", "AtEnd uses fade threshold.");
        edge.SwitchMode = AnimationSwitchMode.Sync; edge.XFadeTime = 0; setup.Playback.Start("a"); setup.Tree.Advance(0); setup.Tree.Advance(.75); setup.Playback.Travel("b"); setup.Tree.Advance(0); Near(setup.Playback.GetCurrentPlayPosition(), .75); setup.Tree.Advance(.25); Near(setup.Playback.GetCurrentPlayPosition(), 1);
        var flag = new AnimationParameter<bool>("ready", false); edge.AdvanceMode = AnimationAdvanceMode.Auto; edge.AdvanceCondition = flag; edge.AdvanceExpression = t => t.GetParameter("", flag); setup.Playback.Start("a"); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "a", "False flag suppresses automatic edge."); setup.Tree.SetParameter("", flag, true); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "b", "Typed condition and predicate execute.");
        edge.AdvanceCondition = null; edge.AdvanceExpression = null; edge.SwitchMode = AnimationSwitchMode.AtEnd; setup.Clips[0].LoopMode = SpriteFrames.LoopMode.Linear; setup.Playback.Start("a"); setup.Tree.Advance(0); setup.Tree.Advance(3.9); Check(setup.Playback.GetCurrentNode() == "a", "Loops wait without BreakLoopAtEnd."); edge.BreakLoopAtEnd = true; setup.Tree.Advance(.05); Check(setup.Playback.GetCurrentNode() == "b", "Loop break uses predicted cycle endpoint.");
        using var back = new AnimationNodeStateMachineTransition { AdvanceMode = AnimationAdvanceMode.Auto }; edge.SwitchMode = AnimationSwitchMode.Immediate; setup.Machine.AddTransition("b", "a", back); setup.Playback.Start("a"); setup.Tree.Advance(0); Check(setup.Playback.IsPlaying(), "Zero-duration automatic cycles terminate within a pass.");
    }
    private static void Boundaries()
    {
        using var setup = new Setup(); setup.Machine.GetTransition(0).XFadeTime = 1; setup.Machine.ResetEnds = true; setup.Tree.Advance(0); setup.Tree.Advance(.5); Near(setup.Target.X, 5); setup.Tree.Advance(.5); Near(setup.Target.X, 10); using var exit = new AnimationNodeStateMachineTransition { XFadeTime = 1 }; setup.Machine.AddTransition("a", "End", exit); setup.Playback.Travel("End"); setup.Tree.Advance(0); setup.Tree.Advance(.5); Near(setup.Target.X, 5); setup.Tree.Advance(.5); Near(setup.Target.X, .0001); setup.Tree.Advance(0); Near(setup.Target.X, 0);
        setup.Machine.ResetEnds = false; setup.Playback.Start("a"); setup.Tree.Advance(0); setup.Playback.Travel("End"); setup.Tree.Advance(0); setup.Tree.Advance(.5); Near(setup.Target.X, 10);
        using var earlier = new AnimationNodeStateMachineTransition { AdvanceMode = AnimationAdvanceMode.Auto, Priority = 3 }; using var later = new AnimationNodeStateMachineTransition { AdvanceMode = AnimationAdvanceMode.Auto, Priority = 2 }; setup.Machine.AddTransition("a", "b", earlier); setup.Machine.AddTransition("a", "c", later); setup.Playback.Start("a"); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "c", "Lowest automatic priority wins.");
    }
    private static void Groups()
    {
        using var setup = new Setup(); using var group = new AnimationNodeStateMachine { StateMachineType = AnimationStateMachineType.Grouped }; using var enter = new AnimationNodeStateMachineTransition { AdvanceMode = AnimationAdvanceMode.Auto }; using var inner = new AnimationNodeStateMachineTransition(); using var exit = new AnimationNodeStateMachineTransition { SwitchMode = AnimationSwitchMode.AtEnd }; group.AddNode("one", setup.Leaves[0]); group.AddNode("two", setup.Leaves[1]); group.AddTransition("Start", "one", inner); group.AddTransition("one", "two", inner); group.AddTransition("two", "End", exit); setup.Machine.AddNode("group", group); setup.Machine.AddTransition("a", "group", enter); setup.Machine.AddTransition("group", "c", exit);
        var names = new List<string>(); setup.Playback.StateStarted += names.Add; setup.Playback.Start("group/one"); setup.Tree.Advance(0); var child = setup.Tree.GetParameter("group", AnimationNodeStateMachine.Playback); Check(child.GetCurrentNode() == "one" && names.Contains("group/one"), "Grouped descendant control and ancestor signals."); Reject<InvalidOperationException>(() => child.Start("two")); Reject<ArgumentException>(() => setup.Playback.Start("group/End"));
        setup.Playback.Travel("group/two"); setup.Tree.Advance(0); setup.Tree.Advance(0); Check(child.GetCurrentNode() == "two", "Grouped travel."); setup.Playback.Travel("c"); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "group", "Parent waits for group endpoint."); setup.Playback.Next(); setup.Tree.Advance(0); setup.Tree.Advance(0); setup.Playback.Next(); setup.Tree.Advance(0); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "c", "Next propagates through deepest group and exits.");
        using var deepGroup = new AnimationNodeStateMachine { StateMachineType = AnimationStateMachineType.Grouped }; deepGroup.AddNode("leaf", setup.Leaves[0]); deepGroup.AddTransition("Start", "leaf", inner); deepGroup.AddTransition("leaf", "End", exit); group.AddNode("deep", deepGroup); group.AddTransition("one", "deep", inner); group.AddTransition("deep", "End", exit); setup.Playback.Start("group/deep/leaf"); setup.Scene.ProcessFrame(0); var deepest = setup.Tree.GetParameter("group/deep", AnimationNodeStateMachine.Playback); Check(deepest.GetCurrentNode() == "leaf" && names.Contains("group/deep/leaf"), "Multiple grouped ancestors preserve names and control."); setup.Playback.StateStarted -= names.Add;
        for (var i = 0; i < 20; i++) { setup.Playback.Start("group/deep/leaf"); setup.Scene.ProcessFrame(0); }
        var allocated = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 64; i++) { setup.Playback.Start("group/deep/leaf"); setup.Scene.ProcessFrame(0); }
        Check(GC.GetAllocatedBytesForCurrentThread() == allocated, "Prepared grouped descendant commands allocate zero managed bytes.");
        using var blockedGroup = new AnimationNodeStateMachine { StateMachineType = AnimationStateMachineType.Grouped }; blockedGroup.AddNode("leaf", setup.Leaves[0]); blockedGroup.AddTransition("Start", "leaf", inner); setup.Machine.AddNode("blocked", blockedGroup); setup.Machine.AddTransition("blocked", "c", inner); setup.Playback.Start("blocked/leaf"); setup.Tree.Advance(0); setup.Playback.Travel("c"); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "c" && setup.Playback.GetTravelPath().Length == 0, "An unreachable group exit causes teleport instead of a stuck route.");
        using var invalid = new AnimationTree { TreeRoot = group }; Reject<InvalidOperationException>(() => invalid.Advance(0));
        setup.Machine.StateMachineType = AnimationStateMachineType.Nested; setup.Playback.Start("c"); setup.Tree.Advance(0); setup.Tree.Advance(.75); using var outer = new AnimationNodeBlendTree(); using var seeker = new AnimationNodeTimeSeek(); outer.AddNode("machine", setup.Machine); outer.AddNode("seek", seeker); outer.ConnectNode("seek", 0, "machine"); outer.ConnectNode("output", 0, "seek"); setup.Tree.TreeRoot = outer; setup.Tree.Advance(0); var nested = setup.Tree.GetParameter("machine", AnimationNodeStateMachine.Playback); nested.Start("c"); setup.Tree.Advance(0); setup.Tree.Advance(.5); setup.Tree.SetParameter("seek", AnimationNodeTimeSeek.SeekRequest, 0d); setup.Tree.Advance(0); Check(nested.GetCurrentNode() == "c", "Nested seek keeps current state.");
    }
    private static void SharingAndFailure()
    {
        using var setup = new Setup(); using var other = new AnimationTree { TreeRoot = setup.Machine }; var root = new Node(); root.AddChild(new Probe { Name = "target" }); root.AddChild(other); using var scene = new SceneTree(root); other.AddAnimationLibrary("", setup.Library); setup.Tree.Advance(0); other.Advance(0); var second = other.GetParameter("", AnimationNodeStateMachine.Playback); Check(!ReferenceEquals(second, setup.Playback), "Shared definition has independent playback."); setup.Playback.Start("b"); setup.Tree.Advance(0); Check(second.GetCurrentNode() == "a", "Independent selection."); setup.Machine.RenameNode("b", "renamed"); setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "renamed", "Rename preserves selected state identity."); setup.Machine.RemoveNode("renamed"); setup.Tree.Advance(0); Check(!setup.Playback.IsPlaying() && setup.Playback.GetCurrentNode() == "", "Selected removal stops controller.");
        setup.Playback.Start("a"); setup.Tree.Advance(0); Action<string> reenter = name => { if (name == "c") setup.Playback.Start("a"); }; setup.Playback.StateStarted += reenter; setup.Playback.Start("c"); setup.Tree.Advance(0); setup.Playback.StateStarted -= reenter; setup.Tree.Advance(0); Check(setup.Playback.GetCurrentNode() == "a", "Reentrant command survives stale pass.");
        Action<string> fail = _ => throw new InvalidOperationException("state fixture"); setup.Playback.StateStarted += fail; setup.Playback.Start("c"); Reject<InvalidOperationException>(() => setup.Tree.Advance(0)); setup.Playback.StateStarted -= fail; setup.Playback.Start("a"); setup.Tree.Advance(0); Near(setup.Target.X, 10);
        using var edge = new AnimationNodeStateMachineTransition { AdvanceMode = AnimationAdvanceMode.Auto, AdvanceExpression = _ => throw new InvalidOperationException("predicate fixture") }; setup.Machine.AddTransition("a", "c", edge); Reject<InvalidOperationException>(() => setup.Tree.Advance(0)); edge.AdvanceExpression = null; setup.Tree.Advance(0);
        Action<Resource> failChanged = _ => throw new InvalidOperationException("edge observer fixture"); edge.Changed += failChanged; Reject<AggregateException>(() => edge.AdvanceCondition = new AnimationParameter<bool>("ready", true)); edge.Changed -= failChanged; setup.Tree.SetParameter("", edge.AdvanceCondition!, false);
        using var malformed = new AnimationNodeStateMachine(); using var badEdge = new AnimationNodeStateMachineTransition { AdvanceCondition = new AnimationParameter<bool>("playback", false) }; malformed.AddNode("leaf", setup.Leaves[0]); malformed.AddTransition("Start", "leaf", badEdge); setup.Tree.TreeRoot = malformed; Reject<InvalidOperationException>(() => setup.Tree.GetParameter("", AnimationNodeStateMachine.Playback)); badEdge.AdvanceCondition = null; var recovered = setup.Tree.GetParameter("", AnimationNodeStateMachine.Playback); Check(!recovered.IsDisposed, "Failed preparation recovers and releases new owned controllers."); setup.Tree.TreeRoot = setup.Machine; setup.Tree.Advance(0);
        Task.Run(() => Reject<InvalidOperationException>(() => setup.Tree.GetParameter("", AnimationNodeStateMachine.Playback).Next())).GetAwaiter().GetResult(); var currentPlayback = setup.Tree.GetParameter("", AnimationNodeStateMachine.Playback); Task.Run(() => Reject<InvalidOperationException>(currentPlayback.Next)).GetAwaiter().GetResult();
        using var borrowed = new AnimationNodeStateMachinePlayback(); var borrowedKey = new AnimationParameter<AnimationNodeStateMachinePlayback>("borrowed", borrowed); using var custom = new BorrowedControllerNode(borrowedKey); var customTree = new AnimationTree { TreeRoot = custom }; Check(ReferenceEquals(customTree.GetParameter("", borrowedKey), borrowed), "Custom typed controller cells remain borrowed."); customTree.Dispose(); Check(!borrowed.IsDisposed, "Only exact state-machine Playback cells transfer ownership to the tree.");
        var owned = setup.Tree.GetParameter("", AnimationNodeStateMachine.Playback); setup.Tree.TreeRoot = null; setup.Tree.Advance(0); Check(owned.IsDisposed && !setup.Machine.IsDisposed && !setup.Leaves[0].IsDisposed, "Removed graph releases owned controllers only.");
    }
    private static void Effects()
    {
        using var setup = new Setup(); var methods = setup.Clips[0].AddMethodTrack<Probe>(); setup.Clips[0].TrackSetPath(methods, "target"); setup.Clips[0].TrackInsertKey(methods, 0, new AnimationMethodKey<Probe, int>("mark", static (n, value) => n.Calls += value, 1)); var nested = setup.Clips[0].AddAnimationTrack(); setup.Clips[0].TrackSetPath(nested, "child"); setup.Clips[0].AnimationTrackInsertKey(nested, 0, "child"); using var childLibrary = new AnimationLibrary(); childLibrary.AddAnimation("child", setup.Clips[1]); var child = new AnimationPlayer { Name = "child", PlaybackAutoCapture = false }; child.AddAnimationLibrary("", childLibrary); setup.Tree.Parent!.AddChild(child);
        setup.Tree.Advance(0); setup.Scene.ProcessFrame(0); Check(setup.Target.Calls == 1 && child.IsPlaying(), "State startup executes method and nested tracks."); setup.Playback.Stop(); setup.Tree.Advance(0); Check(!child.IsPlaying(), "State stop retires controlled nested playback."); setup.Playback.Start("a"); setup.Tree.Advance(0); Check(child.IsPlaying(), "State restart controls child again."); setup.Playback.Start("b"); setup.Tree.Advance(0); Check(!child.IsPlaying(), "Departed clip retires controlled child.");
    }
    internal static void RunNative()
    {
        using var setup = new Setup(); var data = new byte[8820]; for (var i = 0; i < data.Length / 2; i++) System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian(data.AsSpan(i * 2), (short)(Math.Sin(i * Math.PI * 2 * 440 / 44100) * 8000)); using var wave = new AudioStreamWAV { Data = data, SampleFormat = AudioStreamWAV.Format.PCM16, Loop = AudioLoopMode.Forward, LoopBegin = 0, LoopEnd = 4409 }; var speaker = new AudioStreamPlayer { Name = "speaker" }; setup.Tree.Parent!.AddChild(speaker); var audio = setup.Clips[0].AddAudioTrack(); setup.Clips[0].TrackSetPath(audio, "speaker"); setup.Clips[0].AudioTrackSetUseBlend(audio, false); setup.Clips[0].AudioTrackInsertKey(audio, 0, wave); setup.Tree.Advance(0); var native = AudioServer.Instance.Native; Check(Capture(native).Any(v => Math.Abs(v) > .03), "State audio cue reaches native PCM."); setup.Playback.Stop(); setup.Tree.Advance(0); Check(Capture(native).All(v => Math.Abs(v) < 1e-6), "State stop retires nonblended cues."); setup.Playback.Start("a"); setup.Tree.Advance(0); Check(Capture(native).Any(v => Math.Abs(v) > .03), "State restart retriggers prepared audio."); setup.Playback.Start("b"); setup.Tree.Advance(0); Check(Capture(native).All(v => Math.Abs(v) < 1e-6), "Departed clip retires nonblended cue."); Console.WriteLine("State-machine native audio integration passed.");
    }
    private static float[] Capture(FAudioContext context)
    {
        var start = context.MixPasses; Check(SpinWait.SpinUntil(() => context.MixPasses >= start + 4, 5000), "Native transport warms."); context.PrepareCapture(context.QuantumFrames * context.Channels * 6); start = context.MixPasses; Check(SpinWait.SpinUntil(() => context.MixPasses >= start + 8, 5000), "Native transport captures."); return context.CapturedPCM();
    }
    private static void TestingAndWarm()
    {
        using var setup = new Setup(); using var edge = new AnimationNodeStateMachineTransition { SwitchMode = AnimationSwitchMode.AtEnd }; setup.Machine.AddTransition("a", "b", edge); setup.Machine.AddTransition("b", "a", edge); using var graph = new AnimationNodeBlendTree(); using var gate = new Gate(); graph.AddNode("gate", gate); graph.AddNode("machine", setup.Machine); graph.ConnectNode("gate", 0, "machine"); graph.ConnectNode("output", 0, "gate"); setup.Tree.TreeRoot = graph; var playback = setup.Tree.GetParameter("machine", AnimationNodeStateMachine.Playback); playback.Start("b"); var before = setup.Target.X; setup.Tree.Advance(0); Check(!playback.IsPlaying() && setup.Target.X == before, "Test-only suppresses state and output."); gate.Test = false; setup.Tree.Advance(0); Check(playback.GetCurrentNode() == "b", "Test-only retains pending command."); before = setup.Target.X; var position = playback.GetCurrentPlayPosition(); gate.Test = true; playback.Start("a"); setup.Tree.Advance(.5); Check(setup.Target.X == before && playback.GetCurrentNode() == "b" && playback.GetCurrentPlayPosition() == position, "Test-only preserves an already applied pose and clock."); gate.Test = false; setup.Tree.Advance(0);
        for (var i = 0; i < 20; i++) { playback.Start("a"); setup.Scene.ProcessFrame(0); playback.Travel("b"); setup.Scene.ProcessFrame(0); playback.Next(); setup.Scene.ProcessFrame(.01); }
        var allocated = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 64; i++) { playback.Start("a"); setup.Scene.ProcessFrame(0); playback.Travel("b"); setup.Scene.ProcessFrame(0); playback.Next(); setup.Scene.ProcessFrame(.01); }
        Check(GC.GetAllocatedBytesForCurrentThread() == allocated, "Prepared commands/routes/automatic frame allocate zero managed bytes."); playback.Stop(); setup.Scene.ProcessFrame(0); allocated = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 64; i++) setup.Scene.ProcessFrame(.01); Check(GC.GetAllocatedBytesForCurrentThread() == allocated, "Stopped state-machine idle frames allocate zero managed bytes.");
    }
    internal static void RunHost()
    {
        var backend = Environment.GetEnvironmentVariable("ELECTRON2D_ANIMATION_RENDERER") ?? "gpu"; var settings = ProjectSettings.Instance; var prior = settings.Get(ProjectSettings.RenderingMethod); settings.Set(ProjectSettings.RenderingMethod, backend);
        try
        {
            for (var run = 0; run < 2; run++)
            {
                using var machine = new AnimationNodeStateMachine(); using var first = new AnimationNodeAnimation { Animation = "a" }; using var second = new AnimationNodeAnimation { Animation = "b" }; using var initial = new AnimationNodeStateMachineTransition { AdvanceMode = AnimationAdvanceMode.Auto }; using var fade = new AnimationNodeStateMachineTransition { XFadeTime = 1 }; machine.AddNode("a", first); machine.AddNode("b", second); machine.AddTransition("Start", "a", initial); machine.AddTransition("a", "b", fade);
                using var library = new AnimationLibrary(); using var a = new Animation(); using var b = new Animation(); var descriptor = new PropertyDescriptor<Entity, Vector2>(nameof(Entity.Position), n => n.Position, (n, v) => n.Position = v); foreach (var pair in new[] { (Clip: a, Name: "a", X: 16), (Clip: b, Name: "b", X: 80) }) { var track = pair.Clip.AddTrack(descriptor); pair.Clip.TrackSetPath(track, "box:Position"); pair.Clip.TrackInsertKey(track, 0, new Vector2(pair.X, 16)); library.AddAnimation(pair.Name, pair.Clip); }
                var window = new Window { Size = new(128, 64), Title = "Electron2D state machine" }; var box = new Box { Name = "box" }; var tree = new AnimationTree { TreeRoot = machine, CallbackModeProcess = AnimationMixer.AnimationCallbackModeProcess.Manual }; tree.AddAnimationLibrary("", library); window.AddChild(box); window.AddChild(tree); var stage = 0; int[] expected = [16, 16, 48, 80, 16, 80]; var started = 0;
                box.ReadyAction = () =>
                {
                    var renderer = RenderingServer.Instance!; renderer.SetDefaultClearColor(Colors.Black); var playback = tree.GetParameter("", AnimationNodeStateMachine.Playback); playback.StateStarted += _ => started++; tree.Advance(0);
                    renderer.FramePostDraw += () =>
                    {
                        using var pixels = renderer.Readback(); var x = expected[stage]; Check(pixels.GetPixel(x, 16).R > .9f && pixels.GetPixel(x, 16).G < .1f, "State-machine pose reaches actual pixels."); if (stage > 0 && x != expected[stage - 1]) Check(pixels.GetPixel(expected[stage - 1], 16).R < .1f, "Previous pose clears.");
                        switch (stage++) { case 0: playback.Travel("b"); tree.Advance(0); break; case 1: tree.Advance(.5); break; case 2: tree.Advance(.5); break; case 3: playback.Start("a"); tree.Advance(0); break; case 4: fade.XFadeTime = 0; playback.Travel("b"); tree.Advance(0); tree.Advance(0); break; case 5: playback.Stop(); tree.Advance(0); Check(!playback.IsPlaying(), "Rendered stop executes."); window.Tree!.Quit(); break; }
                    };
                };
                Check(Engine.Instance.Run(window) == 0 && stage == 6 && window.IsDisposed && started >= 4 && !machine.IsDisposed && !library.IsDisposed, "Public host lifecycle borrows authored resources."); Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(new { scenario = "state-machine-host", backend, run, stages = stage, started, cleaned = window.IsDisposed }));
            }
        }
        finally { settings.Set(ProjectSettings.RenderingMethod, prior); }
    }
    private sealed class Box : Entity { internal Action? ReadyAction; protected override void OnReady() => ReadyAction?.Invoke(); protected override void OnDraw() => DrawRect(new(-3, -3, 6, 6), Colors.Red); }
    private sealed class BorrowedControllerNode(AnimationParameter<AnimationNodeStateMachinePlayback> key) : AnimationRootNode
    { protected override IEnumerable<AnimationParameter> OnGetParameterList() => base.OnGetParameterList().Append(key); }
    private sealed class Gate : AnimationNode { internal bool Test = true; internal Gate() => AddInput("in"); protected override double OnProcess(double time, bool seek, bool external, bool testOnly) => BlendInput(0, time, seek, external, 1, testOnly: Test); }
    private sealed class Probe : Node { internal double X; internal int Calls; internal Action? Hook { get; set; } }
    private sealed class Setup : IDisposable
    {
        internal readonly AnimationNodeStateMachine Machine = new(); internal readonly AnimationTree Tree = new(); internal readonly Probe Target = new() { Name = "target" }; internal readonly AnimationLibrary Library = new(); internal readonly Animation[] Clips = new Animation[3]; internal readonly AnimationNodeAnimation[] Leaves = new AnimationNodeAnimation[3]; internal readonly SceneTree Scene; internal readonly AnimationNodeStateMachinePlayback Playback; private readonly AnimationNodeStateMachineTransition _start = new() { AdvanceMode = AnimationAdvanceMode.Auto };
        internal Setup() { for (var i = 0; i < 3; i++) { var name = ((char)('a' + i)).ToString(); var clip = new Animation { Length = 4 }; var track = clip.AddTrack(X); clip.TrackSetPath(track, "target:X"); clip.TrackInsertKey(track, 0, i == 0 ? 10d : i == 1 ? 30d : 50d); Clips[i] = clip; Library.AddAnimation(name, clip); var leaf = new AnimationNodeAnimation { Animation = name }; Leaves[i] = leaf; Machine.AddNode(name, leaf); } Machine.AddTransition("Start", "a", _start); var root = new Node(); root.AddChild(Target); root.AddChild(Tree); Scene = new(root); Tree.AddAnimationLibrary("", Library); Tree.TreeRoot = Machine; Playback = Tree.GetParameter("", AnimationNodeStateMachine.Playback); }
        public void Dispose() { Scene.Dispose(); Machine.Dispose(); _start.Dispose(); Library.Dispose(); foreach (var leaf in Leaves) leaf.Dispose(); foreach (var clip in Clips) clip.Dispose(); }
    }
    private static void Near(double actual, double expected) => Check(Math.Abs(actual - expected) < .0001, $"Expected {expected}, got {actual}.");
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
