using Electron2D;

internal static class AnimationActionTests
{
    private static readonly PropertyDescriptor<Probe, double> X = new("X", n => n.X, (n, v) => { n.X = v; n.Writes++; n.Hook?.Invoke(); });
    private static readonly PropertyDescriptor<Probe, double> Y = new("Y", n => n.Y, (n, v) => n.Y = v);
    internal static void Run() { Authoring(); OneShot(); RestartAndLoops(); Transition(); TransitionPolicies(); IsolationAndFailures(); SeekingAndEvents(); Warm(); Console.WriteLine("Animation action requests, envelopes/curves/filters, restart/loop breaks, named transitions, shared clocks, edits/test-only/failures and warmed checks passed."); }
    private static void Authoring()
    {
        using var shot = new AnimationNodeOneShot(); Check(shot.GetInputCount() == 2 && shot.GetInputName(1) == "shot" && shot.MixMode == AnimationMixMode.Blend && shot.AutorestartDelay == 1, "OneShot defaults."); Reject<ArgumentOutOfRangeException>(() => shot.FadeInTime = double.NaN);
        using var transition = new AnimationNodeTransition { InputCount = 3 }; Check(transition.GetInputName(2) == "state_2" && transition.IsInputReset(1) && !transition.IsInputSetAsAutoAdvance(1), "Transition input defaults."); AnimationNode throughBase = transition; throughBase.RemoveInput(1); Check(transition.InputCount == 2 && transition.GetInputName(1) == "state_2", "Virtual edits retain policies."); throughBase.AddInput("extra"); transition.SetInputReset(2, false); transition.SetInputBreakLoopAtEnd(2, true); transition.SetInputAsAutoAdvance(2, true);
        using var copy = (AnimationNodeTransition)transition.Duplicate(); Check(!copy.IsInputReset(2) && copy.IsInputLoopBrokenAtEnd(2) && copy.IsInputSetAsAutoAdvance(2), "Definition copies retain policies."); Reject<ArgumentOutOfRangeException>(() => transition.InputCount = -1);
        using var curve = UnitCurve(); shot.FadeInCurve = shot.FadeOutCurve = curve; using var deep = (AnimationNodeOneShot)shot.Duplicate(true); Check(deep.FadeInCurve != curve && deep.FadeInCurve == deep.FadeOutCurve, "Deep curve aliases."); deep.FadeInCurve!.Dispose();
        Action fail = () => throw new InvalidOperationException("edit fixture"); transition.TreeChanged += fail; Reject<AggregateException>(() => throughBase.AddInput("committed")); transition.TreeChanged -= fail; Check(transition.InputCount == 4 && transition.IsInputReset(3), "Callback failure preserves aligned committed policy storage.");
    }
    private static void OneShot()
    {
        using var shot = new AnimationNodeOneShot { FadeInTime = 1, FadeOutTime = 1 }; using var setup = new Setup(shot, Clip(10), Clip(30)); setup.Tree.Advance(0); Near(setup.Target.X, 10); Fire(setup); setup.Tree.Advance(0); Near(setup.Target.X, 10.0003); Check(setup.Tree.GetParameter("control", AnimationNodeOneShot.Active) && setup.Tree.GetParameter("control", AnimationNodeOneShot.Request) == AnimationOneShotRequest.None, "Fire consumes request and activates.");
        setup.Tree.Advance(.5); Near(setup.Target.X, 10.0003); setup.Tree.Advance(.25); Near(setup.Target.X, 20); setup.Tree.Advance(.25); Near(setup.Target.X, 25); setup.Tree.Advance(.25); Near(setup.Target.X, 30);
        setup.Tree.SetParameter("control", AnimationNodeOneShot.Request, AnimationOneShotRequest.FadeOut); setup.Tree.Advance(0); Check(!setup.Tree.GetParameter("control", AnimationNodeOneShot.InternalActive) && setup.Tree.GetParameter("control", AnimationNodeOneShot.Active), "Fade keeps public activity."); setup.Tree.Advance(.5); Near(setup.Target.X, 30); setup.Tree.Advance(.25); Near(setup.Target.X, 20); setup.Tree.Advance(.25); Near(setup.Target.X, 15); setup.Tree.Advance(0); Check(!setup.Tree.GetParameter("control", AnimationNodeOneShot.Active), "Fade completes."); setup.Tree.Advance(0); Near(setup.Target.X, 10);
        using var curve = UnitCurve(); shot.FadeInCurve = shot.FadeOutCurve = curve; Fire(setup); setup.Tree.Advance(0); setup.Tree.Advance(.5); setup.Tree.Advance(0); Near(setup.Target.X, 15); setup.Tree.SetParameter("control", AnimationNodeOneShot.Request, AnimationOneShotRequest.FadeOut); setup.Tree.Advance(0); setup.Tree.Advance(.5); setup.Tree.Advance(0); Near(setup.Target.X, 25);
        shot.FadeInTime = 0; shot.FadeOutTime = 0; shot.FilterEnabled = true; shot.SetFilterPath("target:X", true); Add(setup.Clips[0], Y, 20); Add(setup.Clips[1], Y, 80); Fire(setup); setup.Tree.Advance(0); Near(setup.Target.X, 30); Near(setup.Target.Y, 20); shot.MixMode = AnimationMixMode.Add; setup.Tree.Advance(0); Near(setup.Target.X, 40); Near(setup.Target.Y, 20);
        Reject<InvalidOperationException>(() => setup.Tree.SetParameter("control", AnimationNodeOneShot.Active, false)); setup.Tree.SetParameter("control", AnimationNodeOneShot.Request, (AnimationOneShotRequest)42); Reject<ArgumentOutOfRangeException>(() => setup.Tree.Advance(0));
    }
    private static void RestartAndLoops()
    {
        using var shot = new AnimationNodeOneShot { Autorestart = true, AutorestartDelay = .2, FadeOutTime = .25 }; using var setup = new Setup(shot, Clip(10), Clip(30, 1)); setup.Tree.Advance(0); Fire(setup); setup.Tree.Advance(0); setup.Tree.Advance(.5); setup.Tree.Advance(.25); Check(!setup.Tree.GetParameter("control", AnimationNodeOneShot.InternalActive), "Automatic fade starts near the endpoint."); setup.Tree.Advance(.25); Check(!setup.Tree.GetParameter("control", AnimationNodeOneShot.Active), "Action completes."); Near(setup.Tree.GetParameter("control", AnimationNodeOneShot.TimeToRestart), .2); setup.Tree.Advance(.2); Check(!setup.Tree.GetParameter("control", AnimationNodeOneShot.Active), "Zero restart timer waits for negative crossing."); setup.Tree.Advance(.01); Check(setup.Tree.GetParameter("control", AnimationNodeOneShot.Active), "Pending auto restart fires.");
        setup.Tree.SetParameter("control", AnimationNodeOneShot.Request, AnimationOneShotRequest.Abort); setup.Tree.Advance(0); Near(setup.Tree.GetParameter("control", AnimationNodeOneShot.TimeToRestart), -1); shot.AutorestartRandomDelay = .1; Fire(setup); setup.Tree.Advance(0); setup.Tree.Advance(1); var restart = setup.Tree.GetParameter("control", AnimationNodeOneShot.TimeToRestart); Check(restart >= .2 && restart <= .3, "Uniform restart delay range.");
        shot.Autorestart = false; shot.FadeOutTime = 0; setup.Clips[1].LoopMode = SpriteFrames.LoopMode.Linear; Fire(setup); setup.Tree.Advance(0); setup.Tree.Advance(.75); Check(setup.Tree.GetParameter("control", AnimationNodeOneShot.Active), "Loop retains action without break."); shot.BreakLoopAtEnd = true; Fire(setup); setup.Tree.Advance(0); setup.Tree.Advance(.75); Check(!setup.Tree.GetParameter("control", AnimationNodeOneShot.Active), "Predictive cycle-end flag permits loop break.");
        Fire(setup); setup.Tree.Advance(0); shot.AbortOnReset = true; setup.Tree.TreeRoot = null; setup.Tree.TreeRoot = setup.Graph; setup.Tree.Advance(0); Check(!setup.Tree.GetParameter("control", AnimationNodeOneShot.Active), "AbortOnReset cancels active action.");
    }
    private static void Transition()
    {
        using var node = new AnimationNodeTransition { InputCount = 3, XFadeTime = 1 }; using var setup = new Setup(node, Clip(10), Clip(30), Clip(70)); setup.Tree.Advance(0); Near(setup.Target.X, 10); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.CurrentIndex) == 0, "Initial selection is usable on first frame."); Request(setup, "state_1"); setup.Tree.Advance(.5); Near(setup.Target.X, 10.0003); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.CurrentState) == "state_1", "Diagnostics switch at fade start."); setup.Tree.Advance(.25); Near(setup.Target.X, 20); setup.Tree.Advance(.25); Near(setup.Target.X, 25); setup.Tree.Advance(0); Near(setup.Target.X, 30.0001); setup.Tree.Advance(0); Near(setup.Target.X, 30);
        using var curve = UnitCurve(); node.XFadeCurve = curve; Request(setup, "state_0"); setup.Tree.Advance(.5); setup.Tree.Advance(0); Near(setup.Target.X, 15); Request(setup, "state_2"); setup.Tree.Advance(.25); Near(setup.Target.X, 10.0007); setup.Tree.Advance(.25); Check(setup.Target.X > 10 && setup.Target.X < 70, "Interrupted transition keeps its prior selected state.");
        node.SetInputName(2, "renamed"); setup.Tree.Advance(0); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.CurrentState) == "renamed", "Renaming updates diagnostics per tree."); node.RemoveInput(0); setup.Tree.Advance(0); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.CurrentIndex) == 1, "Removing an earlier port preserves selected identity and shifts connection."); Request(setup, "missing"); Reject<ArgumentException>(() => setup.Tree.Advance(0)); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.TransitionRequest) == "", "Invalid request is consumed.");
    }
    private static void TransitionPolicies()
    {
        using var node = new AnimationNodeTransition { InputCount = 2 }; using var setup = new Setup(node, Moving(), Moving()); setup.Tree.Advance(0); setup.Tree.Advance(.5); Request(setup, "state_1"); setup.Tree.Advance(.1); Near(setup.Tree.GetParameter("b", AnimationNode.CurrentPosition), 0); setup.Tree.Advance(.5); node.AllowTransitionToSelf = true; Request(setup, "state_1"); setup.Tree.Advance(0); Near(setup.Tree.GetParameter("b", AnimationNode.CurrentPosition), 0);
        node.Sync = true; node.SetInputReset(0, false); setup.Tree.Advance(.25); var pos = setup.Tree.GetParameter("a", AnimationNode.CurrentPosition); Request(setup, "state_0"); setup.Tree.Advance(.1); Near(setup.Tree.GetParameter("a", AnimationNode.CurrentPosition), pos + .1); node.Sync = false; node.SetInputAsAutoAdvance(0, true); setup.Clips[0].Length = 1; setup.Tree.Advance(1); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.TransitionRequest) == "state_1", "Automatic advance queues for next pass."); setup.Tree.Advance(0); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.CurrentIndex) == 1, "Automatic request switches.");
        node.SetInputAsAutoAdvance(1, true); setup.Clips[1].Length = 1; setup.Clips[1].LoopMode = SpriteFrames.LoopMode.Linear; setup.Tree.Advance(.75); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.TransitionRequest) == "", "Loop without break does not auto advance."); node.SetInputBreakLoopAtEnd(1, true); setup.Tree.Advance(.15); Check(setup.Tree.GetParameter("control", AnimationNodeTransition.TransitionRequest) == "state_0", "Loop-break prediction queues wrap.");
    }
    private static void IsolationAndFailures()
    {
        using var shot = new AnimationNodeOneShot { FadeInTime = 1 }; using var setup = new Setup(shot, Clip(10), Clip(30)); using var other = new Setup(shot, Clip(100), Clip(300)); setup.Tree.Advance(0); other.Tree.Advance(0); Fire(setup); setup.Tree.Advance(.5); Check(setup.Tree.GetParameter("control", AnimationNodeOneShot.Active) && !other.Tree.GetParameter("control", AnimationNodeOneShot.Active), "Shared controllers isolate requests/timers.");
        using var curve = UnitCurve(); shot.FadeInCurve = curve; curve.Dispose(); setup.Tree.SetParameter("control", AnimationNodeOneShot.FadeInRemaining, .5); Reject<ObjectDisposedException>(() => setup.Tree.Advance(.1)); shot.FadeInCurve = null; setup.Tree.Advance(0); Near(setup.Target.X, 20);
        setup.Target.Hook = () => setup.Tree.TreeRoot = null; setup.Tree.Advance(.1); Check(setup.Tree.TreeRoot is null, "Setter reentry abandons remaining commits."); setup.Target.Hook = null;
        using var gate = new TestingGate(); using var node = new AnimationNodeTransition { InputCount = 2 }; using var tested = new Setup(node, Clip(10), Clip(30)); tested.Graph.AddNode("gate", gate); tested.Graph.DisconnectNode("output", 0); tested.Graph.ConnectNode("gate", 0, "control"); tested.Graph.ConnectNode("output", 0, "gate"); Request(tested, "state_1"); tested.Tree.Advance(0); Check(tested.Tree.GetParameter("control", AnimationNodeTransition.TransitionRequest) == "state_1" && tested.Tree.GetParameter("control", AnimationNodeTransition.CurrentIndex) == -1, "Test-only selection preserves cells/request."); gate.TestOnly = false; tested.Tree.Advance(0); Near(tested.Target.X, 30);
    }
    private static void SeekingAndEvents()
    {
        using var shot = new AnimationNodeOneShot(); using var setup = new Setup(shot, Clip(10), Clip(30)); using var seek = new AnimationNodeTimeSeek(); setup.Graph.AddNode("seek", seek); setup.Graph.DisconnectNode("output", 0); setup.Graph.ConnectNode("seek", 0, "control"); setup.Graph.ConnectNode("output", 0, "seek"); setup.Tree.Advance(0); setup.Tree.Advance(.5); setup.Tree.SetParameter("seek", AnimationNodeTimeSeek.SeekRequest, 3d); setup.Tree.Advance(0); Near(setup.Tree.GetParameter("a", AnimationNode.CurrentDelta), -2.5); seek.ExplicitElapse = false; setup.Tree.SetParameter("seek", AnimationNodeTimeSeek.SeekRequest, 1d); setup.Tree.Advance(0); Near(setup.Tree.GetParameter("a", AnimationNode.CurrentDelta), 0);
        setup.Scene.ProcessFrame(0); Action<string> fail = _ => throw new InvalidOperationException("event fixture"); setup.Tree.AnimationStarted += fail; Fire(setup); Reject<AggregateException>(() => setup.Scene.ProcessFrame(0)); setup.Tree.AnimationStarted -= fail; setup.Tree.SetParameter("control", AnimationNodeOneShot.Request, AnimationOneShotRequest.Abort); setup.Scene.ProcessFrame(0); var delivered = 0; setup.Tree.AnimationStarted += _ => delivered++; Fire(setup); setup.Scene.ProcessFrame(0); Check(delivered == 1, "Deferred notice recycling survives handler failure.");
        using var transition = new AnimationNodeTransition { InputCount = 2 }; using var first = new Setup(transition, Clip(10), Clip(30)); using var second = new Setup(transition, Clip(100), Clip(300)); first.Tree.Advance(0); second.Tree.Advance(0); Request(first, "state_1"); first.Tree.Advance(0); transition.SetInputName(0, "renamed"); second.Tree.Advance(0); Check(first.Tree.GetParameter("control", AnimationNodeTransition.CurrentIndex) == 1 && second.Tree.GetParameter("control", AnimationNodeTransition.CurrentState) == "renamed", "Shared transition selection and edits reconcile in every tree.");
    }
    private static void Warm()
    {
        using var shot = new AnimationNodeOneShot { Autorestart = true, AutorestartRandomDelay = .01, FadeInTime = .01, FadeOutTime = .01 }; using var setup = new Setup(shot, Clip(10), Clip(30, .2)); shot.AutorestartDelay = .01; var starts = 0; var finishes = 0; setup.Tree.AnimationStarted += _ => starts++; setup.Tree.AnimationFinished += _ => finishes++; setup.Scene.ProcessFrame(0); Fire(setup); for (var i = 0; i < 32; i++) setup.Scene.ProcessFrame(.01);
        var before = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 256; i++) setup.Scene.ProcessFrame(.01); Check(GC.GetAllocatedBytesForCurrentThread() == before, "Warm restarted envelopes allocate zero managed bytes."); Check(starts > 2 && finishes > 1, "Warmed restarts include deferred start/finish delivery.");
        using var transition = new AnimationNodeTransition { InputCount = 2, XFadeTime = 1 }; using var other = new Setup(transition, Clip(10), Clip(30)); var transitionStarts = 0; other.Tree.AnimationStarted += _ => transitionStarts++; other.Scene.ProcessFrame(0); for (var i = 0; i < 20; i++) { Request(other, (i & 1) == 0 ? "state_1" : "state_0"); other.Scene.ProcessFrame(.01); }
        before = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 256; i++) { Request(other, (i & 1) == 0 ? "state_1" : "state_0"); other.Scene.ProcessFrame(.01); }
        Check(GC.GetAllocatedBytesForCurrentThread() == before, "Warm interrupted transitions allocate zero managed bytes."); Check(transitionStarts > 256, "Interrupted transitions retain all deferred start events.");
    }
    internal static void RunHost()
    {
        var backend = Environment.GetEnvironmentVariable("ELECTRON2D_ANIMATION_RENDERER") ?? "gpu"; var settings = ProjectSettings.Instance; var prior = settings.Get(ProjectSettings.RenderingMethod); settings.Set(ProjectSettings.RenderingMethod, backend);
        var descriptor = new PropertyDescriptor<Entity, Vector2>(nameof(Entity.Position), n => n.Position, (n, v) => n.Position = v);
        Vector2[] expected = [new(16, 16), new(16, 16), new(32, 16), new(48, 16), new(48, 16), new(48, 16), new(60, 16), new(72, 16), new(72, 16), new(60, 16), new(48, 16), new(120, 32), new(48, 16)];
        try
        {
            for (var run = 0; run < 2; run++)
            {
                using var shot = new AnimationNodeOneShot { FadeInTime = .5, FadeOutTime = .5 }; using var transition = new AnimationNodeTransition { InputCount = 2, XFadeTime = 1 }; using var graph = new AnimationNodeBlendTree(); using var a = new AnimationNodeAnimation { Animation = "a" }; using var b = new AnimationNodeAnimation { Animation = "b" }; using var c = new AnimationNodeAnimation { Animation = "c" }; graph.AddNode("a", a); graph.AddNode("b", b); graph.AddNode("c", c); graph.AddNode("shot", shot); graph.AddNode("transition", transition); graph.ConnectNode("shot", 0, "b"); graph.ConnectNode("shot", 1, "c"); graph.ConnectNode("transition", 0, "a"); graph.ConnectNode("transition", 1, "shot"); graph.ConnectNode("output", 0, "transition");
                using var library = new AnimationLibrary(); var clips = new Animation[3]; for (var i = 0; i < clips.Length; i++) { var clip = new Animation { Length = 4 }; var track = clip.AddTrack(descriptor); clip.TrackSetPath(track, "box:Position"); clip.TrackInsertKey(track, 0, new Vector2(i == 0 ? 16 : i == 1 ? 48 : 72, 16)); clips[i] = clip; library.AddAnimation(((char)('a' + i)).ToString(), clip); }
                var window = new Window { Size = new(160, 64), Title = "Electron2D animation action controllers" }; var box = new Box { Name = "box" }; var tree = new AnimationTree { TreeRoot = graph, CallbackModeProcess = AnimationMixer.AnimationCallbackModeProcess.Manual }; tree.AddAnimationLibrary("", library); window.AddChild(box); window.AddChild(tree); var stage = 0;
                box.Start = () =>
                {
                    var renderer = RenderingServer.Instance!; renderer.SetDefaultClearColor(Colors.Black); tree.Advance(0); renderer.FramePostDraw += () =>
                    {
                        using var pixels = renderer.Readback(); var at = expected[stage]; Check(pixels.GetPixel((int)at.X, (int)at.Y).R > .9f && pixels.GetPixel((int)at.X, (int)at.Y).G < .1f, "Composed transition/action pose reaches rendered pixels."); if (stage > 0 && expected[stage - 1] != at) { var old = expected[stage - 1]; Check(pixels.GetPixel((int)old.X, (int)old.Y).R < .1f, "Old action pose clears."); }
                        switch (stage++) { case 0: tree.SetParameter("transition", AnimationNodeTransition.TransitionRequest, "state_1"); tree.Advance(.5); break; case 1: tree.Advance(.5); break; case 2: tree.Advance(0); break; case 3: tree.SetParameter("shot", AnimationNodeOneShot.Request, AnimationOneShotRequest.Fire); tree.Advance(0); break; case 4: tree.Advance(.25); break; case 5: tree.Advance(.25); break; case 6: tree.Advance(0); break; case 7: tree.SetParameter("shot", AnimationNodeOneShot.Request, AnimationOneShotRequest.FadeOut); tree.Advance(0); tree.Advance(.25); break; case 8: tree.Advance(.25); break; case 9: tree.Advance(0); break; case 10: shot.MixMode = AnimationMixMode.Add; shot.FadeInTime = 0; tree.SetParameter("shot", AnimationNodeOneShot.Request, AnimationOneShotRequest.Fire); tree.Advance(0); break; case 11: tree.SetParameter("shot", AnimationNodeOneShot.Request, AnimationOneShotRequest.Abort); tree.Advance(0); break; case 12: window.Tree!.Quit(); break; }
                    };
                };
                try { Check(Engine.Instance.Run(window) == 0 && stage == 13 && window.IsDisposed && !shot.IsDisposed && !transition.IsDisposed && !library.IsDisposed, "Action host cleanup borrows resources."); Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(new { scenario = "animation-actions-host", backend, run, stages = stage, cleaned = window.IsDisposed })); } finally { foreach (var clip in clips) clip.Dispose(); }
            }
        }
        finally { settings.Set(ProjectSettings.RenderingMethod, prior); }
    }
    private sealed class Box : Entity { internal Action? Start; protected override void OnReady() => Start?.Invoke(); protected override void OnDraw() => DrawRect(new(-3, -3, 6, 6), Colors.Red); }
    private sealed class TestingGate : AnimationNode { internal bool TestOnly = true; internal TestingGate() => AddInput("in"); protected override double OnProcess(double time, bool seek, bool external, bool testOnly) => BlendInput(0, time, seek, external, 1, testOnly: TestOnly); }
    private static void Fire(Setup setup) => setup.Tree.SetParameter("control", AnimationNodeOneShot.Request, AnimationOneShotRequest.Fire);
    private static void Request(Setup setup, string name) => setup.Tree.SetParameter("control", AnimationNodeTransition.TransitionRequest, name);
    private static Curve UnitCurve() { var c = new Curve(); c.AddPoint(new(0, 0)); c.AddPoint(new(.5f, .25f)); c.AddPoint(new(1, 1)); return c; }
    private static Animation Clip(double value, double length = 4) { var a = new Animation { Length = length }; Add(a, X, value); return a; }
    private static Animation Moving() { var a = Clip(0); a.TrackInsertKey(0, 4, 40d); return a; }
    private static void Add(Animation clip, PropertyDescriptor<Probe, double> property, double value) { var i = clip.AddTrack(property); clip.TrackSetPath(i, "target:" + property.Name); clip.TrackInsertKey(i, 0, value); }
    private sealed class Setup : IDisposable
    {
        internal readonly AnimationNodeBlendTree Graph = new(); internal readonly AnimationTree Tree = new(); internal readonly Probe Target = new() { Name = "target" }; internal readonly AnimationLibrary Library = new(); internal readonly SceneTree Scene; internal readonly Animation[] Clips; private readonly AnimationNodeAnimation[] _leaves;
        internal Setup(AnimationNode control, params Animation[] clips) { Clips = clips; _leaves = new AnimationNodeAnimation[control.GetInputCount()]; Graph.AddNode("control", control); Graph.ConnectNode("output", 0, "control"); for (var i = 0; i < clips.Length; i++) Library.AddAnimation(((char)('a' + i)).ToString(), clips[i]); for (var i = 0; i < _leaves.Length; i++) { var name = ((char)('a' + i)).ToString(); var leaf = new AnimationNodeAnimation { Animation = name }; _leaves[i] = leaf; Graph.AddNode(name, leaf); Graph.ConnectNode("control", i, name); } var root = new Node(); root.AddChild(Target); root.AddChild(Tree); Scene = new(root); Tree.AddAnimationLibrary("", Library); Tree.TreeRoot = Graph; }
        public void Dispose() { Scene.Dispose(); Graph.Dispose(); Library.Dispose(); foreach (var leaf in _leaves) leaf.Dispose(); foreach (var clip in Clips) clip.Dispose(); }
    }
    private sealed class Probe : Node { internal double X, Y; internal int Writes; internal Action? Hook; }
    private static void Near(double actual, double expected) => Check(Math.Abs(actual - expected) < 1e-5, $"Expected {expected}, got {actual}.");
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
