using Electron2D;

internal static class AnimationNestedTrackTests
{
    private static readonly PropertyDescriptor<Probe, double> X = new("X", n => n.X, (n, v) => n.X = v);
    internal static void Run() { Authoring(); Execute(); Seeking(); LoopsAndGraph(); FiltersAndCycles(); Lifetime(); Warm(); Console.WriteLine("Nested animation tracks: typed keys/copies, start/stop/seek/sections/loops, graph/filter, lifetime/reentry/cycles and prepared zero-allocation frames passed."); }
    private static void Authoring()
    {
        using var clip = new Animation(); var t = clip.AddAnimationTrack(); Check(clip.TrackGetType(t) == Animation.TrackType.Animation, "Executable kind."); clip.TrackSetPath(t, "child"); clip.AnimationTrackInsertKey(t, .5, "a"); clip.AnimationTrackInsertKey(t, .25, "b"); Check(clip.FindTrack("child", Animation.TrackType.Animation) == t && clip.FindTrack("child", Animation.TrackType.Method) == -1, "Path/kind identity."); Check(clip.AnimationTrackGetKeyAnimation(t, 0) == "b", "Sorted names."); clip.TrackSetKeyValue(t, 0, "a"); Check(clip.TrackGetKeyValue<string>(t, 0) == "a", "Generic storage."); using var copy = (Animation)clip.Duplicate(true); clip.AnimationTrackSetKeyAnimation(t, 0, "changed"); Check(copy.AnimationTrackGetKeyAnimation(t, 0) == "a", "Independent copied keys."); Reject<ArgumentException>(() => clip.TrackSetPath(t, "child:AssignedAnimation")); Reject<ArgumentNullException>(() => clip.AnimationTrackInsertKey(t, 0, null!)); Reject<InvalidCastException>(() => clip.TrackGetKeyValue<int>(t, 0)); var v = clip.AddTrack(X); Reject<InvalidOperationException>(() => clip.AnimationTrackInsertKey(v, 0, "a")); Reject<InvalidOperationException>(() => clip.ValueTrackGetUpdateMode(t));
    }
    private static void Execute()
    {
        using var setup = new Setup(); setup.Parent.Play("control"); setup.Parent.Advance(0); Check(setup.Child.IsPlaying() && setup.Child.AssignedAnimation == "a", "Startup controls child."); setup.Child.Advance(.25); Near(setup.Target.X, 2.5); setup.Parent.Advance(.5); Check(setup.Child.AssignedAnimation == "b", "Crossed key chooses named clip."); setup.Child.Advance(.25); Near(setup.Target.X, 22.5); setup.Parent.Advance(.25); Check(!setup.Child.IsPlaying(), "Stop key stops controlled child."); Near(setup.Target.X, 20);
        setup.Parent.Stop(true); setup.Parent.Play("control"); setup.Parent.Advance(.6); Check(setup.Child.AssignedAnimation == "b", "Large startup seeks last applicable key."); setup.Child.Advance(0); Near(setup.Target.X, 21); setup.Parent.Pause(); Check(!setup.Child.IsPlaying(), "Parent pause clears owned playback without destroying child."); Near(setup.Target.X, 21);
        setup.Parent.PlaySection("control", .5, 1); setup.Parent.Advance(0); Check(setup.Child.AssignedAnimation == "b" && setup.Child.IsPlaying(), "Section startup."); setup.Parent.Stop(true); setup.Parent.PlayBackwards("control"); setup.Parent.Advance(.6); Check(setup.Child.AssignedAnimation == "a", "Reverse startup seeks preceding key."); setup.Parent.Advance(.4); Check(setup.Child.AssignedAnimation == "a", "Reverse range selects final crossed key.");
    }
    private static void Seeking()
    {
        using var setup = new Setup(); setup.Parent.AssignedAnimation = "control"; setup.Parent.Seek(.6, true); Check(!setup.Child.IsPlaying() && setup.Child.AssignedAnimation == "b", "External paused seek stays paused."); Near(setup.Target.X, 21);
        setup.Parent.Play("control"); setup.Parent.Seek(.25, true, true); Check(!setup.Child.IsPlaying(), "Update-only seek samples without startup."); Near(setup.Target.X, 2.5); setup.Parent.Seek(.25, true); Check(!setup.Child.IsPlaying(), "External seek of stopped child remains pose-only."); setup.Parent.Advance(0); setup.Parent.Stop(true); setup.Parent.Play("control"); setup.Parent.Advance(0); setup.Parent.Seek(.6, true); Check(setup.Child.IsPlaying() && setup.Child.AssignedAnimation == "b", "External seek of running child retains playback."); setup.Child.Advance(0); Near(setup.Target.X, 21);
        setup.ParentClip.Length = 4; setup.ParentClip.AnimationTrackSetKeyAnimation(0, 0, "a"); setup.ParentClip.TrackRemoveKey(0, 2); setup.ParentClip.TrackRemoveKey(0, 1); setup.A.LoopMode = SpriteFrames.LoopMode.Linear; setup.Parent.Seek(2.5, true); setup.Child.Advance(0); Near(setup.Child.CurrentAnimationPosition, .5); Near(setup.Target.X, 5); setup.A.LoopMode = SpriteFrames.LoopMode.PingPong; setup.Parent.Seek(1.25, true); setup.Child.Advance(0); Near(setup.Child.CurrentAnimationPosition, .75); Near(setup.Target.X, 7.5);
        setup.A.LoopMode = SpriteFrames.LoopMode.None; setup.Parent.Stop(true); setup.Parent.Play("control"); setup.Parent.Advance(2); Check(!setup.Child.IsPlaying(), "Internal startup beyond finite child clip does not start expired playback.");
    }
    private static void LoopsAndGraph()
    {
        using var setup = new Setup(); setup.ParentClip.LoopMode = SpriteFrames.LoopMode.Linear; setup.Parent.Play("control"); setup.Parent.Advance(0); setup.Parent.Advance(2.6); Check(setup.Child.AssignedAnimation == "b" && setup.Child.IsPlaying(), "Multi-loop traversal picks last key."); setup.ParentClip.LoopMode = SpriteFrames.LoopMode.PingPong; setup.Parent.Stop(true); setup.Parent.Play("control"); setup.Parent.Advance(0); setup.Parent.Advance(1.8); Check(setup.Child.AssignedAnimation == "b", "Ping-pong last crossed key.");
        setup.Parent.Active = false; using var leaf = new AnimationNodeAnimation { Animation = "control" }; var tree = new AnimationTree { TreeRoot = leaf, CallbackModeProcess = AnimationMixer.AnimationCallbackModeProcess.Manual }; tree.AddAnimationLibrary("", setup.ParentLibrary); setup.Root.AddChild(tree); tree.Advance(0); Check(setup.Child.AssignedAnimation == "a" && setup.Child.IsPlaying(), "Graph startup controls child."); tree.Advance(.5); Check(setup.Child.AssignedAnimation == "b", "Graph crossing."); tree.ClearCaches(); Check(!setup.Child.IsPlaying(), "Graph cache clearing stops its owned child."); tree.Dispose();
    }
    private static void FiltersAndCycles()
    {
        using var setup = new Setup(); setup.Parent.Active = false; using var empty = new Animation(); setup.ParentLibrary.AddAnimation("empty", empty); using var graph = new AnimationNodeBlendTree(); using var mix = new AnimationNodeBlend2 { Sync = true, FilterEnabled = true }; using var a = new AnimationNodeAnimation { Animation = "empty" }; using var b = new AnimationNodeAnimation { Animation = "control" }; graph.AddNode("a", a); graph.AddNode("b", b); graph.AddNode("mix", mix); graph.ConnectNode("mix", 0, "a"); graph.ConnectNode("mix", 1, "b"); graph.ConnectNode("output", 0, "mix"); var tree = new AnimationTree { TreeRoot = graph, CallbackModeProcess = AnimationMixer.AnimationCallbackModeProcess.Manual }; tree.AddAnimationLibrary("", setup.ParentLibrary); setup.Root.AddChild(tree); tree.SetParameter("mix", AnimationNodeBlend2.BlendAmount, 1); tree.Advance(0); Check(!setup.Child.IsPlaying(), "Unselected filter suppresses nested command."); mix.SetFilterPath("child", true); tree.Advance(.5); Check(setup.Child.IsPlaying() && setup.Child.AssignedAnimation == "b", "Node-only filter enables latest key after silent Sync clocks."); tree.Dispose();
        using var cyclic = new Setup(); var t = cyclic.A.AddAnimationTrack(); cyclic.A.TrackSetPath(t, "parent"); cyclic.A.AnimationTrackInsertKey(t, 0, "control"); cyclic.Parent.AssignedAnimation = "control"; Reject<InvalidOperationException>(() => cyclic.Parent.Seek(.25, true, true)); Check(!cyclic.Parent.IsPlaying() && !cyclic.Child.IsPlaying(), "Synchronous mutual seek cycle rejects without recursive evaluation.");
    }
    private static void Lifetime()
    {
        using var setup = new Setup(); setup.Parent.Play("control"); setup.Parent.Advance(0); setup.Child.Play("b"); setup.Parent.ClearCaches(); Check(setup.Child.IsPlaying() && setup.Child.AssignedAnimation == "b", "Cleanup does not revoke later independent control."); setup.Child.Stop(true); setup.Parent.Stop(true); setup.Parent.Play("control"); setup.Parent.Advance(0); setup.ParentClip.Clear(); setup.Parent.Advance(0); Check(!setup.Child.IsPlaying(), "Source mutation stops tracked playback.");
        using var cycle = new Animation(); var t = cycle.AddAnimationTrack(); cycle.TrackSetPath(t, "parent"); cycle.AnimationTrackInsertKey(t, 0, "cycle"); setup.ParentLibrary.AddAnimation("cycle", cycle); setup.Parent.Play("cycle"); Reject<InvalidOperationException>(() => setup.Parent.Advance(0)); Check(!setup.Parent.IsPlaying(), "Self-control rejects and pauses current pass.");
        using var other = new Setup(); other.Child.AnimationStarted += _ => other.Parent.Stop(true); other.Parent.Play("control"); other.Parent.Advance(0); Check(!other.Parent.IsPlaying() && !other.Child.IsPlaying(), "Startup callback stopping owner leaves no orphan child.");
        using var takeover = new Setup(); takeover.Child.AnimationStarted += name => { if (name == "a") takeover.Child.Play("b"); }; takeover.Parent.Play("control"); takeover.Parent.Advance(.25); Near(takeover.Child.CurrentAnimationPosition, 0); takeover.Parent.ClearCaches(); Check(takeover.Child.IsPlaying() && takeover.Child.AssignedAnimation == "b", "Observer takeover receives no stale seek or later cleanup.");
        using var throwing = new Setup(); throwing.Child.AnimationStarted += _ => throw new InvalidOperationException("child observer"); throwing.Parent.Play("control"); Reject<Exception>(() => throwing.Parent.Advance(0)); Check(!throwing.Parent.IsPlaying() && !throwing.Child.IsPlaying(), "Startup failure cleans owned child and pauses parent.");
    }
    private static void Warm()
    {
        using var setup = new Setup(); setup.ParentClip.LoopMode = SpriteFrames.LoopMode.Linear; setup.Parent.Play("control"); for (var i = 0; i < 24; i++) { setup.Parent.Advance(.25); setup.Child.Advance(.01); }
        var before = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 256; i++) { setup.Parent.Advance(.25); setup.Child.Advance(.01); }
        Check(GC.GetAllocatedBytesForCurrentThread() == before, "Repeated nested start/stop and child property execution reuse prepared caches."); before = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 256; i++) { setup.Parent.Advance(0); setup.Child.Advance(0); }
        Check(GC.GetAllocatedBytesForCurrentThread() == before, "Repeated idle parent/child evaluations allocate zero bytes.");
    }
    internal static void RunHost()
    {
        var backend = Environment.GetEnvironmentVariable("ELECTRON2D_ANIMATION_RENDERER") ?? "gpu"; var settings = ProjectSettings.Service; var prior = ProjectSettings.Get(ProjectSettings.RenderingMethod); ProjectSettings.Set(ProjectSettings.RenderingMethod, backend);
        var property = new PropertyDescriptor<Entity, Vector2>(nameof(Entity.Position), n => n.Position, (n, v) => n.Position = v); int[] positions = [16, 24, 64, 64, 20, 32];
        try
        {
            for (var run = 0; run < 2; run++)
            {
                using var a = new Animation(); var ta = a.AddTrack(property); a.TrackSetPath(ta, "box:Position"); a.TrackInsertKey(ta, 0, new Vector2(16, 16)); a.TrackInsertKey(ta, 1, new Vector2(48, 16)); using var b = new Animation(); var tb = b.AddTrack(property); b.TrackSetPath(tb, "box:Position"); b.TrackInsertKey(tb, 0, new Vector2(64, 16)); b.TrackInsertKey(tb, 1, new Vector2(96, 16)); using var control = new Animation(); var t = control.AddAnimationTrack(); control.TrackSetPath(t, "child"); control.AnimationTrackInsertKey(t, 0, "a"); control.AnimationTrackInsertKey(t, .5, "b"); control.AnimationTrackInsertKey(t, .75, "[stop]"); using var parentLibrary = new AnimationLibrary(); using var childLibrary = new AnimationLibrary(); parentLibrary.AddAnimation("control", control); childLibrary.AddAnimation("a", a); childLibrary.AddAnimation("b", b);
                var window = new Window { Size = new(128, 48), Title = "Electron2D nested animation tracks" }; var box = new Box { Name = "box" }; var child = new AnimationPlayer { Name = "child", CallbackModeProcess = AnimationMixer.AnimationCallbackModeProcess.Manual, PlaybackAutoCapture = false }; var parent = new AnimationPlayer { CallbackModeProcess = AnimationMixer.AnimationCallbackModeProcess.Manual, PlaybackAutoCapture = false }; child.AddAnimationLibrary("", childLibrary); parent.AddAnimationLibrary("", parentLibrary); window.AddChild(box); window.AddChild(child); window.AddChild(parent); var stage = 0;
                box.Start = () => { var renderer = RenderingServer.Service!; RenderingServer.SetDefaultClearColor(Colors.Black); parent.Play("control"); parent.Advance(0); child.Advance(0); RenderingServer.FramePostDraw += () => { using var pixels = renderer.Readback(); var x = positions[stage]; Check(pixels.GetPixel(x, 16).R > .9f && pixels.GetPixel(x, 16).G < .1f, "Nested player orchestration reaches actual child pixels."); if (stage > 0 && positions[stage - 1] != x) Check(pixels.GetPixel(positions[stage - 1], 16).R < .1f, "Old child pose clears."); switch (stage++) { case 0: parent.Advance(.25); child.Advance(.25); break; case 1: parent.Advance(.25); child.Advance(0); break; case 2: parent.Advance(.25); Check(!child.IsPlaying(), "Stop key reaches child state."); break; case 3: parent.Seek(.125, true); Check(!child.IsPlaying(), "External pose seek retains paused child."); break; case 4: parent.Stop(true); parent.Play("control"); parent.Advance(0); child.Advance(.5); parent.ClearCaches(); Check(!child.IsPlaying(), "Cache cleanup holds rendered child pose."); break; case 5: window.Tree!.Quit(); break; } }; };
                Check(Engine.Run(window) == 0 && stage == 6 && window.IsDisposed && !control.IsDisposed && !a.IsDisposed && !parentLibrary.IsDisposed, "Nested host cleanup borrows resources."); Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(new { scenario = "animation-nested-tracks-host", backend, run, stages = stage, cleaned = window.IsDisposed }));
            }
        }
        finally { ProjectSettings.Set(ProjectSettings.RenderingMethod, prior); }
    }
    private sealed class Box : Entity { internal Action? Start; protected override void OnReady() => Start?.Invoke(); protected override void OnDraw() => DrawRect(new(-3, -3, 6, 6), Colors.Red); }
    private static Animation Clip(double offset) { var a = new Animation { Length = 1 }; var t = a.AddTrack(X); a.TrackSetPath(t, "target:X"); a.TrackInsertKey(t, 0, offset); a.TrackInsertKey(t, 1, offset + 10); return a; }
    private sealed class Setup : IDisposable
    {
        internal readonly Node Root = new(); internal readonly Probe Target = new() { Name = "target" }; internal readonly AnimationPlayer Parent = new() { Name = "parent", PlaybackAutoCapture = false, CallbackModeProcess = AnimationMixer.AnimationCallbackModeProcess.Manual }; internal readonly AnimationPlayer Child = new() { Name = "child", PlaybackAutoCapture = false, CallbackModeProcess = AnimationMixer.AnimationCallbackModeProcess.Manual }; internal readonly Animation ParentClip = new(); internal readonly AnimationLibrary ParentLibrary = new(), ChildLibrary = new(); internal readonly Animation A = Clip(0), B = Clip(20); internal readonly SceneTree Scene;
        internal Setup() { var t = ParentClip.AddAnimationTrack(); ParentClip.TrackSetPath(t, "child"); ParentClip.AnimationTrackInsertKey(t, 0, "a"); ParentClip.AnimationTrackInsertKey(t, .5, "b"); ParentClip.AnimationTrackInsertKey(t, .75, "[stop]"); ParentLibrary.AddAnimation("control", ParentClip); ChildLibrary.AddAnimation("a", A); ChildLibrary.AddAnimation("b", B); Parent.AddAnimationLibrary("", ParentLibrary); Child.AddAnimationLibrary("", ChildLibrary); Root.AddChild(Target); Root.AddChild(Child); Root.AddChild(Parent); Scene = new(Root); }
        public void Dispose() { Scene.Dispose(); ParentLibrary.Dispose(); ChildLibrary.Dispose(); ParentClip.Dispose(); A.Dispose(); B.Dispose(); }
    }
    private sealed class Probe : Node { internal double X; }
    private static void Near(double value, double expected) => Check(Math.Abs(value - expected) < 1e-5, $"Expected {expected}, got {value}.");
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
