using Electron2D;
using Path = System.IO.Path;
internal static class CodeEditTests
{
    private sealed class Root : Viewport { public override Rect2 GetVisibleRect() => new(0, 0, 640, 400); }
    internal static void Run() { Editing(); ParsingFolding(); Markers(); Completion(); CodeEdges(); Symbols(); Storage(); Console.WriteLine("CodeEdit editing, delimiters, folding, markers, typed completion and scene configuration passed."); }
    private static void Editing()
    {
        using var code = new CodeEdit { Size = new(420, 240) }; Check(code.GetGutterCount() == 3 && code.IndentSize == 4 && code.TextDirection == TextDirection.LTR, "defaults"); code.Text = "one\ntwo"; code.SelectAll(); code.IndentUseSpaces = true; code.IndentLines(); Check(code.Text == "    one\n    two", "indent selected lines"); code.UnindentLines(); Check(code.Text == "one\ntwo", "dedent"); code.Text = "\t\tone\n  two"; code.ConvertIndent(); Check(code.Text == "        one\n  two", "convert indentation"); code.Text = "a\nb\nc"; code.SetCaretLine(1); code.DuplicateLines(); Check(code.Text == "a\nb\nb\nc", "duplicate line: " + code.Text.Replace("\n", "|")); code.Undo(); Check(code.Text == "a\nb\nc", "group undo"); code.MoveLinesDown(); Check(code.Text == "a\nc\nb", "move line"); code.Text = "a \n b\nc"; code.SetCaretLine(0); code.JoinLines(); Check(code.Text == "a b\nc", "join whitespace");
        var viewport = new Root(); var input = new CodeEdit { Size = new(420, 240), AutoBraceCompletionEnabled = true, IndentAutomatic = true, IndentUseSpaces = true }; viewport.AddChild(input); using var scene = new SceneTree(viewport); scene.FlushDeferred(); InputMap.LoadFromProjectSettings(); input.GrabFocus(); scene.DispatchCommittedText(viewport, "("); Check(input.Text == "()" && input.GetCaretColumn() == 1, "native text producer brace pair"); using (var enter = new InputEventKey { Keycode = Key.Enter, Pressed = true }) viewport.PushInput(enter, true); Check(input.Text == "(\n    \n)", "pair newline indentation"); input.Undo(); Check(input.Text == "()", "newline undo"); using (var backspace = new InputEventKey { Keycode = Key.Backspace, Pressed = true }) viewport.PushInput(backspace, true); Check(input.Text == "", "paired backspace"); input.Text = "    previous"; input.IndentAutomatic = false; input.SetCaretColumn(12); using (var newline = new InputEventKey { Keycode = Key.Enter, Pressed = true }) viewport.PushInput(newline, true); Check(input.Text == "    previous\n    ", "newline inherits existing indentation without prefix expansion"); input.Text = "    item"; using (var above = new InputEventKey { Keycode = Key.Enter, ControlPressed = true, ShiftPressed = true, Pressed = true }) viewport.PushInput(above, true); Check(input.Text == "    \n    item", "above newline keeps indentation"); input.Text = ""; input.AddAutoBraceCompletionPair("<<", ">>"); scene.DispatchCommittedText(viewport, "<<"); Check(input.Text == "<<>>" && input.GetCaretColumn() == 2, "long opening key"); scene.DispatchCommittedText(viewport, ">"); Check(input.Text == "<<>>" && input.GetCaretColumn() == 4, "long closer skip"); input.SetCaretColumn(2); input.Backspace(); Check(input.Text == "", "long paired deletion"); input.Editable = false; scene.DispatchCommittedText(viewport, "ignored"); Check(input.Text == "", "read-only producer");
    }
    private static void ParsingFolding()
    {
        using var code = new CodeEdit { Size = new(400, 200), LineFolding = true }; code.AddCommentDelimiter("#", ""); code.AddCommentDelimiter("/*", "*/"); code.Text = "root:\n    child\n    next\nafter"; Check(code.CanFoldLine(0), "indent block"); code.FoldLine(0); Check(code.IsLineFolded(0) && code.GetPosAtLineColumn(1, 0) == new Vector2i(-1, -1), "hidden row geometry"); code.UnfoldLine(2); Check(!code.IsLineFolded(0) && code.GetPosAtLineColumn(1, 0) != new Vector2i(-1, -1), "unfold hidden child"); code.Text = "/*one\ntwo*/\n\"a\\\"b\" # comment"; Check(code.IsInComment(1, 1) >= 0 && code.GetDelimiterStartPosition(1, 1) == new Vector2(1, 0) && code.GetDelimiterEndPosition(1, 1) == new Vector2(5, 1), "multiline delimiter boundaries"); Check(code.IsInString(2, 4) >= 0 && code.IsInComment(2, 9) >= 0, "escaped quote and comment"); code.Text = "#region outer\nvalue\n#endregion"; Check(code.IsLineCodeRegionStart(0) && code.CanFoldLine(0), "code region"); code.FoldLine(0); code.UnfoldAllLines(); Check(code.GetFoldedLines().Length == 0, "unfold all"); code.Text = "  # comment"; Check(code.IsInComment(0) >= 0, "whole comment with leading whitespace"); code.Text = "\\\"escaped"; Check(code.IsInString(0, 2) == -1, "escaped opening key"); var copy = code.DelimiterStrings; copy[0] = "bad"; Check(code.DelimiterStrings[0] != "bad", "copied delimiters");
    }
    private static void Markers()
    { using var code = new CodeEdit { Text = "one\ntwo", GuttersDrawBreakpointsGutter = true }; var events = new List<int>(); code.BreakpointToggled += events.Add; code.SetLineAsBreakpoint(1, true); code.SetLineAsBookmarked(1, true); code.InsertLineAt(0, "new"); Check(code.IsLineBreakpointed(2) && code.IsLineBookmarked(2) && events.Contains(1) && events.Contains(2), "marker line shift"); code.Undo(); Check(code.IsLineBreakpointed(1) && code.IsLineBookmarked(1), "marker undo"); code.ClearBreakpointedLines(); Check(code.GetBreakpointedLines().Length == 0, "clear breakpoints"); }
    private static void Completion()
    { using var code = new CodeEdit { Text = "pri", CodeCompletionEnabled = true }; code.SetCaretColumn(3); var requests = 0; code.CodeCompletionRequested += () => requests++; code.RequestCodeCompletion(); Check(requests == 1, "request provider"); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "print", "print"); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "private", "private"); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Variable, "other", "other"); code.UpdateCodeCompletionOptions(false); Check(code.GetCodeCompletionOptions().Length == 2 && code.GetCodeCompletionSelectedIndex() == 0, "filter options"); code.ConfirmCodeCompletion(); Check(code.Text == "print" && code.GetCodeCompletionSelectedIndex() == -1, "confirm candidate"); code.Undo(); Check(code.Text == "pri", "completion undo group"); var option = new CodeCompletionOption(CodeEdit.CodeCompletionKind.Constant, "red", "red").WithDefaultValue(Colors.Red); Check(option.TryGetDefaultValue<Color>(out var color) && color == Colors.Red && !option.TryGetDefaultValue<int>(out _), "typed payload"); Check(code.GetTextWithCursorChar(0, 1) == "p\uffffri", "cursor marker scalar"); }
    private sealed class FilteredCode : CodeEdit { protected override CodeCompletionOption[] OnFilterCodeCompletionCandidates(CodeCompletionOption[] candidates) => candidates; }
    private sealed class CallbackCode : CodeEdit { internal Func<CodeCompletionOption[], CodeCompletionOption[]>? Filter; protected override CodeCompletionOption[] OnFilterCodeCompletionCandidates(CodeCompletionOption[] candidates) => Filter?.Invoke(candidates) ?? candidates; }
    private static void CodeEdges()
    {
        using var code = new CodeEdit { Text = "pri\npri", CodeCompletionEnabled = true, AutoBraceCompletionEnabled = true, LineFolding = true }; code.SetCaretColumn(3); code.AddCaret(1, 3); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "print()", "print()"); code.UpdateCodeCompletionOptions(true); code.ConfirmCodeCompletion(); Check(code.Text == "print()\nprint()" && code.GetCaretColumn(0) == 6 && code.GetCaretColumn(1) == 6, "multicaret function completion"); code.Undo(); Check(code.Text == "pri\npri", "multicaret completion history");
        code.Text = "'paTAIL'"; code.SetCaretColumn(3); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.FilePath, "\"path\"", "\"path\""); code.UpdateCodeCompletionOptions(true); Check(code.GetCodeCompletionOption(0)?.InsertText == "'path'", "quote normalization"); code.ConfirmCodeCompletion(true); Check(code.Text == "'path'", "quoted replacement suffix");
        code.Text = "'pa'"; code.SetCaretColumn(3); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.FilePath, "path1", "path1"); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.FilePath, "path2", "path2"); code.UpdateCodeCompletionOptions(true); code.SetCodeCompletionSelectedIndex(1); code.SetCaretColumn(2); Check(code.GetCodeCompletionSelectedIndex() == 1, "quoted candidates preserve selection when ordered display prefix stays equal"); code.CancelCodeCompletion();
        code.Text = "print"; code.SetCaretColumn(5); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "print", "print"); code.UpdateCodeCompletionOptions(false); Check(code.GetCodeCompletionSelectedIndex() == -1, "perfect completion cancels");
        using (var custom = new FilteredCode { Text = "pri" }) { custom.SetCaretColumn(3); custom.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Keyword, "else", "else"); custom.UpdateCodeCompletionOptions(false); custom.ConfirmCodeCompletion(); Check(custom.Text == "prielse", "override owns empty insertion prefix"); }
        code.Text = "# one\n# two\nroot:\n    child\n\nafter"; code.AddCommentDelimiter("#", ""); Check(code.CanFoldLine(0) && !code.CanFoldLine(1), "single-line comment block"); code.FoldLine(0); Check(!code.CanFoldLine(0), "folded header cannot fold again"); code.UnfoldAllLines(); code.FoldLine(2); Check(code.GetPosAtLineColumn(4, 0) != new Vector2i(-1, -1), "fold excludes trailing blank"); code.InsertLineAt(0, "before"); Check(code.IsLineFolded(3) && code.GetPosAtLineColumn(4, 0) == new Vector2i(-1, -1), "fold header identity shifts"); code.UnfoldAllLines();
        code.Text = "a\nb"; code.SelectAll(); code.CreateCodeRegion(); Check(code.Text.StartsWith("#region New Code Region\n", StringComparison.Ordinal) && code.IsLineFolded(0) && code.GetSelectedText() == "New Code Region", "named folded region creation"); code.Text = "a\nb"; code.SetCaretLine(1); code.DuplicateSelection(); Check(code.Text == "a\nb\nb" && code.GetCaretLine() == 2, "duplicate selection line caret follows copy"); code.Editable = false; code.DeleteLines(); Check(code.Text == "a\nb", "explicit document editing on read-only widget"); code.Editable = true;
        code.Text = "a\nb\nc"; code.SetCaretLine(2); code.AddCaret(0, 0); Check(code.GetLineRangesFromCarets(false, false).SequenceEqual(new[] { new Vector2i(0, 0), new Vector2i(2, 2) }), "unselected line ranges use sorted current positions"); code.AddCaret(0, 1); Check(code.GetLineRangesFromCarets(false, false).Length == 2, "overlapping ranges merge independently of adjacent policy"); code.RemoveSecondaryCarets();
        var matcher = typeof(CodeEdit).GetMethod("FindBraceMatch", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)!; bool Match(int line, int column, Vector2i expected) { object?[] args = [line, column, null, null, null]; return (bool)matcher.Invoke(code, args)! && (Vector2i)args[3]! == expected; }
        code.Text = "(\n  (\")\") # )\n)"; Check(Match(0, 1, new(0, 2)) && Match(2, 0, new(0, 0)), "nested multiline brace match ignores strings/comments"); code.Text = "("; Check(Match(0, 1, new(-1, -1)), "unmatched brace");
        using (var reentrant = new CallbackCode { Text = "x" }) { var calls = 0; reentrant.Filter = options => { if (calls++ == 0) { reentrant.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Keyword, "second", "second"); reentrant.UpdateCodeCompletionOptions(true); } return options; }; reentrant.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Keyword, "first", "first"); reentrant.UpdateCodeCompletionOptions(true); Check(reentrant.GetCodeCompletionOption(0)?.DisplayText == "second" && calls == 2, "reentrant filter settles newest queue"); reentrant.Filter = options => { reentrant.CancelCodeCompletion(); return options; }; reentrant.UpdateCodeCompletionOptions(true); Check(reentrant.GetCodeCompletionSelectedIndex() == -1, "filter cancellation stays canceled"); }
        using (var failed = new CodeEdit { Text = "a\nb" }) { failed.SetLineAsBreakpoint(0, true); failed.SetLineAsBreakpoint(1, true); failed.BreakpointToggled += _ => throw new InvalidOperationException("observer"); try { failed.ClearBreakpointedLines(); throw new Exception("missing observer exception"); } catch (AggregateException error) { Check(error.InnerExceptions.Count == 2 && failed.GetBreakpointedLines().Length == 0, "marker clear continues after observer failures"); } }
        var root = new Root(); var input = new CodeEdit { Text = "p", Size = new(200, 160), CodeCompletionEnabled = true }; root.AddChild(input); using var scene = new SceneTree(root); scene.FlushDeferred(); input.GrabFocus(); input.SetCaretColumn(1); var requested = 0; input.CodeCompletionRequested += () => requested++; scene.DispatchCommittedText(root, "r"); Check(requested == 1, "automatic completion producer"); input.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "print", "print"); input.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "private", "private"); input.UpdateCodeCompletionOptions(true); InputMap.ActionEraseEvents("ui_down"); using var binding = new InputEventKey { Keycode = Key.F8 }; InputMap.ActionAddEvent("ui_down", binding); using (var key = new InputEventKey { Keycode = Key.F8, Pressed = true }) root.PushInput(key, true); Check(input.GetCodeCompletionSelectedIndex() == 1, "remapped completion navigation index=" + input.GetCodeCompletionSelectedIndex() + " text=" + input.Text + " options=" + input.GetCodeCompletionOptions().Length); InputMap.LoadFromProjectSettings();
    }
    private static void Symbols()
    {
        var root = new Root(); var code = new CodeEdit { Text = "actor", Size = new(200, 120), SymbolLookupOnClick = true, SymbolTooltipOnHover = true }; root.AddChild(code); using var scene = new SceneTree(root); scene.FlushDeferred(); var validated = 0; var hovered = 0; var lookedUp = 0; code.SymbolValidate += word => { Check(word == "actor", "validated pointer word"); validated++; code.SetSymbolLookupWordAsValid(true); }; code.SymbolHovered += (word, line, column) => { Check(word == "actor" && line == 0 && column >= 0, "hover symbol coordinates"); hovered++; }; code.SymbolLookup += (word, line, column) => { Check(word == "actor" && line == 0 && column >= 0, "lookup symbol coordinates"); lookedUp++; }; var timer = code.GetNode<Electron2D.Timer>("_symbol_tooltip"); timer.WaitTime = .001; try { timer.Dispose(); throw new Exception("owned timer disposal accepted"); } catch (InvalidOperationException) { }
        var point = (Vector2)code.GetPosAtLineColumn(0, 1) + new Vector2(1, 2); using (var motion = new InputEventMouseMotion { Position = point, ControlPressed = true }) root.PushInput(motion, true); scene.ProcessFrame(.01); using (var click = new InputEventMouseButton { Position = point, ButtonIndex = MouseButton.Left, Pressed = true, ControlPressed = true }) root.PushInput(click, true); Check(validated == 1 && hovered == 1 && lookedUp == 1 && code.MouseDefaultCursorShape == CursorShape.IBeam && code.GetCursorShape(point) == CursorShape.PointingHand && code.GetTextForSymbolLookup().Contains('\uffff'), "routed symbol validation, owned timer and lookup workflow");
    }
    private static void Storage()
    { using var code = new CodeEdit { Text = "saved", IndentSize = 2, IndentUseSpaces = true, GuttersDrawLineNumbers = true, LineFolding = true, CodeCompletionEnabled = true, LineLengthGuidelines = [40, 80] }; code.AddCommentDelimiter("#", ""); using var packed = new PackedScene(); packed.Pack(code); using var copy = (CodeEdit)packed.Instantiate(); Check(copy.Text == "saved" && copy.IndentSize == 2 && copy.IndentUseSpaces && copy.GuttersDrawLineNumbers && copy.HasCommentDelimiter("#") && copy.LineLengthGuidelines.SequenceEqual(new[] { 40, 80 }), "stored code configuration"); var path = Path.Combine(Path.GetTempPath(), "e2d-code-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(packed, path); var start = new System.Diagnostics.ProcessStartInfo(Environment.ProcessPath!) { RedirectStandardOutput = true, RedirectStandardError = true }; if (Path.GetFileNameWithoutExtension(Environment.ProcessPath) == "dotnet") start.ArgumentList.Add(typeof(CodeEditTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_CODE_EDIT"); start.Environment.Remove("ELECTRON2D_TEST_CODE_EDIT_HOST"); start.Environment["ELECTRON2D_TEST_CODE_EDIT_CHILD"] = path; using var process = System.Diagnostics.Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("fresh code scene"); } Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh CodeEdit scene passed"), error.GetAwaiter().GetResult()); } finally { File.Delete(path); } }
    internal static void RunChild(string path) { using var packed = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); using var code = (CodeEdit)packed.Instantiate(); Check(code.Text == "saved" && code.IndentSize == 2 && code.IndentUseSpaces && code.GuttersDrawLineNumbers && code.HasCommentDelimiter("#") && code.AutoBraceCompletionPairs["("] == ")", "fresh configuration codecs"); code.SetCaretColumn(5); code.DoIndent(); Check(code.Text == "saved ", "fresh executable indentation"); Console.WriteLine("Fresh CodeEdit scene passed"); }
    internal static void RunHost()
    {
        Run(); var backend = Environment.GetEnvironmentVariable("ELECTRON2D_CODE_RENDERER") ?? "gpu"; var previous = ProjectSettings.Get(ProjectSettings.RenderingMethod); ProjectSettings.Set(ProjectSettings.RenderingMethod, backend); try { Pixels(); Warm(); Warm(true); } finally { ProjectSettings.Set(ProjectSettings.RenderingMethod, previous); }
        Console.WriteLine("CodeEdit native rendering/input passed (" + backend + ").");
    }
    private static CodeEdit NativeCode()
    {
        var code = new CodeEdit { Size = new(480, 260), Text = "#region actor\nfunc actor():\n    print(\"hello\")\n#endregion\n\npri", GuttersDrawLineNumbers = true, GuttersDrawBreakpointsGutter = true, GuttersDrawBookmarks = true, GuttersDrawFoldGutter = true, GuttersDrawExecutingLines = true, LineFolding = true, AutoBraceCompletionHighlightMatching = true, CodeCompletionEnabled = true, LineLengthGuidelines = [30, 40] }; code.AddCommentDelimiter("#", ""); code.SetLineAsBreakpoint(2, true); code.SetLineAsBookmarked(1, true); code.SetLineAsExecuting(2, true); return code;
    }
    private sealed class DrawGuardStyle(CodeEdit code) : StyleBox
    {
        internal bool Rejected;
        protected override void OnDraw(CanvasItem canvas, Rect2 rect) { try { code.Text = "invalid drawing mutation"; throw new Exception("drawing mutation accepted"); } catch (InvalidOperationException) { Rejected = true; } }
    }
    private static void Pixels()
    {
        var window = new Window { Size = new(500, 280) }; var code = NativeCode(); using var highlighter = new CodeHighlighter { FunctionColor = new(.9f, .9f, .9f), SymbolColor = new(.8f, .8f, .8f), NumberColor = new(.9f, .7f, .3f), MemberVariableColor = new(.8f, .9f, 1) }; highlighter.AddKeywordColor("func", new(.3f, .8f, 1)); highlighter.AddColorRegion("\"", "\"", new(.9f, .7f, .3f)); code.SyntaxHighlighter = highlighter; using var guard = new DrawGuardStyle(code); code.AddThemeStyleBoxOverride("completion", guard); window.AddChild(code); var phase = 0;
        window.Ready += _ => { code.GrabFocus(); code.SetCaretLine(5); code.SetCaretColumn(3); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "print", "print"); code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "private", "private"); code.UpdateCodeCompletionOptions(true); code.SetCodeHint("print(\uffffmessage\uffff)"); RenderingServer.FramePostDraw += () => { using var pixels = RenderingServer.Service!.Readback(); var colored = 0; var ink = 0; for (var y = 0; y < 260; y++) for (var x = 0; x < 480; x++) { var color = pixels.GetPixel(x, y); if (color.R > .65 && color.G < .4 || color.B > .6 && color.R < .7) colored++; if (color.R > .5 && color.G > .5 && color.B > .5) ink++; } if (phase == 0) { Check(colored > 0 && ink > 0 && guard.Rejected, "actual marker/glyph/completion pixels and inherited drawing guard"); if (Environment.GetEnvironmentVariable("ELECTRON2D_CODE_CAPTURE") is { } path) pixels.SavePNG(path); var native = SDL3.SDL.GetWindows(out var count)![0]; var key = new SDL3.SDL.Event { Key = new SDL3.SDL.KeyboardEvent { Type = SDL3.SDL.EventType.KeyDown, WindowID = SDL3.SDL.GetWindowID(native), Key = SDL3.SDL.Keycode.Return, Scancode = SDL3.SDL.Scancode.Return, Down = true } }; Check(SDL3.SDL.PushEvent(ref key), "queue completion Enter"); } else if (phase == 1) { Check(code.GetLine(5) == "print", "native completion commit"); code.FoldLine(0); } else if (phase == 2) { Check(code.GetPosAtLineColumn(2, 0) == new Vector2i(-1, -1), "native folded line hides"); code.UnfoldAllLines(); } else { window.Tree!.Quit(); } phase++; }; }; Check(Engine.Run(window) == 0 && phase == 4, "native code lifecycle");
    }
    private static void Warm(bool completion = false)
    {
        var window = new Window { Size = new(500, 280) }; var code = NativeCode(); window.AddChild(code); var frame = 0; long before = 0, total = 0; window.Ready += _ => { code.GrabFocus(); if (completion) { code.SetCaretLine(5); code.SetCaretColumn(3); for (var i = 0; i < 12; i++) code.AddCodeCompletionOption(CodeEdit.CodeCompletionKind.Function, "print" + i, "print" + i); code.UpdateCodeCompletionOptions(true); } RenderingServer.FramePreDraw += () => before = GC.GetAllocatedBytesForCurrentThread(); RenderingServer.FramePostDraw += () => { var after = GC.GetAllocatedBytesForCurrentThread(); if (frame >= 64) total += after - before; if (completion) code.SetCodeCompletionSelectedIndex(frame % 12); else { code.Select(2, 9, 2, frame % 2 + 10); } if (frame >= 64) total += GC.GetAllocatedBytesForCurrentThread() - after; if (++frame == 128) window.Tree!.Quit(); }; }; Check(Engine.Run(window) == 0 && total == 0, "prepared code bytes " + total); Console.WriteLine("64 prepared CodeEdit caret/selection/render intervals: " + total + " managed bytes.");
    }
    private static void Check(bool value, string message) { if (!value) throw new Exception("CodeEdit: " + message); }
}
