using Electron2D;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Text;
using Path = System.IO.Path;
using Certificate = Electron2D.X509Certificate;

internal static class CryptoTests
{
    internal static void Run() { Digests(); Blocks(); KeysAndCertificate(); Console.WriteLine("Crypto hash/HMAC/AES vectors, RSA/EC/certificate resource and native TLS interoperability, lifecycle and prepared allocation checks passed."); }
    private static byte[] Bytes(string hex) => Convert.FromHexString(hex);
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
    private static void Wait(Func<bool> ready) { var deadline = Environment.TickCount64 + 10000; while (!ready()) { if (Environment.TickCount64 > deadline) throw new TimeoutException(); Thread.Sleep(1); } }
    private static void Digests()
    {
        using var crypto = new Crypto(); Span<byte> result = stackalloc byte[32];
        foreach (var (type, abc, empty) in new[] { (HashType.MD5, "900150983cd24fb0d6963f7d28e17f72", "d41d8cd98f00b204e9800998ecf8427e"), (HashType.SHA1, "a9993e364706816aba3e25717850c26c9cd0d89d", "da39a3ee5e6b4b0d3255bfef95601890afd80709"), (HashType.SHA256, "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855") })
        {
            using var context = new HashingContext(); Reject<InvalidOperationException>(() => context.Update("a"u8)); context.Start(type); Reject<InvalidOperationException>(() => context.Start(type)); Reject<ArgumentException>(() => context.Update([])); context.Update("a"u8); context.Update("bc"u8); Reject<ArgumentException>(() => context.Finish(new byte[1])); var count = context.Finish(result); Check(result[..count].SequenceEqual(Bytes(abc)), "Known abc digest and preserved undersized finish."); Reject<InvalidOperationException>(() => context.Finish()); context.Start(type); Check(context.Finish().SequenceEqual(Bytes(empty)), "Empty complete digest."); context.Start(type); for (var i = 0; i < 32; i++) context.Update("warm"u8); var before = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 64; i++) context.Update("warm"u8); Check(GC.GetAllocatedBytesForCurrentThread() == before, "Prepared digest Update allocates zero bytes."); before = GC.GetAllocatedBytesForCurrentThread(); context.Finish(result); Check(GC.GetAllocatedBytesForCurrentThread() == before, "Caller-span digest finish allocates zero managed bytes.");
            Reject<InvalidOperationException>(() => Task.Run(() => context.Start(type)).GetAwaiter().GetResult());
        }
        var key = Enumerable.Repeat((byte)0x0b, 20).ToArray();
        foreach (var (type, expected) in new[] { (HashType.SHA1, "b617318655057264e28bc0b6fb378c8ef146be00"), (HashType.SHA256, "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7") })
        {
            using var context = new HMACContext(); Reject<ArgumentException>(() => context.Start(type, [])); context.Start(type, key); Reject<InvalidOperationException>(() => context.Start(type, key)); context.Update("Hi "u8); context.Update("There"u8); Reject<ArgumentException>(() => context.Update([])); Reject<ArgumentException>(() => context.Finish(new byte[1])); Check(context.Finish().SequenceEqual(Bytes(expected)) && crypto.HMACDigest(type, key, "Hi There"u8).SequenceEqual(Bytes(expected)), "RFC HMAC vector and incremental/snapshot parity.");
            context.Start(type, key); for (var i = 0; i < 32; i++) context.Update("warm"u8); var before = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 64; i++) context.Update("warm"u8); Check(GC.GetAllocatedBytesForCurrentThread() == before, "Prepared HMAC updates allocate zero bytes."); context.Finish(result); context.Start(type, key); using (var oracle = IncrementalHash.CreateHMAC(type == HashType.SHA1 ? HashAlgorithmName.SHA1 : HashAlgorithmName.SHA256, key)) Check(context.Finish().SequenceEqual(oracle.GetHashAndReset()), "HMAC empty message through no-update finish.");
            var copied = key.ToArray(); context.Start(type, copied); Array.Clear(copied); context.Update("Hi There"u8); Check(context.Finish().SequenceEqual(Bytes(expected)), "Prepared HMAC owns key material.");
        }
        using var invalid = new HashingContext(); Reject<ArgumentOutOfRangeException>(() => invalid.Start((HashType)3)); using var hmac = new HMACContext(); Reject<NotSupportedException>(() => hmac.Start(HashType.MD5, key)); Reject<InvalidOperationException>(() => hmac.Finish()); Reject<ArgumentException>(() => crypto.HMACDigest(HashType.SHA256, key, []));
        Check(crypto.ConstantTimeCompare([], []) && crypto.ConstantTimeCompare("same"u8, "same"u8) && !crypto.ConstantTimeCompare("same"u8, "samp"u8) && !crypto.ConstantTimeCompare("a"u8, "aa"u8), "Fixed-time content comparison contract."); for (var i = 0; i < 32; i++) crypto.GenerateRandomBytes(result); var allocated = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 64; i++) { crypto.GenerateRandomBytes(result); Check(crypto.ConstantTimeCompare(result, result), "Prepared random/comparison."); }
        Check(GC.GetAllocatedBytesForCurrentThread() == allocated, "Random span/comparison allocates zero bytes."); var random = crypto.GenerateRandomBytes(4096); Check(random.Distinct().Count() > 200 && !random.SequenceEqual(crypto.GenerateRandomBytes(4096)) && crypto.GenerateRandomBytes(0).Length == 0, "Secure random size and independent sample."); Reject<ArgumentOutOfRangeException>(() => crypto.GenerateRandomBytes(-1)); Reject<InvalidOperationException>(() => Task.Run(crypto.Dispose).GetAwaiter().GetResult()); Check(!crypto.IsDisposed, "Crypto owner validation precedes disposal."); Console.WriteLine("64 prepared MD5/SHA1/SHA256, HMAC, random-span/comparison cycles: 0 managed bytes.");
    }
    private static void Blocks()
    {
        var plain = Bytes("6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710"); var iv = Bytes("000102030405060708090a0b0c0d0e0f"); Span<byte> state = stackalloc byte[16];
        foreach (var (keyHex, ecbHex, cbcHex) in new[] { ("2b7e151628aed2a6abf7158809cf4f3c", "3ad77bb40d7a3660a89ecaf32466ef97f5d3d58503b9699de785895a96fdbaaf43b1cd7f598ece23881b00e3ed0306887b0c785e27e8ad3f8223207104725dd4", "7649abac8119b246cee98e9b12e9197d5086cb9b507219ee95db113a917678b273bed6b8e3c1743b7116e69e222295163ff1caa1681fac09120eca307586e1a7"), ("603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4", "f3eed1bdb5d2a03c064b5a7e3db181f8591ccb10d410ed26dc5ba74a31362870b6ed21b99ca6f4f9f153e7b1beafed1d23304b7a39f9f3ff067d8d8f9e24ecc7", "f58c4c04d6e5f1ba779eabfb5f7bfbd69cfc4e967edb808d679f777bc6702c7d39f23369a9d9bacfa530e26304231461b2eb05e2c39be9fcda6c19078c6a9d1b") })
        {
            var key = Bytes(keyHex);
            foreach (var mode in new[] { AESMode.ECBEncrypt, AESMode.ECBDecrypt, AESMode.CBCEncrypt, AESMode.CBCDecrypt })
            {
                var cbc = mode is AESMode.CBCEncrypt or AESMode.CBCDecrypt; var decrypt = mode is AESMode.ECBDecrypt or AESMode.CBCDecrypt; var cipher = Bytes(cbc ? cbcHex : ecbHex); var input = decrypt ? cipher : plain; var expected = decrypt ? plain : cipher; using var context = new AESContext(); context.Start(mode, key, iv); Reject<InvalidOperationException>(() => context.Start(mode, key, iv)); var output = new byte[plain.Length]; context.Update(input.AsSpan(0, 16), output.AsSpan(0, 16)); context.Update(input.AsSpan(16, 32), output.AsSpan(16, 32)); context.Update(input.AsSpan(48), output.AsSpan(48)); Check(output.SequenceEqual(expected), "NIST AES 128/256 ECB/CBC vector and split chunks."); Reject<ArgumentException>(() => context.Update(input.AsSpan(0, 16), new byte[15]));
                if (cbc) { Check(context.GetIVState(state) == 16 && state.SequenceEqual(cipher.AsSpan(48)), "CBC IV tracks last ciphertext on encrypt/decrypt."); var copy = context.GetIVState(); copy[0] ^= 1; Check(!context.GetIVState().SequenceEqual(copy), "IV snapshot is owned."); Reject<ArgumentException>(() => context.Update(new byte[15])); Check(context.GetIVState().AsSpan().SequenceEqual(state), "Invalid update preserves IV."); } else Reject<InvalidOperationException>(() => context.GetIVState());
                var overlap = new byte[17]; Reject<ArgumentException>(() => context.Update(overlap.AsSpan(0, 16), overlap.AsSpan(1))); context.Finish(); var inPlace = input.ToArray(); context.Start(mode, key, iv); context.Update(inPlace, inPlace); Check(inPlace.SequenceEqual(expected), "Exact in-place update supports CBC decryption."); context.Finish(); context.Finish(); Reject<InvalidOperationException>(() => context.Update([]));
                context.Start(mode, key, iv); var scratch = new byte[64]; for (var i = 0; i < 32; i++) context.Update(input, scratch); var before = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 64; i++) { context.Update(input, scratch); if (cbc) context.GetIVState(state); }
                Check(GC.GetAllocatedBytesForCurrentThread() == before, "Prepared AES block/span/IV updates allocate zero managed bytes."); context.Finish(); Reject<InvalidOperationException>(() => Task.Run(context.Dispose).GetAwaiter().GetResult());
            }
        }
        using var invalid = new AESContext(); Reject<ArgumentOutOfRangeException>(() => invalid.Start(AESMode.Max, new byte[16])); Reject<ArgumentException>(() => invalid.Start(AESMode.ECBEncrypt, new byte[24])); Reject<ArgumentException>(() => invalid.Start(AESMode.CBCEncrypt, new byte[16])); invalid.Start(AESMode.ECBEncrypt, new byte[16]); Check(invalid.Update([]).Length == 0, "Empty AES update is valid."); Console.WriteLine("64 prepared AES-128/256 ECB/CBC encrypt/decrypt span/IV cycles: 0 managed bytes.");
    }
    private static void KeysAndCertificate()
    {
        using var crypto = new Crypto(); using var key = crypto.GenerateRSA(2048); using var pub = new CryptoKey(); pub.LoadFromString(key.SaveToString(true), true); using var rsa = RSA.Create(); rsa.ImportFromPem(key.SaveToString()); var data = "game payload"u8.ToArray();
        foreach (var (type, name) in new[] { (HashType.MD5, HashAlgorithmName.MD5), (HashType.SHA1, HashAlgorithmName.SHA1), (HashType.SHA256, HashAlgorithmName.SHA256) })
        {
            using var hash = IncrementalHash.CreateHash(name); hash.AppendData(data); var digest = hash.GetHashAndReset(); var signature = crypto.Sign(type, digest, key); Check(signature.SequenceEqual(rsa.SignHash(digest, name, RSASignaturePadding.Pkcs1)) && crypto.Verify(type, digest, signature, pub), "Independent RSA PKCS1 digest-signature wire."); signature[0] ^= 1; Check(!crypto.Verify(type, digest, signature, pub) && !crypto.Verify(type, digest, [], pub), "Signature corruption rejects."); Reject<ArgumentException>(() => crypto.Sign(type, new byte[1], key)); Reject<CryptographicException>(() => crypto.Sign(type, digest, pub));
        }
        var encrypted = crypto.Encrypt(pub, data); Check(encrypted.Length == 256 && rsa.Decrypt(encrypted, RSAEncryptionPadding.Pkcs1).SequenceEqual(data) && crypto.Decrypt(key, rsa.Encrypt(data, RSAEncryptionPadding.Pkcs1)).SequenceEqual(data), "Bidirectional RSA encryption oracle."); var maximum = new byte[245]; Check(crypto.Decrypt(key, crypto.Encrypt(pub, maximum)).SequenceEqual(maximum), "RSA maximum padded plaintext."); Reject<CryptographicException>(() => crypto.Encrypt(pub, new byte[246])); Reject<CryptographicException>(() => crypto.Decrypt(key, new byte[255])); Reject<CryptographicException>(() => crypto.Decrypt(pub, encrypted)); Check(crypto.Decrypt(key, crypto.Encrypt(pub, [])).Length == 0, "RSA empty plaintext.");
        using var ec = ECDsa.Create(ECCurve.NamedCurves.nistP256); using var ecKey = new CryptoKey(); ecKey.LoadFromString(ec.ExportPkcs8PrivateKeyPem()); using var ecPub = new CryptoKey(); ecPub.LoadFromString(ecKey.SaveToString(true), true); var sha = SHA256.HashData(data); var ecSignature = crypto.Sign(HashType.SHA256, sha, ecKey); Check(ec.VerifyHash(sha, ecSignature, DSASignatureFormat.Rfc3279DerSequence) && crypto.Verify(HashType.SHA256, sha, ec.SignHash(sha, DSASignatureFormat.Rfc3279DerSequence), ecPub), "Bidirectional EC DER digest-signature wire."); Check(!crypto.Verify(HashType.SHA256, sha, new byte[] { 1, 2, 3 }, ecPub), "Malformed EC DER returns false."); Reject<NotSupportedException>(() => crypto.Encrypt(ecKey, data));
        using var certificate = crypto.GenerateSelfSignedCertificate(key, "CN=localhost,O=Electron2D,C=RU"); using var parsed = X509CertificateLoader.LoadCertificate(Encoding.ASCII.GetBytes(certificate.SaveToString())); Check(parsed.SubjectName.RawData.SequenceEqual(parsed.IssuerName.RawData) && parsed.Version == 3 && parsed.SignatureAlgorithm.Value == "1.2.840.113549.1.1.11" && parsed.GetNameInfo(X509NameType.SimpleName, false) == "localhost", "Self-signed X509 subject/issuer/version/signature."); var basic = parsed.Extensions.OfType<X509BasicConstraintsExtension>().Single(); Check(basic.CertificateAuthority && basic.HasPathLengthConstraint && basic.PathLengthConstraint == 0 && parsed.NotBefore.ToUniversalTime().Year == 2014 && parsed.NotAfter.ToUniversalTime().Year == 2034 && parsed.GetSerialNumber().Length is > 0 and <= 20, "Certificate CA/path/UTC/default/serial contract."); using var ecCertificate = crypto.GenerateSelfSignedCertificate(ecKey, "CN=localhost,O=Electron2D,C=RU");
        Reject<ArgumentException>(() => crypto.GenerateSelfSignedCertificate(key, "CN=localhost")); Reject<ArgumentException>(() => crypto.GenerateSelfSignedCertificate(key, "CN=localhost,O=Electron2D,C=RUS")); Reject<ArgumentException>(() => crypto.GenerateSelfSignedCertificate(key, notBefore: "20260230000000")); Reject<ArgumentException>(() => crypto.GenerateSelfSignedCertificate(key, notBefore: "invalid")); Reject<ArgumentException>(() => crypto.GenerateSelfSignedCertificate(key, notBefore: "20340101000000", notAfter: "20140101000000")); Reject<CryptographicException>(() => crypto.GenerateSelfSignedCertificate(pub));
        var directory = Path.Combine(Path.GetTempPath(), "e2d-crypto-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(directory);
        try { var keyPath = Path.Combine(directory, "generated.key"); var certPath = Path.Combine(directory, "generated.crt"); key.Save(keyPath); certificate.Save(certPath); using var loadedKey = ResourceLoader.Load<CryptoKey>(keyPath, ResourceLoader.CacheMode.Ignore); using var loadedCert = ResourceLoader.Load<Certificate>(certPath, ResourceLoader.CacheMode.Ignore); Check(crypto.Decrypt(loadedKey, crypto.Encrypt(pub, data)).SequenceEqual(data) && loadedCert.SaveToString() == certificate.SaveToString(), "Generated resources use existing typed loader/save paths."); } finally { Directory.Delete(directory, true); }
        NativeCertificate(crypto, key, certificate, parsed); using var disposed = new CryptoKey(); disposed.Dispose(); Reject<ObjectDisposedException>(() => crypto.Encrypt(disposed, data)); Reject<InvalidOperationException>(() => Task.Run(() => crypto.GenerateRandomBytes(1)).GetAwaiter().GetResult());
    }
    private static void NativeCertificate(Crypto crypto, CryptoKey key, Certificate certificate, X509Certificate2 publicCertificate)
    {
        using var stop = new CancellationTokenSource(10000); using var listener = new TCPServer(); listener.Listen(0, "127.0.0.1"); var port = listener.GetLocalPort();
        var oracle = Task.Run(async () => { using var socket = new TcpClient(); await socket.ConnectAsync(IPAddress.Loopback, port, stop.Token); using var ssl = new SslStream(socket.GetStream(), false); var policy = new X509ChainPolicy { TrustMode = X509ChainTrustMode.CustomRootTrust, RevocationMode = X509RevocationMode.NoCheck }; policy.CustomTrustStore.Add(publicCertificate); await ssl.AuthenticateAsClientAsync(new SslClientAuthenticationOptions { TargetHost = "localhost", CertificateChainPolicy = policy, EnabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Tls13 }, stop.Token); await ssl.WriteAsync("generated"u8.ToArray(), stop.Token); var response = new byte[2]; await ssl.ReadExactlyAsync(response, stop.Token); Check(response.AsSpan().SequenceEqual("OK"u8), "Independent TLS client trusts generated key/certificate."); });
        Wait(listener.IsConnectionAvailable); using var tcp = listener.TakeConnection()!; using var options = TLSOptions.Server(key, certificate); using var tls = new StreamPeerTLS(); tls.AcceptStream(tcp, options); Wait(() => { tls.Poll(); return tls.GetStatus() == TLSStatus.Connected; }); var digest = SHA256.HashData("retained"u8); Check(crypto.Verify(HashType.SHA256, digest, crypto.Sign(HashType.SHA256, digest, key), key), "Crypto snapshots work while TLS retains the same resource."); Reject<InvalidOperationException>(key.Dispose); Reject<InvalidOperationException>(certificate.Dispose); var received = new byte[9]; var count = 0; Wait(() => { tls.Poll(); count += tls.GetPartialData(received.AsSpan(count)); return count == received.Length; }); Check(received.AsSpan().SequenceEqual("generated"u8), "Generated TLS native data."); tls.PutData("OK"u8); oracle.GetAwaiter().GetResult();
    }
}
