using Electron2D;

internal static class DialogTests
{
    internal static void Run()
    {
        Reject<InvalidOperationException>(() => DisplayServer.GetSwapCancelOK());
        using var defaults = new AcceptDialog(); Check(!defaults.Visible && defaults.Transient && defaults.Exclusive && defaults.WrapControls && defaults.KeepTitleVisible && defaults.MinimizeDisabled && defaults.MaximizeDisabled && !defaults.Borderless && !defaults.PopupWindow && defaults.Title == "Alert!", "Dialog window defaults.");
        Check(defaults.DialogText == "" && !defaults.DialogAutowrap && defaults.DialogHideOnOK && defaults.DialogCloseOnEscape && defaults.OKButtonText == "" && defaults.GetOKButton().Text == "OK" && defaults.ChildCount == 0 && defaults.GetChildCount(true) == 3, "Owned controls and acceptance defaults.");
        defaults.OKButtonText = "Proceed"; defaults.OKButtonText = ""; Check(defaults.GetOKButton().Text == "OK", "Empty OK override restores default."); Reject<ArgumentNullException>(() => defaults.AddButton(null!)); Reject<ArgumentException>(() => defaults.RemoveButton(defaults.GetOKButton()));
        try { ProjectSettings.Set(ProjectSettings.SwapCancelOK, 2); using var ordered = new ConfirmationDialog(); var host = new SubViewport { Size = new(500, 250), GUIEmbedSubwindows = true }; host.AddChild(ordered); using var orderedTree = new SceneTree(host); ordered.PopupCentered(); orderedTree.ProcessFrame(.01); Check(ordered.GetCancelButton().Position.X > ordered.GetOKButton().Position.X, "Explicit OK-first project order."); Reject<ArgumentOutOfRangeException>(() => ProjectSettings.Set(ProjectSettings.SwapCancelOK, 3)); } finally { ProjectSettings.Set(ProjectSettings.SwapCancelOK, 0); }
        using var titleWindow = new Window { Borderless = true, KeepTitleVisible = true, Title = new string('W', 40), Size = new(100, 100) }; Check(titleWindow.Size.X == 100, "Borderless windows need no title width."); titleWindow.Borderless = false; Check(titleWindow.Size.X > 100, "Enabling decorations restores the actual title minimum."); titleWindow.MaxSize = new(200, 200); Check(titleWindow.Size.X == 200, "Title minimum respects changed maximum.");
        var root = new SubViewport { Size = new(640, 360), GUIEmbedSubwindows = true }; var dialog = new ObservedDialog { DialogText = "Confirm the operation", Name = "Dialog" }; root.AddChild(dialog); using var tree = new SceneTree(root); tree.ProcessFrame(.01);
        var order = dialog.Order; dialog.Confirmed += () => order.Add("confirmed:" + dialog.Visible); dialog.Canceled += () => order.Add("canceled:" + dialog.Visible); dialog.CustomAction += action => order.Add("custom:" + action);
        dialog.PopupCentered(new(340, 180)); tree.ProcessFrame(.01); Check(dialog.GetOKButton().HasFocus() && dialog.HasFocus(), "Shown dialog focuses OK in its embedded viewport."); ActionKey(root, "ui_accept"); Check(!dialog.Visible && order.SequenceEqual(new[] { "OK:False", "confirmed:False" }), "Hide, OK hook, confirmed order.");
        order.Clear(); dialog.DialogHideOnOK = false; dialog.PopupCentered(); ActionKey(root, "ui_accept"); Check(dialog.Visible && order.SequenceEqual(new[] { "OK:True", "confirmed:True" }), "Validation can retain visibility.");
        order.Clear(); ActionKey(root, "ui_cancel"); Check(dialog.Visible && order.Count == 0, "ui_cancel is independent of close action."); ActionKey(root, "ui_close_dialog"); Check(dialog.Visible && order.SequenceEqual(new[] { "canceled:True", "cancel:True" }), "Cancel events precede deferred hiding."); tree.ProcessFrame(.01); Check(!dialog.Visible, "Cancellation hides after deferred phase.");
        dialog.PopupCentered(); dialog.DialogCloseOnEscape = false; SendKey(root, Key.Escape); Check(dialog.Visible, "Close on escape gate."); dialog.DialogCloseOnEscape = true; SendKey(root, Key.Escape, true); Check(dialog.Visible, "Echoed Escape does not cancel."); SendKey(root, Key.Escape); tree.ProcessFrame(.01); Check(!dialog.Visible, "Default Escape maps to close action.");
        var left = dialog.AddButton("Help", action: "help"); var right = dialog.AddButton("Other", true, "other"); var cancel = dialog.AddCancelButton(""); dialog.PopupCentered(new(400, 200)); tree.ProcessFrame(.01); Check(left.Position.X < dialog.GetOKButton().Position.X && right.Position.X > dialog.GetOKButton().Position.X && cancel.Text == "Cancel", "Action button ordering and cancel caption."); order.Clear(); Click(root, (Vector2)dialog.Position + left.GetGlobalRect().GetCenter()); Check(dialog.Visible && order.SequenceEqual(new[] { "custom:help", "hook:help" }), "Pointer custom event/hook with no implicit hide.");
        var row = (Control)left.Parent!; var width = row.GetCombinedMinimumSize().X; left.Hide(); tree.ProcessFrame(.01); Check(row.GetCombinedMinimumSize().X < width, "Hidden buttons hide their paired spacers."); left.Show(); dialog.RemoveButton(left); Check(left.Parent == null && !left.IsDisposed, "Removal transfers button ownership."); root.AddChild(left); left.Position = new(0, 0); left.Size = new(60, 40); dialog.Hide(); order.Clear(); Click(root, left.GetGlobalRect().GetCenter()); Check(order.Count == 0, "Removed button has no dialog callbacks."); Reject<ArgumentException>(() => dialog.RemoveButton(left)); right.Dispose(); tree.ProcessFrame(.01);
        var edit = new LineEdit { Text = "Submitted" }; dialog.AddChild(edit); dialog.RegisterTextEnter(edit); dialog.RegisterTextEnter(edit); dialog.PopupCentered(); tree.ProcessFrame(.01); edit.GrabFocus(); dialog.GetOKButton().Disabled = true; order.Clear(); SendKey(root, Key.Enter); Check(order.Count == 0 && dialog.Visible, "Disabled OK prevents registered submission."); dialog.GetOKButton().Disabled = false; dialog.DialogHideOnOK = true; edit.GrabFocus(); edit.Edit(); SendKey(root, Key.Enter); Check(order.SequenceEqual(new[] { "OK:False", "confirmed:False" }) && !dialog.Visible, "Registered Enter confirms once: " + string.Join(",", order) + " visible=" + dialog.Visible); edit.Dispose();
        using var style = new StyleBoxFlat(); style.SetContentMarginAll(12); dialog.AddThemeStyleBoxOverride("panel", style); dialog.AddThemeConstantOverride("buttons_min_width", 80); dialog.AddThemeConstantOverride("buttons_min_height", 45); dialog.AddThemeConstantOverride("buttons_separation", 17); dialog.DialogAutowrap = true; dialog.DialogText = "Long words wrap into a narrower area when the dialog is resized."; dialog.PopupCentered(new(350, 220)); tree.ProcessFrame(.01); Check(dialog.GetOKButton().CustomMinimumSize == new Vector2(80, 45) && dialog.GetLabel().Position == new Vector2(12, 12) && dialog.GetContentsMinimumSize().Y >= 24 + 45 + 17, "Live panel/button theme geometry.");
        dialog.Title = new string('W', 60); Check(dialog.Size.X > 350, "Keep title visible expands embedded width."); dialog.KeepTitleVisible = false; dialog.Position = new(-100, -100); Check(dialog.Position.X >= 0 && dialog.Position.Y >= 36, "Dialog geometry includes title when clamped to embedder.");
        Reject<InvalidOperationException>(() => Task.Run(() => dialog.DialogText = "wrong owner").GetAwaiter().GetResult()); Reentrancy(); Packing(); dialog.RemoveThemeStyleBoxOverride("panel"); Console.WriteLine("AcceptDialog/ConfirmationDialog defaults, actions, input, text, ownership, themes, reentrancy and fresh scenes passed.");
    }
    private sealed class ObservedDialog : AcceptDialog
    {
        internal readonly List<string> Order = [];
        protected override void OnOKPressed() => Order.Add("OK:" + Visible);
        protected override void OnCancelPressed() => Order.Add("cancel:" + Visible);
        protected override void OnCustomAction(string action) => Order.Add("hook:" + action);
    }
    private static void Reentrancy()
    {
        var root = new SubViewport { Size = new(400, 240), GUIEmbedSubwindows = true }; var dialog = new ObservedDialog(); root.AddChild(dialog); using var tree = new SceneTree(root); tree.ProcessFrame(.01);
        Action reopen = () => dialog.PopupCentered(); dialog.Canceled += reopen; dialog.PopupCentered(); ActionKey(root, "ui_close_dialog"); tree.ProcessFrame(.01); Check(dialog.Visible, "Reopening from canceled supersedes queued old hide."); dialog.Canceled -= reopen;
        var row = dialog.GetOKButton().Parent!; Action<Node> structuralFailure = _ => throw new InvalidOperationException("row observer"); row.ChildOrderChanged += structuralFailure;
        Reject<AggregateException>(() => dialog.AddButton("Committed action", action: "committed")); row.ChildOrderChanged -= structuralFailure;
        var inserted = (Button)row.GetChildren().Single(n => n is Button b && b != dialog.GetOKButton()); Check(inserted.Parent == row, "Insertion commits a live action despite row observer failure.");
        row.ChildOrderChanged += structuralFailure; Reject<AggregateException>(() => dialog.RemoveButton(inserted)); row.ChildOrderChanged -= structuralFailure; Check(inserted.Parent == null && !inserted.IsDisposed, "Removal completes ownership transfer after spacer/detach observer failure."); inserted.Dispose();
        Action failure = () => throw new InvalidOperationException("observer"); dialog.Canceled += failure; Reject<AggregateException>(() => ActionKey(root, "ui_close_dialog")); Check(dialog.Order.Contains("cancel:True"), "Cancel hook continues after subscriber failure."); tree.ProcessFrame(.01); Check(!dialog.Visible, "Failed cancel observers still hide."); dialog.Canceled -= failure;
        dialog.Confirmed += reopen; dialog.PopupCentered(); ActionKey(root, "ui_accept"); Check(dialog.Visible, "Confirmed handler can reopen after committed hide."); dialog.Confirmed -= reopen;
        var confirmed = false; dialog.Confirmed += () => confirmed = true; dialog.VisibilityChanged += () => { if (!dialog.Visible) throw new InvalidOperationException("hide observer"); }; Reject<AggregateException>(() => ActionKey(root, "ui_accept")); Check(confirmed && !dialog.Visible, "Hide observer failure still delivers confirmation.");
    }
    private static void Packing()
    {
        using var source = new ConfirmationDialog { Name = "StoredDialog", DialogText = "Saved confirmation", OKButtonText = "Apply", CancelButtonText = "Back", DialogAutowrap = true, DialogHideOnOK = false, DialogCloseOnEscape = false }; using var scene = new PackedScene(); scene.Pack(source); using var copy = (ConfirmationDialog)scene.Instantiate(); Check(copy.GetCancelButton() != source.GetCancelButton() && copy.CancelButtonText == "Back" && copy.GetOKButton().Text == "Apply" && copy.DialogText == "Saved confirmation" && copy.ChildCount == 0 && copy.GetChildCount(true) == 3 && copy.MinSize == new Vector2i(200, 70), "Scene restores policies and independent owned controls.");
        var path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "electron2d-dialog-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(scene, path); var start = new System.Diagnostics.ProcessStartInfo(Environment.ProcessPath!) { RedirectStandardOutput = true, RedirectStandardError = true }; if (System.IO.Path.GetFileNameWithoutExtension(Environment.ProcessPath) == "dotnet") start.ArgumentList.Add(typeof(DialogTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_DIALOG"); start.Environment["ELECTRON2D_TEST_DIALOG_CHILD"] = path; using var process = System.Diagnostics.Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("Dialog fresh process."); } Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh dialog scene passed"), "Fresh dialog: " + error.GetAwaiter().GetResult()); } finally { File.Delete(path); }
    }
    internal static void RunChild(string path)
    {
        using var scene = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); var dialog = (ConfirmationDialog)scene.Instantiate(); var root = new SubViewport { Size = new(500, 300), GUIEmbedSubwindows = true }; root.AddChild(dialog); using var tree = new SceneTree(root); tree.ProcessFrame(.01); Check(dialog.CancelButtonText == "Back" && dialog.DialogAutowrap && !dialog.DialogHideOnOK && !dialog.DialogCloseOnEscape && dialog.GetOKButton().Text == "Apply", "Fresh dialog policies."); var confirmed = false; dialog.Confirmed += () => confirmed = true; dialog.PopupCentered(new(320, 160)); tree.ProcessFrame(.01); ActionKey(root, "ui_accept"); Check(confirmed && dialog.Visible, "Fresh real confirmation executes."); Click(root, (Vector2)dialog.Position + dialog.GetCancelButton().GetGlobalRect().GetCenter()); tree.ProcessFrame(.01); Check(!dialog.Visible, "Fresh cancel button executes."); Console.WriteLine("Fresh dialog scene passed");
    }
    private static void ActionKey(Viewport root, string action) { using var down = new InputEventAction { Action = action, Pressed = true }; using var up = new InputEventAction { Action = action }; root.PushInput(down, true); root.PushInput(up, true); }
    private static void SendKey(Viewport root, Key key, bool echo = false) { using var input = new InputEventKey { Keycode = key, Pressed = true, Echo = echo }; root.PushInput(input, true); }
    private static void Click(Viewport root, Vector2 position) { using var down = new InputEventMouseButton { Position = position, ButtonIndex = MouseButton.Left, Pressed = true }; using var up = new InputEventMouseButton { Position = position, ButtonIndex = MouseButton.Left }; root.PushInput(down, true); root.PushInput(up, true); }
    private static void Check(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
