using Electron2D;
using IOPath = System.IO.Path;

internal static class FileDialogTests
{
    internal static void Run()
    {
        using var temp = DirAccess.CreateTemp("electron2d-file-dialog"); var directory = temp.GetCurrentDir(); File.WriteAllText(IOPath.Combine(directory, "one.txt"), "one"); File.WriteAllText(IOPath.Combine(directory, "two.TXT"), "two"); File.WriteAllText(IOPath.Combine(directory, "skip.png"), "image"); File.WriteAllText(IOPath.Combine(directory, ".hidden.txt"), "hidden"); Directory.CreateDirectory(IOPath.Combine(directory, "folder"));
        var root = new SubViewport { Size = new(1100, 720), GUIEmbedSubwindows = true }; var dialog = new FileDialog { Name = "Picker", Access = FileDialogAccess.FileSystem, CurrentDir = directory, FileMode = FileDialogMode.OpenFile }; dialog.AddFilter("*.txt", "Text"); root.AddChild(dialog); using var tree = new SceneTree(root); tree.ProcessFrame(.01); dialog.PopupFileDialog(); tree.ProcessFrame(.01);
        var list = (ItemList)dialog.GetVBox().GetNode("Browser/Files"); Check(list.ItemCount == 3 && list.GetItemText(0) == "folder", "Scoped directory, file type and hidden filter execute."); var selected = ""; dialog.FileSelected += path => selected = path; dialog.CurrentFile = "one.txt"; dialog.GetOKButton().GrabFocus(); ActionKey(root, "ui_accept"); Check(selected == IOPath.Combine(directory, "one.txt") && !dialog.Visible, "Existing file validation emits after hide.");
        dialog.FileMode = FileDialogMode.SaveFile; dialog.CurrentFile = "created"; dialog.PopupFileDialog(); tree.ProcessFrame(.01); dialog.GetOKButton().GrabFocus(); ActionKey(root, "ui_accept"); Check(selected == IOPath.Combine(directory, "created.txt") && !File.Exists(selected), "Save appends selected extension and emits a destination without writing a file.");
        dialog.OptionCount = 2; dialog.SetOptionName(0, "Flag"); dialog.SetOptionDefault(0, 8); dialog.SetOptionName(1, "Quality"); dialog.SetOptionValues(1, ["Low", "High"]); dialog.SetOptionDefault(1, 1); dialog.PopupFileDialog(); tree.ProcessFrame(.01); var options = dialog.GetSelectedOptions(); Check(options["Flag"].IsCheckbox && options["Flag"].Checked && options["Quality"].SelectedIndex == 1, "Typed checkbox/index defaults build real controls.");
        var checkbox = (CheckBox)dialog.GetVBox().GetNode("Options/Checkbox0"); checkbox.GrabFocus(); ActionKey(root, "ui_accept"); var choice = (OptionButton)dialog.GetVBox().GetNode("Options/Choice1/Choice"); choice.ShowPopup(); ActionKey(root, "ui_up"); ActionKey(root, "ui_accept"); var changedOptions = dialog.GetSelectedOptions(); Check(!changedOptions["Flag"].Checked && changedOptions["Quality"].SelectedIndex == 0 && options["Flag"].Checked && options["Quality"].SelectedIndex == 1, "Live checkbox/choice input changes new results and preserves previous snapshots."); Reject<InvalidOperationException>(() => _ = changedOptions["Quality"].Checked); var copiedValues = dialog.GetOptionValues(1); copiedValues[0] = "mutated"; Check(dialog.GetOptionValues(1)[0] == "Low", "Option value getters return independent copies.");
        dialog.RootSubfolder = directory; Reject<UnauthorizedAccessException>(() => dialog.CurrentDir = ".."); Check(dialog.CurrentDir == directory, "Rejected root escape preserves directory."); dialog.FilenameFilter = "TWO"; Check(list.ItemCount == 2 && list.GetItemText(1) == "two.TXT", "Substring filter is case insensitive and retains directories."); dialog.ClearFilenameFilter(); dialog.ShowHiddenFiles = true; Check(list.ItemCount == 4, "Hidden toggle changes actual listing."); dialog.Hide(); Packing(dialog); EdgeCases(dialog, root, tree, list, directory); TrashProcess(); ContextEmbedding(directory);
        Console.WriteLine("FileDialog browser, filters, open/save validation, options, roots and scene reconstruction passed.");
    }
    private static void Packing(FileDialog dialog)
    {
        using var packed = new PackedScene(); packed.Pack(dialog); using var copy = (FileDialog)packed.Instantiate(); Check(copy.Access == FileDialogAccess.FileSystem && copy.FileMode == FileDialogMode.SaveFile && copy.OptionCount == 2 && copy.GetOptionDefault(0) == 1 && copy.GetOptionName(1) == "Quality", "Typed file browser and option schemas restore.");
        using var custom = new FileDialog { ModeOverridesTitle = false, Title = "Custom browser", FileMode = FileDialogMode.OpenDirectory }; using var customScene = new PackedScene(); customScene.Pack(custom); using var customCopy = (FileDialog)customScene.Instantiate(); Check(customCopy.Title == "Custom browser" && !customCopy.ModeOverridesTitle && customCopy.FileMode == FileDialogMode.OpenDirectory, "Stored mode restores after its title override policy.");
        var path = IOPath.Combine(IOPath.GetTempPath(), "electron2d-filedialog-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(packed, path); Child("ELECTRON2D_TEST_FILE_DIALOG_CHILD", path); } finally { File.Delete(path); }
    }
    private static void EdgeCases(FileDialog dialog, SubViewport root, SceneTree tree, ItemList list, string directory)
    {
        dialog.ShowHiddenFiles = false; dialog.OptionCount = 0; dialog.FileMode = FileDialogMode.OpenFiles; dialog.PopupFileDialog(); tree.ProcessFrame(.01); list.Select(1); list.Select(2, single: false); dialog.CurrentFile = "two.TXT"; IReadOnlyList<string>? paths = null; dialog.FilesSelected += value => paths = value; Accept(root, dialog);
        Check(paths != null && paths.SequenceEqual(new[] { IOPath.Combine(directory, "one.txt"), IOPath.Combine(directory, "two.TXT") }), "Multiple selection returns actual files in index order.");
        dialog.FileMode = FileDialogMode.OpenDirectory; dialog.PopupFileDialog(); tree.ProcessFrame(.01); list.Select(0); string? folder = null; dialog.DirSelected += value => folder = value; Accept(root, dialog); Check(folder == IOPath.Combine(directory, "folder"), "Directory selection emits the selected directory.");
        dialog.PopupFileDialog(); tree.ProcessFrame(.01); dialog.DeselectAll(); Accept(root, dialog); Check(folder == directory, "No directory selection accepts the current directory.");
        dialog.FileMode = FileDialogMode.OpenAny; dialog.CurrentFile = "two.TXT"; dialog.PopupFileDialog(); tree.ProcessFrame(.01); Accept(root, dialog); Check(!dialog.Visible, "Open-any accepts an existing file.");
        dialog.FileMode = FileDialogMode.SaveFile; dialog.CurrentFile = "one.txt"; dialog.PopupFileDialog(); tree.ProcessFrame(.01); var overwrite = (ConfirmationDialog)dialog.GetNode("_overwrite"); Accept(root, dialog); Check(dialog.Visible && overwrite.Visible, "Existing destination requires a separate confirmation."); ActionKey(root, "ui_close_dialog"); tree.ProcessFrame(.01); Check(dialog.Visible && !overwrite.Visible && File.ReadAllText(IOPath.Combine(directory, "one.txt")) == "one", "Cancel overwrite preserves the browser and source."); Accept(root, dialog); Accept(root, overwrite); Check(!dialog.Visible && File.ReadAllText(IOPath.Combine(directory, "one.txt")) == "one", "Confirmed save emits a destination without replacing source contents.");
        dialog.CurrentFile = "none/leaf.txt"; dialog.PopupFileDialog(); tree.ProcessFrame(.01); Accept(root, dialog); var error = (AcceptDialog)dialog.GetNode("_file_error"); Check(error.Visible && dialog.Visible, "Missing parent prevents save acceptance."); ActionKey(root, "ui_close_dialog"); tree.ProcessFrame(.01); dialog.CurrentFile = "";
        var create = (Button)dialog.GetVBox().GetNode("Toolbar/NewFolder"); create.GrabFocus(); ActionKey(root, "ui_accept"); var mkdir = (ConfirmationDialog)dialog.GetNode("_create_folder"); ((LineEdit)mkdir.GetNode("FolderName")).Text = "created-folder"; Accept(root, mkdir); Check(dialog.CurrentDir == IOPath.Combine(directory, "created-folder") && Directory.Exists(dialog.CurrentDir), "Create-folder command executes DirAccess and navigates the result."); dialog.CurrentDir = directory;
        dialog.GetLineEdit().GrabFocus(); Key(root, Electron2D.Key.H); Check(dialog.ShowHiddenFiles, "Independent built-in shortcut changes real listing."); dialog.HiddenFilesToggleEnabled = false; Key(root, Electron2D.Key.H); Check(dialog.ShowHiddenFiles, "Customization gates its shortcut."); dialog.HiddenFilesToggleEnabled = true;
        var seen = ""; Action<string> changed = value => seen = value; dialog.FilenameFilterChanged += changed; dialog.FilenameFilter = "two"; Check(seen == "two" && list.GetItemText(list.ItemCount - 1) == "two.TXT", "Programmatic filter emits committed text and refreshes."); Action<string> fail = _ => throw new InvalidOperationException("observer"); dialog.FilenameFilterChanged += fail; Reject<AggregateException>(() => dialog.FilenameFilter = "one"); Check(dialog.FilenameFilter == "one" && list.GetItemText(list.ItemCount - 1) == "one.txt", "Failed filter observer still commits and refreshes."); dialog.FilenameFilterChanged -= fail; dialog.FilenameFilterChanged -= changed; dialog.ClearFilenameFilter();
        FileDialog.SetFavoriteList([directory]); FileDialog.SetRecentList([directory, "res://"]); dialog.Invalidate(); Check(((ItemList)dialog.GetVBox().GetNode("Browser/Places/Favorites")).ItemCount == 1 && FileDialog.GetFavoriteList()[0] == directory + "/", "Shared favorites populate the actual scoped sidebar."); Check(FileDialog.GetRecentList()[0] == directory + "/" && FileDialog.GetRecentList()[1] == "res://", "Shared directory lists normalize a trailing separator."); Reject<InvalidOperationException>(() => Task.Run(() => FileDialog.GetFavoriteList()).GetAwaiter().GetResult()); FileDialog.SetFavoriteList([IOPath.Combine(directory, "absent-favorite")]); dialog.Invalidate(); Check(FileDialog.GetFavoriteList().Count == 0, "Stale matching favorite directories are pruned."); FileDialog.SetFavoriteList([]); FileDialog.SetRecentList([]);
        FileDialog.SetGetIconCallback(_ => { if (dialog.FilenameFilter.Length == 0) dialog.FilenameFilter = "two"; return null; }); dialog.DisplayMode = FileDialog.DisplayModeType.List; Check(dialog.FilenameFilter == "two" && list.GetItemText(list.ItemCount - 1) == "two.TXT", "Reentrant icon callback settles against current filter."); FileDialog.SetGetIconCallback(null); dialog.ClearFilenameFilter();
        Reject<ArgumentOutOfRangeException>(() => dialog.FileMode = (FileDialogMode)99); Reject<ArgumentOutOfRangeException>(() => dialog.SetOptionDefault(0, 1)); Reject<ArgumentException>(() => dialog.Filters = ["bad\0"]); Reject<UnauthorizedAccessException>(() => dialog.CurrentDir = ".."); Check(dialog.CurrentDir == directory, "Invalid writes preserve existing scope."); dialog.UseNativeDialog = true; Check(!DisplayServer.IsAvailable, "Focused test has no native session."); dialog.Hide(); dialog.PopupFileDialog(); Check(dialog.Visible, "Unavailable native service falls back to executable custom browser."); dialog.Hide();
        dialog.Access = FileDialogAccess.Resources; Check(dialog.RootSubfolder.Length == 0 && dialog.CurrentDir == "res://" && dialog.CurrentPath == "res://", "Access migration resets boundary and preserves virtual URI root."); dialog.CurrentPath = "res://Electron2D.csproj"; Check(dialog.CurrentDir == "res://" && dialog.CurrentFile == "Electron2D.csproj", "Virtual root splitting preserves scope."); dialog.Access = FileDialogAccess.FileSystem;
        Reject<ArgumentException>(() => OS.MoveToTrash("")); Reject<ArgumentException>(() => OS.ShellOpen("")); Reject<ArgumentException>(() => OS.ShellShowInFileManager("bad\0")); Reject<InvalidOperationException>(() => Engine.UnregisterSingleton("OS")); Reject<InvalidOperationException>(() => Engine.GetSingleton<OS>("OS").Dispose()); Check(Engine.GetSingleton<OS>("OS") != null, "OS retains named process service identity.");
    }
    private static void Accept(Viewport root, AcceptDialog dialog) { dialog.GetOKButton().GrabFocus(); ActionKey(root, "ui_accept"); }
    private static void ContextEmbedding(string directory)
    {
        foreach (var embed in new[] { false, true })
        {
            var root = new SubViewport { Size = new(1400, 1000), GUIEmbedSubwindows = true }; var dialog = new FileDialog { Access = FileDialogAccess.FileSystem, CurrentDir = directory, FileMode = FileDialogMode.OpenFile, GUIEmbedSubwindows = embed }; root.AddChild(dialog); using var tree = new SceneTree(root); tree.ProcessFrame(.01); dialog.PopupFileDialog(); tree.ProcessFrame(.01); dialog.Position = new(100, 80); var list = (ItemList)dialog.GetVBox().GetNode("Browser/Files"); var point = list.GetItemRect(0).GetCenter(); var at = list.GetGlobalTransformWithCanvas() * point; using var down = new InputEventMouseButton { Position = (Vector2)dialog.Position + at, ButtonIndex = MouseButton.Right, Pressed = true }; root.PushInput(down, true); var context = (PopupMenu)dialog.GetNode("_file_actions"); Check(context.Visible && context.Position == (Vector2i)(embed ? at : (Vector2)dialog.Position + at), "Context anchor uses its actual embedding viewport exactly once."); context.Hide(); using var motion = new InputEventMouseMotion { Position = (Vector2)dialog.Position + at, Relative = new(1, 1) }; root.PushInput(motion, true); tree.ProcessFrame(2); Check(list.GetNodeOrNull("Tooltip") != null, "Embedded file tooltip is active before owner-tree teardown.");
        }
    }
    private static void TrashProcess()
    {
        if (!OperatingSystem.IsLinux() || OperatingSystem.IsAndroid()) return;
        var path = IOPath.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".cache", "electron2d-trash-check-" + Guid.NewGuid()); Directory.CreateDirectory(path); try { Child("ELECTRON2D_TEST_FILE_DIALOG_TRASH", path, path); } finally { Directory.Delete(path, true); }
    }
    internal static void RunTrashChild(string directory)
    {
        var source = IOPath.Combine(directory, "source.txt"); File.WriteAllText(source, "recoverable"); OS.MoveToTrash(source); var trash = IOPath.Combine(directory, "Trash"); Check(!File.Exists(source) && Directory.GetFiles(IOPath.Combine(trash, "files")).Any(p => File.ReadAllText(p) == "recoverable") && Directory.GetFiles(IOPath.Combine(trash, "info")).Any(p => File.ReadAllText(p).Contains("Path=")), "GIO creates recoverable content and metadata in isolated XDG trash.");
        var guiFile = IOPath.Combine(directory, "gui.txt"); File.WriteAllText(guiFile, "confirmed"); var root = new SubViewport { Size = new(1100, 720), GUIEmbedSubwindows = true }; var dialog = new FileDialog { Access = FileDialogAccess.FileSystem, CurrentDir = directory, FileMode = FileDialogMode.OpenFile }; root.AddChild(dialog); using var tree = new SceneTree(root); tree.ProcessFrame(.01); dialog.PopupFileDialog(); tree.ProcessFrame(.01); var list = (ItemList)dialog.GetVBox().GetNode("Browser/Files"); var index = Enumerable.Range(0, list.ItemCount).First(i => list.GetItemText(i) == "gui.txt"); list.Select(index); dialog.GetOKButton().GrabFocus(); Key(root, Electron2D.Key.Delete); var confirmation = (ConfirmationDialog)dialog.GetNode("_trash"); Check(confirmation.Visible && File.Exists(guiFile), "Trash shortcut requires confirmation before OS work."); ActionKey(root, "ui_close_dialog"); tree.ProcessFrame(.01); Check(File.Exists(guiFile) && dialog.Visible, "Canceled trash preserves file and browser."); dialog.GetOKButton().GrabFocus(); Key(root, Electron2D.Key.Delete); Accept(root, confirmation); Check(!File.Exists(guiFile) && !Enumerable.Range(0, list.ItemCount).Any(i => list.GetItemText(i) == "gui.txt"), "Confirmed browser trash executes native recovery and refreshes listing."); dialog.Hide();
        var target = IOPath.Combine(directory, "target.txt"); File.WriteAllText(target, "preserved"); var link = IOPath.Combine(directory, "link.txt"); File.CreateSymbolicLink(link, target); OS.MoveToTrash(link); Check(File.Exists(target) && File.ReadAllText(target) == "preserved", "Trashing a symlink preserves its target."); Reject<IOException>(() => OS.MoveToTrash(IOPath.Combine(directory, "absent"))); Console.WriteLine("File dialog child passed");
    }
    private static void Child(string flag, string path, string? xdg = null)
    {
        var start = new System.Diagnostics.ProcessStartInfo(Environment.ProcessPath!) { RedirectStandardOutput = true, RedirectStandardError = true }; if (IOPath.GetFileNameWithoutExtension(Environment.ProcessPath) == "dotnet") start.ArgumentList.Add(typeof(FileDialogTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_FILE_DIALOG"); start.Environment[flag] = path; if (xdg != null) start.Environment["XDG_DATA_HOME"] = xdg; using var process = System.Diagnostics.Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("File dialog child."); }
        Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("File dialog child passed"), "File dialog child: " + error.GetAwaiter().GetResult());
    }
    internal static void RunChild(string path)
    {
        using var scene = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); var dialog = (FileDialog)scene.Instantiate(); var root = new SubViewport { Size = new(1100, 720), GUIEmbedSubwindows = true }; root.AddChild(dialog); using var tree = new SceneTree(root); tree.ProcessFrame(.01); dialog.CurrentFile = "fresh"; var selected = ""; dialog.FileSelected += value => selected = value; dialog.PopupFileDialog(); tree.ProcessFrame(.01); Accept(root, dialog); Check(selected.EndsWith("fresh.txt", StringComparison.Ordinal) && dialog.GetSelectedOptions()["Quality"].SelectedIndex == 1, "Fresh resource reconstructs filters/options and executes save validation."); Console.WriteLine("File dialog child passed");
    }
    private static void Key(Viewport root, Electron2D.Key key) { using var input = new InputEventKey { Keycode = key, Pressed = true }; root.PushInput(input, true); }
    private static void ActionKey(Viewport root, string action) { using var down = new InputEventAction { Action = action, Pressed = true }; using var up = new InputEventAction { Action = action }; root.PushInput(down, true); root.PushInput(up, true); }
    private static void Check(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
