using Electron2D;

internal static class MenuButtonTests
{
    internal static void Run()
    {
        using var detached = new MenuButton("File"); Check(detached.Flat && detached.ToggleMode && detached.ActionMode == ButtonActionMode.ButtonPress && detached.FocusMode == FocusMode.Accessibility && !detached.SwitchOnHover && detached.ItemCount == 0 && detached.ChildCount == 0 && detached.GetChildCount(true) == 1, "Menu button defaults and owned popup."); detached.ShowPopup(); Reject<ArgumentOutOfRangeException>(() => detached.ItemCount = -1);
        var root = new SubViewport { Size = new(600, 320), GUIEmbedSubwindows = true }; var bar = new HBoxContainer { Name = "Bar", Position = new(20, 20), Size = new(220, 40) }; var file = new MenuButton("File") { Name = "File", SwitchOnHover = true }; var edit = new MenuButton("Edit") { Name = "Edit", SwitchOnHover = true }; file.GetPopup().AddItem("Disabled"); file.GetPopup().SetItemDisabled(0, true); file.GetPopup().AddSeparator("Group"); file.GetPopup().AddItem("Open", 42); edit.GetPopup().AddItem("Copy", 84); bar.AddChild(file); bar.AddChild(edit); root.AddChild(bar); var ordinary = new Button("Ordinary") { Name = "Ordinary", Position = new(320, 20), Size = new(150, 40) }; root.AddChild(ordinary); using var tree = new SceneTree(root); tree.ProcessFrame(.01);
        var about = 0; var pressed = 0; var activated = new List<int>(); file.AboutToPopup += () => { Check(!file.GetPopup().Visible, "AboutToPopup precedes visibility."); about++; }; file.Pressed += () => pressed++; file.GetPopup().IDPressed += activated.Add;
        file.ShowPopup(); Check(about == 1 && file.GetPopup().Visible && file.ButtonPressed && file.GetPopup().GetFocusedItem() == 2, "Programmatic opening focuses first eligible command after preparation."); Action(root, "ui_accept"); Check(activated.SequenceEqual(new[] { 42 }) && !file.GetPopup().Visible && !file.ButtonPressed, "Command activation hides and resets toggle state.");
        Click(root, file.GetGlobalRect().GetCenter()); Check(file.GetPopup().Visible && file.GetPopup().GetFocusedItem() == -1 && pressed == 1, "Pointer opens with no item focus and emits one pressed event."); Motion(root, edit.GetGlobalRect().GetCenter()); tree.ProcessFrame(.01); Check(!file.GetPopup().Visible && edit.GetPopup().Visible && edit.ButtonPressed && !file.ButtonPressed && edit.GetPopup().GetFocusedItem() == -1, "Hover switches related opt-in menu buttons without item focus."); edit.GetPopup().Hide();
        var ordinaryPressed = 0; ordinary.Pressed += () => ordinaryPressed++; Click(root, ordinary.GetGlobalRect().GetCenter()); Check(ordinaryPressed == 1, "Closed popup leaves no stale parent pointer capture.");
        file.ShowPopup(); edit.Disabled = true; Motion(root, edit.GetGlobalRect().GetCenter()); tree.ProcessFrame(.01); Check(file.GetPopup().Visible && !edit.GetPopup().Visible, "Disabled hover target is skipped."); edit.Disabled = false; edit.SwitchOnHover = false; Motion(root, edit.GetGlobalRect().GetCenter()); tree.ProcessFrame(.01); Check(file.GetPopup().Visible, "Both buttons must opt into hover switch."); edit.SwitchOnHover = true; file.SwitchOnHover = false; Motion(root, edit.GetGlobalRect().GetCenter()); tree.ProcessFrame(.01); Check(file.GetPopup().Visible, "Active owner's live hover gate."); file.GetPopup().Hide(); file.SwitchOnHover = true;
        var unrelatedParent = new Control { Name = "Unrelated" }; var unrelated = new MenuButton("Other") { Name = "Other", SwitchOnHover = true, Position = new(250, 100), Size = new(100, 40) }; unrelated.GetPopup().AddItem("Other command"); unrelatedParent.AddChild(unrelated); root.AddChild(unrelatedParent); tree.ProcessFrame(.01); file.ShowPopup(); Motion(root, unrelated.GetGlobalRect().GetCenter()); tree.ProcessFrame(.01); Check(file.GetPopup().Visible && !unrelated.GetPopup().Visible, "Unrelated menu branches do not switch."); file.Hide(); Check(!file.GetPopup().Visible, "Hiding owner hides popup."); file.Show();
        using var key = new InputEventKey { Keycode = Electron2D.Key.O }; using var shortcut = new Shortcut { Events = [key] }; file.GetPopup().SetItemShortcut(2, shortcut); Key(root, Electron2D.Key.O); Check(activated.Count == 2, "Hidden menu item shortcut activates."); file.SetDisableShortcuts(true); Key(root, Electron2D.Key.O); Check(activated.Count == 2, "Shortcut stage disabled."); file.SetDisableShortcuts(false); file.Disabled = true; Key(root, Electron2D.Key.O); Check(activated.Count == 2, "Disabled owner gates command shortcuts."); file.Disabled = false;
        file.GetPopup().AddShortcut(shortcut, 43, allowEcho: true); file.GetPopup().SetItemShortcutDisabled(2, true); Key(root, Electron2D.Key.O, echo: true); Check(activated.Last() == 43, "Explicit item echo policy is respected.");
        file.LayoutDirection = LayoutDirection.RTL; file.ShowPopup(); tree.ProcessFrame(.01); Check(file.GetPopup().IsLayoutRTL(), "Popup receives resolved layout direction."); file.GetPopup().Hide(); Reject<InvalidOperationException>(() => Task.Run(file.ShowPopup).GetAwaiter().GetResult()); Reentrancy(); Nested(); Packing(); Console.WriteLine("MenuButton commands, default/focus, shortcuts, hover switching, ownership, reentrancy, nested windows and fresh scenes passed.");
    }
    private static void Reentrancy()
    {
        var root = new SubViewport { Size = new(500, 250), GUIEmbedSubwindows = true }; var button = new MenuButton(); button.GetPopup().AddItem("Action"); root.AddChild(button); using var tree = new SceneTree(root); tree.ProcessFrame(.01); Action recurse = button.ShowPopup; button.AboutToPopup += recurse; Reject<AggregateException>(button.ShowPopup); Check(!button.GetPopup().Visible && !button.ButtonPressed, "Rejected presentation reentry cleans pressed state."); button.AboutToPopup -= recurse;
        button.GetPopup().PopupHide += () => throw new InvalidOperationException("hide observer"); button.ShowPopup(); Reject<Exception>(() => button.GetPopup().Hide()); Check(!button.GetPopup().Visible && !button.ButtonPressed, "Popup hide observer failure still synchronizes owner.");
        var deleting = new MenuButton { Name = "Deleting" }; deleting.GetPopup().AddItem("Dispose"); using var key = new InputEventKey { Keycode = Electron2D.Key.D }; using var shortcut = new Shortcut { Events = [key] }; deleting.GetPopup().SetItemShortcut(0, shortcut); deleting.GetPopup().IDPressed += _ => deleting.Dispose(); root.AddChild(deleting); Key(root, Electron2D.Key.D); Check(deleting.IsDisposed, "Shortcut callback may dispose its owner without stale tree access.");
    }
    private static void Nested()
    {
        var root = new SubViewport { Size = new(800, 500), GUIEmbedSubwindows = true }; var window = new Window { Name = "Inner", Position = new(120, 70), Size = new(450, 280), Borderless = true, GUIEmbedSubwindows = true }; var menu = new MenuButton("Nested") { Name = "Menu", Position = new(25, 20), Size = new(110, 40) }; menu.GetPopup().AddItem("Execute", 99); window.AddChild(menu); root.AddChild(window); using var tree = new SceneTree(root); tree.ProcessFrame(.01); var count = 0; menu.GetPopup().IDPressed += _ => count++; menu.ShowPopup(); Action(root, "ui_accept"); Check(count == 1 && !menu.GetPopup().Visible, "Nested embedded viewport keyboard descends to the focused menu.");
        menu.ShowPopup(); var original = menu.GetPopup().Position; menu.GetPopup().Hide(); window.CanvasTransform = new Transform(0, new Vector2(45, 15)); menu.ShowPopup(); Check(menu.GetPopup().Position == original + new Vector2i(45, 15), "Menu anchor includes its canvas transform exactly once."); menu.GetPopup().Hide(); window.CanvasTransform = Transform.Identity;
        var option = new OptionButton { Name = "Option", Position = new(25, 90), Size = new(130, 40) }; option.AddItem("One"); option.AddItem("Two"); window.AddChild(option); option.ShowPopup(); Check(option.GetPopup().Position.X < 100, "Nested choice uses its own embedding viewport origin once."); Action(root, "ui_down"); Action(root, "ui_accept"); Check(option.Selected == 1 && !option.GetPopup().Visible, "Nested OptionButton shares complete window input routing."); option.ShowPopup(); var optionPosition = option.GetPopup().Position; option.GetPopup().Hide(); window.CanvasTransform = new Transform(0, new Vector2(45, 15)); option.ShowPopup(); Check(option.GetPopup().Position == optionPosition + new Vector2i(45, 15), "Choice anchor includes its canvas transform exactly once."); option.GetPopup().Hide();
    }
    private static void Packing()
    {
        using var source = new MenuButton("Stored") { Name = "StoredMenu", ItemCount = 3, SwitchOnHover = true }; source.GetPopup().SetItemText(0, "Checked"); source.GetPopup().SetItemAsCheckable(0, true); source.GetPopup().SetItemChecked(0, true); source.GetPopup().SetItemText(1, "Radio"); source.GetPopup().SetItemAsRadioCheckable(1, true); source.GetPopup().SetItemID(1, 71); source.GetPopup().SetItemDisabled(1, true); source.GetPopup().SetItemAsSeparator(2, true); using var scene = new PackedScene(); scene.Pack(source); using var copy = (MenuButton)scene.Instantiate(); Check(copy.ItemCount == 3 && copy.GetPopup() != source.GetPopup() && copy.ChildCount == 0 && copy.GetPopup().IsItemCheckable(0) && copy.GetPopup().IsItemChecked(0) && copy.GetPopup().IsItemRadioCheckable(1) && copy.GetPopup().GetItemID(1) == 71 && copy.GetPopup().IsItemSeparator(2), "Seven indexed fields recreate independent popup records.");
        var path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "electron2d-menubutton-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(scene, path); var start = new System.Diagnostics.ProcessStartInfo(Environment.ProcessPath!) { RedirectStandardOutput = true, RedirectStandardError = true }; if (System.IO.Path.GetFileNameWithoutExtension(Environment.ProcessPath) == "dotnet") start.ArgumentList.Add(typeof(MenuButtonTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_MENU_BUTTON"); start.Environment["ELECTRON2D_TEST_MENU_BUTTON_CHILD"] = path; using var process = System.Diagnostics.Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("Menu button fresh process."); } Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh menu button scene passed"), "Fresh menu: " + error.GetAwaiter().GetResult()); } finally { File.Delete(path); }
    }
    internal static void RunChild(string path)
    { using var scene = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); var menu = (MenuButton)scene.Instantiate(); var root = new SubViewport { Size = new(500, 260), GUIEmbedSubwindows = true }; root.AddChild(menu); using var tree = new SceneTree(root); tree.ProcessFrame(.01); var selected = false; menu.GetPopup().IDPressed += _ => selected = true; menu.ShowPopup(); Action(root, "ui_accept"); Check(selected && menu.GetPopup().IsItemChecked(0) && !menu.GetPopup().Visible && menu.SwitchOnHover, "Fresh stored menu executes checked command without changing check state."); Console.WriteLine("Fresh menu button scene passed"); }
    private static void Click(Viewport root, Vector2 point) { using var down = new InputEventMouseButton { Position = point, ButtonIndex = MouseButton.Left, Pressed = true }; using var up = new InputEventMouseButton { Position = point, ButtonIndex = MouseButton.Left }; root.PushInput(down, true); root.PushInput(up, true); }
    private static void Motion(Viewport root, Vector2 point) { using var move = new InputEventMouseMotion { Position = point, Relative = new(1, 1) }; root.PushInput(move, true); }
    private static void Action(Viewport root, string action) { using var down = new InputEventAction { Action = action, Pressed = true }; using var up = new InputEventAction { Action = action }; root.PushInput(down, true); root.PushInput(up, true); }
    private static void Key(Viewport root, Electron2D.Key key, bool echo = false) { using var input = new InputEventKey { Keycode = key, Pressed = true, Echo = echo }; root.PushInput(input, true); }
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
