using Electron2D;
using System.Buffers.Binary;
using System.Diagnostics;
using IOPath = System.IO.Path;

internal static class MeshSkinTests
{
    internal static MeshSurfaceData Data(int slots = 4, int bone = 0)
    {
        var data = new MeshSurfaceData { Vertices = [new(0, 0), new(32, 0), new(32, 8), new(0, 8)], Indices = [0, 1, 2, 0, 2, 3], Bones = new int[slots * 4], Weights = new float[slots * 4] }; for (var i = 0; i < 4; i++) { data.Bones[i * slots + (slots == 8 ? 5 : 0)] = bone; data.Weights[i * slots + (slots == 8 ? 5 : 0)] = 1; }
        return data;
    }
    internal static ArrayMesh Mesh(int slots = 4, int bone = 0) { var mesh = new ArrayMesh(); mesh.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, Data(slots, bone), flags: slots == 8 ? Electron2D.Mesh.ArrayFormat.Use8BoneWeights : 0); return mesh; }
    private static Bone Bone(string name) { var bone = new Bone { Name = name, Rest = Transform.Identity }; bone.SetAutocalculateLengthAndAngle(false); bone.SetLength(32); return bone; }
    internal static void Run() { Channels(); ScenePalette(); Storage(); Console.WriteLine("Mesh four/eight skin channels, packed regions, scene palettes and fresh archives passed."); }
    private static void Channels()
    {
        using var mesh = Mesh(); var query = mesh.SurfaceGetArrays(0); Check(query.Bones.Length == 16 && query.Weights[0] == 1 && (mesh.SurfaceGetFormat(0) & (Electron2D.Mesh.ArrayFormat.Bones | Electron2D.Mesh.ArrayFormat.Weights)) != 0, "Actual channel storage and format."); query.Bones[0] = 7; Check(mesh.SurfaceGetArrays(0).Bones[0] == 0, "Queries copy skin channels."); using var copy = (ArrayMesh)mesh.Duplicate(); Check(copy.SurfaceGetArrays(0).Weights.SequenceEqual(query.Weights), "Duplicate retains skin arrays.");
        var bytes = new byte[16]; BinaryPrimitives.WriteUInt16LittleEndian(bytes, 6); BinaryPrimitives.WriteUInt16LittleEndian(bytes.AsSpan(8), 32767); mesh.SurfaceUpdateSkinRegion(0, 0, bytes); query = mesh.SurfaceGetArrays(0); Check(query.Bones[0] == 6 && query.Weights[0] == 32767 / 65535f, "Exact uint16/UNORM16 layout."); mesh.SurfaceUpdateSkinRegion(0, 1, [1]); Check(mesh.SurfaceGetArrays(0).Bones[0] == 262, "Partial skin record bytes retain untouched values."); Reject<ArgumentOutOfRangeException>(() => mesh.SurfaceUpdateSkinRegion(0, 64, [1])); Check(mesh.SurfaceGetArrays(0).Bones[0] == 262, "Rejected byte region preserves data.");
        var data = Data(); data.Weights[0] = .5f; data.Weights[1] = 2; data.Weights[2] = -1; using var quantized = new ArrayMesh(); quantized.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, data); query = quantized.SurfaceGetArrays(0); Check(query.Weights[0] == 32767 / 65535f && query.Weights[1] == 1 && query.Weights[2] == 0, "Imports clamp/truncate without normalizing sum."); data.Bones[0] = -1; Reject<ArgumentOutOfRangeException>(() => quantized.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, data)); data.Bones[0] = 65536; Reject<ArgumentOutOfRangeException>(() => quantized.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, data)); data.Bones[0] = 0; data.Weights[0] = float.NaN; Reject<ArgumentException>(() => quantized.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, data)); Reject<ArgumentException>(() => quantized.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, Data(8))); using var eight = Mesh(8, 7); Check((eight.SurfaceGetFormat(0) & Electron2D.Mesh.ArrayFormat.Use8BoneWeights) != 0, "Eight-weight schema executes.");
        var quantum = Data(); quantum.Weights[0] = 1f / 65535; using var precise = new ArrayMesh(); precise.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, quantum, flags: Electron2D.Mesh.ArrayFormat.Bones | Electron2D.Mesh.ArrayFormat.Weights); Check(precise.SurfaceGetArrays(0).Weights[0] == 1f / 65535, "Float32 quantization preserves the first UNORM16 quantum.");
        var empty = new MeshSurfaceData { Vertices = [new(0, 0), new(1, 0), new(0, 1)] }; using var unskinned = new ArrayMesh(); unskinned.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, empty); Reject<InvalidOperationException>(() => unskinned.SurfaceUpdateSkinRegion(0, 0, []));
    }
    private sealed class DrawMeshNode : Entity
    {
        internal Mesh? Resource;
        internal Transform Pose = Transform.Identity;
        protected override void OnDraw() { base.OnDraw(); if (Resource is not null) DrawMesh(Resource, transform: Pose); }
    }
    private sealed class CallbackMesh : Electron2D.Mesh
    {
        internal Action? Action;
        internal int Calls;
        protected override int OnGetSurfaceCount() => 1;
        protected override MeshSurfaceData OnSurfaceGetArrays(int surfaceIndex) { Calls++; Action?.Invoke(); return Data(); }
        protected override int OnSurfaceGetArrayLen(int surfaceIndex) => 4;
        protected override int OnSurfaceGetArrayIndexLen(int surfaceIndex) => 6;
        protected override PrimitiveType OnSurfaceGetPrimitiveType(int surfaceIndex) => PrimitiveType.Triangles;
        protected override ArrayFormat OnSurfaceGetFormat(int surfaceIndex) => ArrayFormat.Vertex | ArrayFormat.Use2DVertices | ArrayFormat.Bones | ArrayFormat.Weights | ArrayFormat.Index;
        protected override Material? OnSurfaceGetMaterial(int surfaceIndex) => null;
        protected override void OnSurfaceSetMaterial(int surfaceIndex, Material? material) { }
    }
    private static void ScenePalette()
    {
        using var mesh = Mesh(8, 5); using var root = new Entity(); var rig = new Skeleton { Name = "Rig", Position = new(10, 20) }; for (var i = 0; i < 8; i++) rig.AddChild(Bone("B" + i)); var node = new DrawMeshNode { Name = "Consumer", Position = new(20, 30), Resource = mesh }; root.AddChild(rig); root.AddChild(node); using var tree = new SceneTree(root); var rid = node.GetCanvasItem(); Check(rid.IsValid() && node.GetCanvasItem() == rid && RenderingCanvasItemRegistry.Resolve(rid) == node, "Stable weak canvas identity."); node.AttachSkeleton(rig.GetSkeleton()); rig.GetBone(5).Position = new(12, 0);
        var vertices = new List<CanvasVertex>(256); var batches = new List<CanvasBatch>(8); void Replay() { node.PrepareCanvas(); vertices.Clear(); batches.Clear(); node.AppendCanvas(vertices, batches, Transform.Identity); }
        Replay(); Near(vertices[0].Position, new(12, 0), .001f, "Fifth influence drives actual retained mesh geometry through different item/rig bases."); node.Pose = new Transform(Mathf.Pi / 2, new(3, 0)); node.QueueRedraw(); Replay(); Near(vertices[0].Position, new(3, 12), .001f, "Command-local transform follows skin deformation."); node.Pose = Transform.Identity; node.QueueRedraw();
        rig.Rotation = Mathf.Pi / 2; Replay(); Near(vertices[0].Position, new(0, 12), .001f, "Noncommuting palette basis participates."); rig.Rotation = 0; node.Scale = new(-1, 2); Replay(); Near(vertices[0].Position, new(-12, 0), .001f, "Reflected/nonuniform consumer basis participates."); node.Transform = new Transform(0, new(20, 30));
        var half = new byte[2]; BinaryPrimitives.WriteUInt16LittleEndian(half, 32767); for (var i = 0; i < 4; i++) mesh.SurfaceUpdateSkinRegion(0, i * 32 + 26, half); Replay(); Near(vertices[0].Position, new(12 * (32767 / 65535f), 0), .001f, "Stored weight sums remain unnormalized during actual deformation."); BinaryPrimitives.WriteUInt16LittleEndian(half, 65535); for (var i = 0; i < 4; i++) mesh.SurfaceUpdateSkinRegion(0, i * 32 + 26, half);
        var bad = new byte[2]; BinaryPrimitives.WriteUInt16LittleEndian(bad, 20); mesh.SurfaceUpdateSkinRegion(0, 0, bad); Reject<InvalidOperationException>(Replay); BinaryPrimitives.WriteUInt16LittleEndian(bad, 0); mesh.SurfaceUpdateSkinRegion(0, 0, bad); Replay(); Check(vertices.Count == 6, "Invalid even zero-weight indices reject safely and recover.");
        rig.Scale = Vector2.Zero; Replay(); Near(vertices[0].Position, Vector2.Zero, .001f, "Singular palette bases skip undefined inverse."); rig.Scale = Vector2.One;
        for (var i = 0; i < 32; i++) Replay(); var before = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 128; i++) { rig.GetBone(5).Position = new(12 + (i & 1), 0); Replay(); }
        Check(GC.GetAllocatedBytesForCurrentThread() == before, "128 prepared scene-palette eight-weight mesh replays allocate zero managed bytes.");
        node.AttachSkeleton(default); Replay(); Near(vertices[0].Position, Vector2.Zero, .001f, "Detach replays original geometry."); root.RemoveChild(node); node.Dispose(); Reject<ArgumentException>(() => RenderingCanvasItemRegistry.Resolve(rid));
    }
    private static void Storage()
    {
        using var mesh = Mesh(8, 5); mesh.SurfaceSetName(0, "Skin🙂"); using var material = new CanvasItemMaterial { BlendMode = BlendMode.Add }; mesh.SurfaceSetMaterial(0, material); mesh.AddSurfaceFromArrays(Electron2D.Mesh.PrimitiveType.Triangles, Data()); mesh.SurfaceSetMaterial(1, material); using var node = new MeshInstance { Name = "Skin", Mesh = mesh }; using var packed = new PackedScene(); packed.Pack(node); var path = IOPath.Combine(IOPath.GetTempPath(), "e2d-mesh-skin-" + Guid.NewGuid().ToString("N") + ".e2dscene");
        try { ResourceSaver.Save(packed, path); RunChild(path); var start = new ProcessStartInfo("dotnet") { RedirectStandardOutput = true, RedirectStandardError = true }; start.ArgumentList.Add(typeof(MeshSkinTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_MESH_SKIN_HOST"); start.Environment["ELECTRON2D_TEST_MESH_SKIN_CHILD"] = path; using var process = Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("Mesh skin child."); } Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh mesh skin scene passed"), error.GetAwaiter().GetResult()); } finally { File.Delete(path); }
        var stored = (PropertyDescriptor<ArrayMesh, byte[]>)mesh.GetPropertyList().First(p => p.Name == "_surface_data"); Reject<InvalidDataException>(() => stored.SetValue(mesh, new byte[8])); Check(mesh.GetSurfaceCount() == 2 && mesh.SurfaceGetName(0) == "Skin🙂", "Malformed archive preserves prior surfaces.");
    }
    internal static void RunChild(string path)
    {
        using var packed = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); using var node = (MeshInstance)packed.Instantiate(); var mesh = (ArrayMesh)node.Mesh!; Check(mesh.SurfaceGetArrays(0).Bones[5] == 5 && mesh.SurfaceGetArrays(0).Weights[5] == 1 && mesh.SurfaceGetName(0) == "Skin🙂" && mesh.SurfaceGetMaterial(0) is CanvasItemMaterial { BlendMode: BlendMode.Add }, "Fresh mesh/node/material factories and copied four/eight channel schema."); Check(ReferenceEquals(mesh.SurfaceGetMaterial(0), mesh.SurfaceGetMaterial(1)), "Fresh material graph aliases survive separate geometry/material schema."); using var root = new Entity(); var rig = new Skeleton(); for (var i = 0; i < 8; i++) rig.AddChild(Bone("B" + i)); root.AddChild(rig); root.AddChild(node); using var tree = new SceneTree(root); node.AttachSkeleton(rig.GetSkeleton()); rig.GetBone(5).Position = new(9, 0); node.PrepareCanvas(); var vertices = new List<CanvasVertex>(); var batches = new List<CanvasBatch>(); node.AppendCanvas(vertices, batches, Transform.Identity); Near(vertices[0].Position, new(9, 0), .001f, "Fresh stored mesh executes actual palette deformation."); Console.WriteLine("Fresh mesh skin scene passed.");
    }
    internal static void RunHost()
    {
        Run(); var method = Environment.GetEnvironmentVariable("ELECTRON2D_MESH_SKIN_RENDERER") ?? "gpu"; var previous = ProjectSettings.Get(ProjectSettings.RenderingMethod); ProjectSettings.Set(ProjectSettings.RenderingMethod, method); using var four = Mesh(); using var eight = Mesh(8, 5); using var sceneMesh = Mesh(); using var callbackMesh = new CallbackMesh(); using var instances = new MultiMesh { Mesh = four, InstanceCount = 1 }; instances.SetInstanceTransform2D(0, Transform.Identity);
        try
        {
            var window = new Window { Size = new(240, 140) }; var a = new MeshInstance { Name = "Four", Mesh = four, Position = new(20, 25), Modulate = new(.1f, .7f, 1) }; var b = new MeshInstance { Name = "Eight", Mesh = eight, Position = new(90, 25), Modulate = a.Modulate }; var rig = new Skeleton { Position = new(155, 25) }; var bone = Bone("B"); bone.Position = new(0, 12); rig.AddChild(bone); var c = new MeshInstance { Name = "Scene", Mesh = sceneMesh, Position = rig.Position, Modulate = a.Modulate }; var multi = new MultiMeshInstance { MultiMesh = instances, Position = new(400, 85), Modulate = a.Modulate }; window.AddChild(a); window.AddChild(b); window.AddChild(rig); window.AddChild(c); window.AddChild(multi); var guard = new MeshInstance { Name = "Guard", Mesh = callbackMesh, Position = new(200, 105) }; window.AddChild(guard);
            var frame = 0; long before = 0, active = 0, idle = 0; RID palette = default, eightPalette = default, multiPalette = default, ownedMesh = default; var patch = new byte[2];
            window.Ready += _ =>
            {
                Check(RenderingServer.GetCurrentRenderingMethod() == method, "Requested native backend actually initialized without fallback.");
                RenderingServer.SetDefaultClearColor(new(.04f, .05f, .08f)); palette = RenderingServer.SkeletonCreate(); RenderingServer.SkeletonAllocateData(palette, 1); Check(RenderingServer.SkeletonGetBoneCount(palette) == 1 && RenderingServer.SkeletonBoneGetTransform2D(palette, 0) == default, "Allocation initializes zero transforms."); RenderingServer.SkeletonBoneSetTransform2D(palette, 0, new Transform(0, new(20, 0))); RenderingServer.SkeletonAllocateData(palette, 1); Check(RenderingServer.SkeletonBoneGetTransform2D(palette, 0).Origin.X == 20, "Equal allocation preserves data."); RenderingServer.SkeletonSetBaseTransform2D(palette, new Transform(.2f, new(10, 0))); RenderingServer.SkeletonSetBaseTransform2D(palette, Transform.Identity); RenderingServer.CanvasItemAttachSkeleton(a.GetCanvasItem(), palette); RenderingServer.CanvasItemAttachSkeleton(guard.GetCanvasItem(), palette); callbackMesh.Action = () => { Reject<InvalidOperationException>(() => RenderingServer.SkeletonBoneSetTransform2D(palette, 0, Transform.Identity)); Reject<InvalidOperationException>(() => RenderingServer.SkeletonAllocateData(palette, 0)); Reject<InvalidOperationException>(() => RenderingServer.FreeRID(palette)); };
                eightPalette = RenderingServer.SkeletonCreate(); RenderingServer.SkeletonAllocateData(eightPalette, 8); for (var i = 0; i < 8; i++) RenderingServer.SkeletonBoneSetTransform2D(eightPalette, i, new Transform(0, new(12, 0))); RenderingServer.CanvasItemAttachSkeleton(b.GetCanvasItem(), eightPalette); RenderingServer.CanvasItemAttachSkeleton(c.GetCanvasItem(), rig.GetSkeleton()); multiPalette = RenderingServer.SkeletonCreate(); RenderingServer.SkeletonAllocateData(multiPalette, 1); RenderingServer.SkeletonBoneSetTransform2D(multiPalette, 0, new Transform(0, new(-240, 0))); RenderingServer.CanvasItemAttachSkeleton(multi.GetCanvasItem(), multiPalette);
                Check(RenderingServer.SkeletonGetBoneCount(rig.GetSkeleton()) == 1 && RenderingServer.SkeletonBoneGetTransform2D(rig.GetSkeleton(), 0).Origin.Y == 12, "Scene palette read follows actual pose."); Reject<InvalidOperationException>(() => RenderingServer.SkeletonAllocateData(rig.GetSkeleton(), 1)); Reject<InvalidOperationException>(() => RenderingServer.FreeRID(rig.GetSkeleton())); Reject<InvalidOperationException>(() => RenderingServer.FreeRID(a.GetCanvasItem())); Reject<ArgumentOutOfRangeException>(() => RenderingServer.SkeletonAllocateData(palette, -1)); Reject<ArgumentOutOfRangeException>(() => RenderingServer.SkeletonBoneGetTransform2D(palette, 1)); Reject<ArgumentException>(() => RenderingServer.SkeletonSetBaseTransform2D(palette, new Transform(new(float.NaN, 0), Vector2.Down, Vector2.Zero))); Reject<InvalidOperationException>(() => Task.Run(() => RenderingServer.SkeletonBoneGetTransform2D(palette, 0)).GetAwaiter().GetResult());
                ownedMesh = RenderingServer.MeshCreate(); RenderingServer.MeshAddSurfaceFromArrays(ownedMesh, Electron2D.Mesh.PrimitiveType.Triangles, Data(8, 5), Electron2D.Mesh.ArrayFormat.Use8BoneWeights); Check(RenderingServer.MeshSurfaceGetFormatSkinStride(RenderingServer.MeshSurfaceGetFormat(ownedMesh, 0), 4) == 32 && RenderingServer.MeshSurfaceGetFormatSkinStride(Electron2D.Mesh.ArrayFormat.Bones | Electron2D.Mesh.ArrayFormat.Weights, 4) == 16, "Server stride query executes both schemas."); RenderingServer.MeshSurfaceUpdateSkinRegion(ownedMesh, 0, 10, patch); Check(RenderingServer.MeshSurfaceGetArrays(ownedMesh, 0).Bones[5] == 0, "Server skin update actually edits owned channel."); RenderingServer.FreeRID(ownedMesh); ownedMesh = default;
                window.Tree!.ProcessFrameStarted += _ => { before = GC.GetAllocatedBytesForCurrentThread(); if (frame < 128) { RenderingServer.SkeletonBoneSetTransform2D(eightPalette, 5, new Transform(0, new(12 + (frame & 1), 0))); BinaryPrimitives.WriteUInt16LittleEndian(patch, (ushort)((frame & 1) == 0 ? 5 : 6)); eight.SurfaceUpdateSkinRegion(0, 10, patch); } };
                RenderingServer.FramePostDraw += () => { if (frame is >= 64 and < 128) active += GC.GetAllocatedBytesForCurrentThread() - before; if (frame >= 128) idle += GC.GetAllocatedBytesForCurrentThread() - before; if (frame == 4) { using var image = RenderingServer.Service!.Readback(); Check(image.GetPixel(45, 28).B > .7f && image.GetPixel(25, 28).B < .3f, "Owned four-slot palette changes pixels."); Check(image.GetPixel(110, 28).B > .7f && image.GetPixel(93, 28).B < .3f, "Fifth of eight influences changes pixels."); Check(image.GetPixel(160, 40).B > .7f && image.GetPixel(160, 27).B < .3f, "Borrowed scene palette changes pixels."); Check(image.GetPixel(165, 88).B > .7f, "Skinned MultiMesh moved from outside original bounds remains visible."); if (Environment.GetEnvironmentVariable("ELECTRON2D_MESH_SKIN_CAPTURE") is { } path) image.SavePNG(path); } if (frame == 5) RenderingServer.SkeletonSetBaseTransform2D(palette, new Transform(Mathf.Pi / 2, Vector2.Zero)); if (frame == 6) { using var image = RenderingServer.Service!.Readback(); Check(image.GetPixel(25, 48).B > .7f && image.GetPixel(45, 28).B < .3f, "Owned rotated base changes actual palette-space deformation pixels."); RenderingServer.SkeletonSetBaseTransform2D(palette, Transform.Identity); } if (++frame == 192) { RenderingServer.FreeRID(palette); Reject<ArgumentException>(() => RenderingServer.SkeletonGetBoneCount(palette)); RenderingServer.CanvasItemAttachSkeleton(a.GetCanvasItem(), default); RenderingServer.FreeRID(eightPalette); window.Tree!.Quit(); } };
            };
            Check(Engine.Run(window) == 0 && frame == 192 && callbackMesh.Calls == 1 && active == 0 && idle == 0, "64 active + 64 idle native mesh skin intervals: " + active + "/" + idle); Check(!RenderingSkeletonRegistry.Contains(multiPalette), "Renderer teardown closes retained owned palette."); Console.WriteLine("64 active + 64 idle native mesh skin intervals: " + active + "/" + idle + " managed bytes; backend=" + method);
        }
        finally { ProjectSettings.Set(ProjectSettings.RenderingMethod, previous); }
    }
    private static void Near(Vector2 a, Vector2 b, float tolerance, string text) => Check(a.DistanceTo(b) <= tolerance, text + " actual=" + a + " expected=" + b);
    private static void Check(bool value, string text) { if (!value) throw new InvalidOperationException(text); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
