using Electron2D;
using System.Globalization;
using System.Diagnostics;
using System.Text;

internal static class NavigationAvoidanceTests
{
    internal static void Run()
    {
        var map = NavigationServer.MapCreate(); NavigationServer.MapSetActive(map, true); var a = Agent(map, new(0, 0), new(10, 0)); var b = Agent(map, new(20, 0), new(-10, 0));
        Check(NavigationServer.AgentGetRadius(a) == 2 && NavigationServer.AgentGetAvoidanceLayers(a) == 1 && NavigationServer.AgentGetAvoidanceMask(a) == 1 && NavigationServer.AgentGetTimeHorizonObstacles(a) == 1, "Real avoidance settings.");
        var deliveries = 0; NavigationServer.AgentSetAvoidanceCallback(a, v => { Check(NavigationServer.AgentGetVelocity(b).X == -8, "Every output publishes before first callback."); deliveries++; Reject<InvalidOperationException>(() => NavigationServer.Step(.1)); Reject<InvalidOperationException>(() => NavigationServer.Synchronize()); }); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(a) == new Vector2(8, 0) && NavigationServer.AgentGetVelocity(b) == new Vector2(-8, 0) && deliveries == 1, "Head-on reciprocal cutoff matches analytic ORCA constraint."); NavigationServer.Step(0); Check(deliveries == 1, "Zero-step sync does not dispatch."); NavigationServer.AgentSetAvoidanceCallback(a, null); Check(!NavigationServer.AgentHasAvoidanceCallback(a), "Callback removal.");
        ResetPair(); NavigationServer.AgentSetAvoidanceMask(a, 0); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(a).X == 10 && NavigationServer.AgentGetVelocity(b).X == -8, "Directed mask filtering."); NavigationServer.AgentSetAvoidanceMask(a, 1); ResetPair(); NavigationServer.AgentSetAvoidancePriority(a, 1); NavigationServer.AgentSetAvoidancePriority(b, .5f); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(a).X == 10 && NavigationServer.AgentGetVelocity(b).X == -8, "High priority ignores lower priority."); NavigationServer.AgentSetAvoidancePriority(b, 1);
        ResetPair(); NavigationServer.AgentSetMaxNeighbors(a, 0); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(a).X == 10, "Zero neighbors disables pair constraints."); NavigationServer.AgentSetMaxNeighbors(a, 10); ResetPair(); NavigationServer.AgentSetNeighborDistance(a, 20); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(a).X == 10, "Neighbor boundary is strict."); NavigationServer.AgentSetNeighborDistance(a, 100); ResetPair(); NavigationServer.AgentSetPaused(b, true); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(a).X == 10 && NavigationServer.AgentGetPaused(b), "Paused agents leave simulation."); NavigationServer.AgentSetPaused(b, false);
        ResetPair(); NavigationServer.AgentSetMaxSpeed(a, 3); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(a).Length() <= 3.00001f, "Output speed cap."); NavigationServer.AgentSetMaxSpeed(a, 10);
        ResetPair(); NavigationServer.AgentSetPosition(b, Vector2.Zero); NavigationServer.AgentSetVelocity(a, Vector2.Zero); NavigationServer.AgentSetVelocity(b, Vector2.Zero); NavigationServer.AgentSetTimeHorizonAgents(a, 0); NavigationServer.AgentSetTimeHorizonAgents(b, 0); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(a).IsFinite() && NavigationServer.AgentGetVelocity(a).X < 0 && NavigationServer.AgentGetVelocity(b).X > 0, "Coincident stationary discs separate with finite opposing velocities."); NavigationServer.AgentSetTimeHorizonAgents(a, 1); NavigationServer.AgentSetTimeHorizonAgents(b, 1);
        ResetPair(); var callbacks = 0; Action<Vector2> first = _ => throw new InvalidOperationException("Observer"); Action<Vector2> second = _ => callbacks++; NavigationServer.AgentSetAvoidanceCallback(a, first + second); Reject<AggregateException>(() => NavigationServer.Step(.1)); Check(callbacks == 1 && NavigationServer.AgentGetVelocity(a).X == 8, "Failure preserves published output and later delivery."); NavigationServer.AgentSetAvoidanceCallback(a, null);
        ResetPair(); NavigationServer.AgentSetAvoidanceCallback(a, _ => NavigationServer.FreeRID(b)); NavigationServer.AgentSetAvoidanceCallback(b, _ => throw new InvalidOperationException("Freed recipient")); NavigationServer.Step(.1); Reject<ArgumentException>(() => NavigationServer.AgentGetVelocity(b)); NavigationServer.AgentSetAvoidanceCallback(a, null); b = Agent(map, new(20, 0), new(-10, 0));
        Reject<ArgumentOutOfRangeException>(() => NavigationServer.AgentSetAvoidancePriority(a, 2)); Reject<ArgumentOutOfRangeException>(() => NavigationServer.AgentSetRadius(a, -1)); Reject<ArgumentException>(() => NavigationServer.AgentSetVelocity(a, new(float.NaN, 0))); Reject<ArgumentOutOfRangeException>(() => NavigationServer.Step(double.NaN)); Reject<ArgumentOutOfRangeException>(() => NavigationServer.Step(double.MaxValue)); Reject<ArgumentOutOfRangeException>(() => NavigationServer.Step(double.Epsilon));
        for (var i = 0; i < 64; i++) { ResetPair(); NavigationServer.Step(.1); }
        var allocation = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 2000; i++) { ResetPair(); NavigationServer.Step(.1); }
        Check(GC.GetAllocatedBytesForCurrentThread() == allocation, "2000 prepared pair position/velocity/forced reset and solve cycles allocate zero bytes.");
        NavigationServer.FreeRID(a); NavigationServer.FreeRID(b); NavigationServer.FreeRID(map); Obstacles(); Scenes(); Oracle(); Console.WriteLine("Navigation ORCA reciprocal agents, contours/discs, masks/priorities, callbacks, ownership, numeric edges, storage and warmed allocation passed.");
        void ResetPair() { NavigationServer.AgentSetPosition(a, Vector2.Zero); NavigationServer.AgentSetPosition(b, new(20, 0)); NavigationServer.AgentSetVelocityForced(a, Vector2.Zero); NavigationServer.AgentSetVelocityForced(b, Vector2.Zero); NavigationServer.AgentSetVelocity(a, new(10, 0)); NavigationServer.AgentSetVelocity(b, new(-10, 0)); }
    }
    private static RID Agent(RID map, Vector2 position, Vector2 velocity)
    { var rid = NavigationServer.AgentCreate(); NavigationServer.AgentSetMap(rid, map); NavigationServer.AgentSetAvoidanceEnabled(rid, true); NavigationServer.AgentSetRadius(rid, 2); NavigationServer.AgentSetMaxSpeed(rid, 10); NavigationServer.AgentSetNeighborDistance(rid, 100); NavigationServer.AgentSetTimeHorizonAgents(rid, 1); NavigationServer.AgentSetTimeHorizonObstacles(rid, 1); NavigationServer.AgentSetPosition(rid, position); NavigationServer.AgentSetVelocity(rid, velocity); return rid; }
    private static void Obstacles()
    {
        var map = NavigationServer.MapCreate(); NavigationServer.MapSetActive(map, true); var agent = Agent(map, Vector2.Zero, new(10, 0)); var obstacle = NavigationServer.ObstacleCreate(); NavigationServer.ObstacleSetMap(obstacle, map); NavigationServer.ObstacleSetPosition(obstacle, new(10, 0)); NavigationServer.ObstacleSetVertices(obstacle, [new(0, -20), new(0, 20)]); NavigationServer.Step(.1); Check(Math.Abs(NavigationServer.AgentGetVelocity(agent).X - 8) < .001f, "Two-point contour constrains the velocity against a static wall."); var copy = NavigationServer.ObstacleGetVertices(obstacle); copy[0] = Vector2.Zero; Check(NavigationServer.ObstacleGetVertices(obstacle)[0].Y == -20, "Contour reads are copied.");
        Reset(); NavigationServer.ObstacleSetAvoidanceLayers(obstacle, 2); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(agent).X == 10, "Contour layer filtering."); NavigationServer.ObstacleSetAvoidanceLayers(obstacle, 1); Reset(); NavigationServer.ObstacleSetPaused(obstacle, true); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(agent).X == 10, "Obstacle pause."); NavigationServer.ObstacleSetPaused(obstacle, false);
        NavigationServer.ObstacleSetVertices(obstacle, []); NavigationServer.ObstacleSetRadius(obstacle, 2); NavigationServer.ObstacleSetPosition(obstacle, new(20, 0)); Reset(); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(agent).X == 8, "Disc obstacle consumes agent prediction radius."); Reset(); NavigationServer.ObstacleSetVelocity(obstacle, new(-2, 0)); NavigationServer.Step(.1); Check(NavigationServer.AgentGetVelocity(agent).X < 8, "Moving-disc velocity affects prediction.");
        Reject<ArgumentException>(() => NavigationServer.ObstacleSetVertices(obstacle, [Vector2.Zero, Vector2.Zero])); Reject<ArgumentException>(() => NavigationServer.ObstacleSetVertices(obstacle, [new(0, 0), new(10, 10), new(0, 10), new(10, 0)])); Reject<ArgumentException>(() => NavigationServer.ObstacleSetPosition(obstacle, new(float.NaN, 0))); Reject<ArgumentOutOfRangeException>(() => NavigationServer.ObstacleSetRadius(obstacle, -1)); NavigationServer.FreeRID(map); Check(NavigationServer.ObstacleGetMap(obstacle) == default, "Map release detaches obstacle."); NavigationServer.FreeRID(obstacle); NavigationServer.FreeRID(agent);
        void Reset() { NavigationServer.AgentSetPosition(agent, Vector2.Zero); NavigationServer.AgentSetVelocityForced(agent, Vector2.Zero); NavigationServer.AgentSetVelocity(agent, new(10, 0)); }
    }
    private static void Scenes()
    {
        using var geometry = NavigationTests.Rectangle(-100, -100, 200, 200); var root = new SubViewport(); root.AddChild(new NavigationRegion { NavigationPolygon = geometry }); var parent = new Entity(); var agent = new NavigationAgent { AvoidanceEnabled = true, Radius = 2, MaxSpeed = 10, NeighborDistance = 100, TargetPosition = new(50, 0), Velocity = new(10, 0), TimeHorizonObstacles = 1 }; parent.AddChild(agent); root.AddChild(parent); var obstacle = new NavigationObstacle { Position = new(20, 0), Radius = 2, Name = "Obstacle" }; root.AddChild(obstacle); using var tree = new SceneTree(root); tree.PhysicsFrame(0); var deliveries = 0; agent.VelocityComputed += v => { deliveries++; Check(v.IsFinite(), "Finite scene velocity."); Reject<InvalidOperationException>(() => agent.Dispose()); }; tree.PhysicsFrame(.1); Check(deliveries == 1 && NavigationServer.AgentGetVelocity(agent.GetRID()).X < 10 && agent.Velocity.X == 10, "Scene preparation and cached desired velocity.");
        var beforeBatch = deliveries; NavigationServer.Step(.1); Check(deliveries == beforeBatch, "Batch stepping does not drive a scene-owned map.");
        var observed = deliveries; Action<RID> failMap = _ => throw new InvalidOperationException("Map observer"); NavigationServer.MapChanged += failMap; NavigationServer.MapSetActive(agent.GetNavigationMap(), true); Reject<AggregateException>(() => tree.PhysicsFrame(.1)); NavigationServer.MapChanged -= failMap; Check(deliveries == observed + 1, "Topology observer failure does not skip independent avoidance stepping.");
        var previous = deliveries; tree.Paused = true; Check(NavigationServer.AgentGetPaused(agent.GetRID()) && NavigationServer.ObstacleGetMap(obstacle.GetRID()) == default, "Pause notifications immediately update agent and detach obstacle membership."); tree.PhysicsFrame(.1); Check(deliveries == previous && NavigationServer.AgentGetPaused(agent.GetRID()) && NavigationServer.ObstacleGetPaused(obstacle.GetRID()), "Paused scene parent/obstacle do not deliver."); tree.Paused = false; tree.PhysicsFrame(.1); Check(deliveries == previous + 1, "Unpause restores participation.");
        using var world = new World(); root.World = world; tree.PhysicsFrame(.1); Check(NavigationServer.AgentGetMap(agent.GetRID()) == world.NavigationMap && NavigationServer.ObstacleGetMap(obstacle.GetRID()) == world.NavigationMap, "World transfer shares identities."); obstacle.Scale = new(2, 3); tree.PhysicsFrame(.1); Check(NavigationServer.ObstacleGetRadius(obstacle.GetRID()) == 6 && NavigationServer.ObstacleGetPosition(obstacle.GetRID()) == new Vector2(20, 0), "Transform radius uses largest absolute axis."); obstacle.Vertices = [new(0, -10), new(0, 10)]; tree.PhysicsFrame(.1); Check(NavigationServer.ObstacleGetVertices(obstacle.GetRID())[1] == new Vector2(0, 30), "Contour offsets transform without duplicate translation.");
        var foreignRoot = new SubViewport(); var foreignParent = new Entity(); var foreignAgent = new NavigationAgent(); foreignParent.AddChild(foreignAgent); foreignRoot.AddChild(foreignParent); using (var foreignTree = new SceneTree(foreignRoot)) { Reject<InvalidOperationException>(() => foreignAgent.SetNavigationMap(world.NavigationMap)); Check(NavigationServer.AgentGetMap(foreignAgent.GetRID()) != world.NavigationMap, "Foreign scene map rejects before membership mutation."); }
        Reject<InvalidOperationException>(() => NavigationServer.FreeRID(obstacle.GetRID())); agent.SetAvoidanceLayerValue(32, true); agent.SetAvoidanceMaskValue(32, true); Check(agent.GetAvoidanceLayerValue(32) && agent.GetAvoidanceMaskValue(32), "High mask/layer bits."); Reject<ArgumentOutOfRangeException>(() => agent.GetAvoidanceMaskValue(0)); obstacle.SetAvoidanceLayerValue(32, true); Check(obstacle.GetAvoidanceLayerValue(32), "Obstacle source high layer.");
        agent.TargetPosition = new(50, 0); parent.Position = new(50, 0); agent.GetNextPathPosition(); Check(agent.IsNavigationFinished() && NavigationServer.AgentGetVelocity(agent.GetRID()) == Vector2.Zero, "Path completion resets desired and forced simulation velocity."); var rid = obstacle.GetRID(); root.RemoveChild(obstacle); Check(NavigationServer.ObstacleGetMap(rid) == default, "Obstacle exit detaches."); obstacle.Dispose(); Reject<ArgumentException>(() => NavigationServer.ObstacleGetRadius(rid));
        using var packedRoot = new Entity { Name = "Root" }; var sourceAgent = new NavigationAgent { Name = "Agent", AvoidanceEnabled = true, AvoidanceLayers = 3, AvoidanceMask = 5, AvoidancePriority = .25f, Radius = 7, MaxNeighbors = 2, MaxSpeed = 4, NeighborDistance = 90, TimeHorizonAgents = 2, TimeHorizonObstacles = 3, Velocity = new(1, 2), TargetPosition = new(8, 9) }; var sourceObstacle = new NavigationObstacle { Name = "Obstacle", AvoidanceEnabled = false, AvoidanceLayers = 3, Radius = 5, Velocity = Vector2.One, Vertices = [new(0, 0), new(1, 2)] }; packedRoot.AddChild(sourceAgent); packedRoot.AddChild(sourceObstacle); sourceAgent.Owner = sourceObstacle.Owner = packedRoot; using var packed = new PackedScene(); packed.Pack(packedRoot); var file = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "e2d-avoid-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(packed, file); RunChild(file); var start = new ProcessStartInfo("dotnet") { RedirectStandardOutput = true, RedirectStandardError = true }; start.ArgumentList.Add(typeof(NavigationAvoidanceTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_AVOIDANCE"); start.Environment["ELECTRON2D_TEST_AVOIDANCE_CHILD"] = file; using var child = Process.Start(start)!; var output = child.StandardOutput.ReadToEndAsync(); var error = child.StandardError.ReadToEndAsync(); if (!child.WaitForExit(30000)) { child.Kill(true); throw new TimeoutException("Fresh avoidance scene."); } Check(child.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh avoidance scene passed"), error.GetAwaiter().GetResult()); } finally { System.IO.File.Delete(file); }
        var abandoned = Abandon(); GC.Collect(); GC.WaitForPendingFinalizers(); GC.Collect(); Check(!abandoned.Weak.TryGetTarget(out _), "Enabled agent callbacks retain node weakly."); NavigationServer.Synchronize(); Reject<ArgumentException>(() => NavigationServer.AgentGetMap(abandoned.RID));
    }
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static (WeakReference<NavigationAgent> Weak, RID RID) Abandon() { var agent = new NavigationAgent { AvoidanceEnabled = true }; return (new(agent), agent.GetRID()); }
    internal static void RunChild(string file)
    { using var scene = ResourceLoader.Load<PackedScene>(file)!; using var root = (Entity)scene.Instantiate(); var agent = (NavigationAgent)root.GetChild(0); var obstacle = (NavigationObstacle)root.GetChild(1); Check(agent.AvoidanceEnabled && agent.AvoidanceLayers == 3 && agent.AvoidanceMask == 5 && agent.AvoidancePriority == .25f && agent.Radius == 7 && agent.MaxNeighbors == 2 && agent.MaxSpeed == 4 && agent.NeighborDistance == 90 && agent.TimeHorizonAgents == 2 && agent.TimeHorizonObstacles == 3 && agent.Velocity == new Vector2(1, 2) && !obstacle.AvoidanceEnabled && obstacle.Radius == 5 && obstacle.Vertices.Length == 2 && obstacle.Velocity == Vector2.One, "Fresh source configuration."); using var tree = new SceneTree(root); tree.PhysicsFrame(.1); Check(NavigationServer.AgentGetMap(agent.GetRID()) == NavigationServer.ObstacleGetMap(obstacle.GetRID()), "Fresh scene identity/map integration."); Console.WriteLine("Fresh avoidance scene passed."); }
    private static void Oracle()
    {
        if (Environment.GetEnvironmentVariable("ELECTRON2D_AVOIDANCE_ORACLE") is not { } oracle) { Console.WriteLine("Independent ORCA oracle not selected."); return; }
        var random = new Random(137); var compared = 0;
        for (var test = 0; test < 24; test++)
        {
            var map = NavigationServer.MapCreate(); NavigationServer.MapSetActive(map, true); var ids = new List<RID>(); var input = new StringBuilder("0.1 6 1\n");
            for (var i = 0; i < 6; i++) { var position = new Vector2((float)(random.NextDouble() * 30 - 15), (float)(random.NextDouble() * 30 - 15)); var current = new Vector2((float)(random.NextDouble() * 4 - 2), (float)(random.NextDouble() * 4 - 2)); var wanted = new Vector2((float)(random.NextDouble() * 20 - 10), (float)(random.NextDouble() * 20 - 10)); var id = Agent(map, position, wanted); NavigationServer.AgentSetVelocityForced(id, current); ids.Add(id); input.Append(CultureInfo.InvariantCulture, $"{position.X:R} {position.Y:R} {current.X:R} {current.Y:R} {wanted.X:R} {wanted.Y:R} 2 10 100 10 1 1\n"); }
            var vertices = test % 3 == 0 ? new Vector2[] { new(20, -20), new(20, 20) } : test % 3 == 1 ? new Vector2[] { new(18, -3), new(24, -3), new(24, 3), new(18, 3) } : new Vector2[] { new(18, -6), new(24, -6), new(24, 6), new(21, 3), new(18, 6) }; var obstacle = NavigationServer.ObstacleCreate(); NavigationServer.ObstacleSetMap(obstacle, map); NavigationServer.ObstacleSetVertices(obstacle, vertices); input.Append(vertices.Length).Append(' '); foreach (var point in vertices) input.Append(CultureInfo.InvariantCulture, $"{point.X:R} {point.Y:R} "); input.AppendLine();
            var start = new ProcessStartInfo(oracle) { RedirectStandardInput = true, RedirectStandardOutput = true, RedirectStandardError = true }; using var process = Process.Start(start)!; process.StandardInput.Write(input); process.StandardInput.Close(); var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("ORCA oracle."); }
            Check(process.ExitCode == 0, error.GetAwaiter().GetResult()); NavigationServer.Step(.1); var lines = output.GetAwaiter().GetResult().Split('\n', StringSplitOptions.RemoveEmptyEntries); Check(lines.Length == ids.Count, "Oracle velocity count."); for (var i = 0; i < ids.Count; i++) { var parts = lines[i].Split(' ', StringSplitOptions.RemoveEmptyEntries); var expected = new Vector2(float.Parse(parts[0], CultureInfo.InvariantCulture), float.Parse(parts[1], CultureInfo.InvariantCulture)); var actual = NavigationServer.AgentGetVelocity(ids[i]); Check(actual.DistanceTo(expected) < .002f, $"ORCA oracle {test}/{i}: actual {actual}, expected {expected}."); compared++; }
            foreach (var id in ids) NavigationServer.FreeRID(id); NavigationServer.FreeRID(obstacle); NavigationServer.FreeRID(map);
        }
        Console.WriteLine($"Independent pinned C++ ORCA oracle: {compared} agent velocities across 24 disc/wall/convex/concave cases passed.");
    }
    private sealed class Walker : Entity
    {
        internal readonly NavigationAgent Agent = new() { AvoidanceEnabled = true, Radius = 5, NeighborDistance = 120, MaxSpeed = 50, TimeHorizonAgents = 1, TargetDesiredDistance = 1, PathDesiredDistance = 2 };
        internal Vector2 Goal; internal bool Done; internal Color Tint; internal int Deliveries; internal Vector2[] Trail = new Vector2[512]; internal int TrailCount;
        internal Walker() { AddChild(Agent); Agent.VelocityComputed += velocity => { if (!Done) { Position += velocity / 60; if (TrailCount < Trail.Length) Trail[TrailCount++] = Position; Deliveries++; } }; }
        protected override void OnPhysicsProcess(double delta)
        {
            var next = Agent.GetNextPathPosition(); Done = Agent.IsTargetReached();
            if (!Done) { var offset = next - Position; Agent.Velocity = offset.Length() > 0 ? offset.Normalized() * Math.Min(50, offset.Length() * 60) : Vector2.Zero; }
            QueueRedraw();
        }
        protected override void OnDraw() => DrawCircle(Vector2.Zero, 3, Tint);
    }
    private sealed class Playground : Entity
    {
        internal Walker A = null!, B = null!;
        protected override void OnDraw() { DrawRect(new(4, 4, 120, 88), new(.12f, .12f, .12f)); DrawCircle(new(64, 48), 8, Colors.Cyan); if (A.TrailCount > 1) DrawPolyline(A.Trail.AsSpan(0, A.TrailCount), Colors.Yellow, 1); if (B.TrailCount > 1) DrawPolyline(B.Trail.AsSpan(0, B.TrailCount), Colors.Green, 1); }
    }
    internal static void RunHost()
    {
        var backend = Environment.GetEnvironmentVariable("ELECTRON2D_RENDER_BACKEND") ?? "gpu"; ProjectSettings.Set(ProjectSettings.RenderingMethod, backend); ProjectSettings.Set(ProjectSettings.RenderingFallback, false); Engine.MaxFPS = 60;
        using var geometry = NavigationTests.Rectangle(4, 4, 120, 88); var window = new Window { Size = new(128, 96) }; window.AddChild(new NavigationRegion { NavigationPolygon = geometry }); var obstacle = new NavigationObstacle { Radius = 8, Position = new(64, 48) }; window.AddChild(obstacle);
        var a = new Walker { Name = "A", Position = new(16, 40), Goal = new(112, 56), Tint = Colors.Yellow, PhysicsProcessEnabled = true }; var b = new Walker { Name = "B", Position = new(112, 56), Goal = new(16, 40), Tint = Colors.Green, PhysicsProcessEnabled = true }; a.Agent.TargetPosition = a.Goal; b.Agent.TargetPosition = b.Goal;
        a.Agent.Velocity = (a.Goal - a.Position).Normalized() * 50; b.Agent.Velocity = (b.Goal - b.Position).Normalized() * 50; a.Agent.SetVelocityForced(a.Agent.Velocity); b.Agent.SetVelocityForced(b.Agent.Velocity);
        var playground = new Playground { A = a, B = b }; window.AddChild(playground); window.AddChild(a); window.AddChild(b); var frames = 0; var minimumPair = float.MaxValue; var minimumObstacle = float.MaxValue; RID map = default;
        window.Ready += _ =>
        {
            Check(RenderingServer.GetCurrentRenderingMethod() == backend && RenderingServer.GetCurrentRenderingDriverName() != "software", "Requested hardware renderer."); map = window.World!.NavigationMap; RenderingServer.SetDefaultClearColor(Colors.Black);
            RenderingServer.FramePostDraw += () =>
            {
                frames++; playground.QueueRedraw(); minimumPair = Math.Min(minimumPair, a.Position.DistanceTo(b.Position)); minimumObstacle = Math.Min(minimumObstacle, Math.Min(a.Position.DistanceTo(obstacle.Position), b.Position.DistanceTo(obstacle.Position)));
                if (!a.Done || !b.Done) { Check(frames < 480, $"Bounded ORCA host: {a.Position}, {b.Position}."); return; }
                Check(a.Deliveries > 60 && b.Deliveries > 60 && minimumPair > 9.5f && minimumObstacle > 12.5f, $"Actual paths avoid discs: pair {minimumPair}, obstacle {minimumObstacle}.");
                using var pixels = window.GetTexture().GetImage()!; Check(pixels.GetPixel(112, 56).R > .9f && pixels.GetPixel(16, 40).G > .9f, "Two actual avoidance consumers reach rendered goal pixels."); if (Environment.GetEnvironmentVariable("ELECTRON2D_AVOIDANCE_SNAPSHOT") is { } capture) pixels.SavePNG(capture); window.Tree!.Quit();
            };
        };
        Engine.Run(window); Check(window.IsDisposed && RenderingServer.Service is null, "Avoidance scene cleanup."); Reject<ArgumentException>(() => NavigationServer.MapGetAgents(map)); Console.WriteLine($"Native ORCA goals/pixels/cleanup: {backend}, {frames} frames, minimum pair {minimumPair}, obstacle {minimumObstacle}.");
    }
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
