using Electron2D;

internal static class NavigationQueryTests
{
    internal static void Run()
    {
        using var left = NavigationTests.Rectangle(0, 0, 10, 20); using var right = NavigationTests.Rectangle(30, 0, 10, 20); var map = NavigationServer.MapCreate(); var a = NavigationServer.RegionCreate(); var b = NavigationServer.RegionCreate(); var link = NavigationServer.LinkCreate();
        NavigationServer.MapSetActive(map, true); Bind(a, left, 101); Bind(b, right, 202); NavigationServer.LinkSetMap(link, map); NavigationServer.LinkSetStartPosition(link, new(8, 5)); NavigationServer.LinkSetEndPosition(link, new(32, 5)); NavigationServer.LinkSetOwnerID(link, 303); NavigationServer.Synchronize();
        using var parameters = new NavigationPathQueryParameters { Map = map, StartPosition = new(5, 15), TargetPosition = new(35, 15) }; using var result = new NavigationPathQueryResult();
        Check(parameters.Algorithm == NavigationPathQueryParameters.PathfindingAlgorithm.AStar && parameters.PostProcessing == NavigationPathQueryParameters.PathPostProcessing.CorridorFunnel && parameters.MetadataFlags == NavigationPathQueryParameters.PathMetadataFlags.IncludeAll && parameters.NavigationLayers == 1 && parameters.PathSearchMaxPolygons == 4096 && !parameters.SimplifyPath, "Default executable query settings.");
        var callback = 0; NavigationServer.QueryPath(parameters, result, () => { callback++; Check(result.Path.Length == 4 && result.PathTypes[1] == NavigationPathQueryResult.PathSegmentType.Link, "Result publishes before completion callback."); });
        Check(callback == 1 && result.Path.SequenceEqual(NavigationServer.MapGetPath(map, parameters.StartPosition, parameters.TargetPosition, true)), "Default typed query shares the public map path kernel.");
        Check(result.PathTypes.SequenceEqual(new[] { NavigationPathQueryResult.PathSegmentType.Region, NavigationPathQueryResult.PathSegmentType.Link, NavigationPathQueryResult.PathSegmentType.Region, NavigationPathQueryResult.PathSegmentType.Region }) && result.PathRIDs.SequenceEqual(new[] { a, link, b, b }) && result.PathOwnerIDs.SequenceEqual(new ulong[] { 101, 303, 202, 202 }), "Primitive/region-link RID/instance metadata remains parallel and identifies link entry.");
        var expected = result.Path[0].DistanceTo(result.Path[1]) + result.Path[1].DistanceTo(result.Path[2]) + result.Path[2].DistanceTo(result.Path[3]); Check(MathF.Abs(result.PathLength - expected) < .0001f, "Length follows the returned route.");
        var snapshot = result.Path; snapshot[0] = new(99, 99); var owners = result.PathOwnerIDs; owners[0] = 999; Check(result.Path[0] == new Vector2(5, 15) && result.PathOwnerIDs[0] == 101, "Result arrays are independent public copies.");
        for (var flags = 0; flags <= 7; flags++) { parameters.MetadataFlags = (NavigationPathQueryParameters.PathMetadataFlags)flags; NavigationServer.QueryPath(parameters, result); Check(result.PathTypes.Length == ((flags & 1) != 0 ? result.Path.Length : 0) && result.PathRIDs.Length == ((flags & 2) != 0 ? result.Path.Length : 0) && result.PathOwnerIDs.Length == ((flags & 4) != 0 ? result.Path.Length : 0), "Every metadata flag combination selects only its arrays."); }
        parameters.MetadataFlags = NavigationPathQueryParameters.PathMetadataFlags.IncludeAll;
        var included = new[] { a, b }; parameters.IncludedRegions = included; included[0] = default; parameters.IncludedRegions[1] = default; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1] == new Vector2(35, 15), "Include-only filters allow links whose two endpoint regions are included, with copied input/getters.");
        parameters.ExcludedRegions = [b]; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1].X <= 10 && !result.PathTypes.Contains(NavigationPathQueryResult.PathSegmentType.Link), "Exclusion wins over inclusion for projection and link traversal."); parameters.ExcludedRegions = []; parameters.IncludedRegions = [a]; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1].X <= 10, "One included endpoint cannot route through a link into an unincluded region."); parameters.IncludedRegions = [];
        parameters.StartPosition = new(5, 5); parameters.TargetPosition = new(35, 5); NavigationServer.QueryPath(parameters, result); Check(result.PathTypes.Contains(NavigationPathQueryResult.PathSegmentType.Link) && result.Path.SequenceEqual(new Vector2[] { new(5, 5), new(8, 5), new(32, 5), new(35, 5) }), "Collinear funnel paths retain executable link transition markers.");
        parameters.PathSearchMaxPolygons = 1; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1].X <= 10, "Bounded polygon search returns the closest processed region surface."); parameters.PathSearchMaxPolygons = 0; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1].X == 35, "Nonpositive count is unlimited."); parameters.PathSearchMaxDistance = 2; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1].X <= 10, "Entry-distance search budget stops expansion before the remote region."); parameters.PathSearchMaxDistance = 0;
        parameters.PathReturnMaxLength = 10; NavigationServer.QueryPath(parameters, result); Check(MathF.Abs(result.PathLength - 10) < .0001f && result.Path[^1].IsEqualApprox(new(15, 5)), "World-length clipping interpolates the last segment."); parameters.PathReturnMaxLength = 0; parameters.PathReturnMaxRadius = 12; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1].IsEqualApprox(new(17, 5)) && MathF.Abs(result.PathLength - 12) < .0001f, "Circle clipping uses the projected route origin."); parameters.PathReturnMaxLength = 6; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1].IsEqualApprox(new(11, 5)) && result.PathRIDs.Length == result.Path.Length, "The tighter clipping limit wins and metadata is trimmed in parallel."); parameters.PathReturnMaxLength = 0; parameters.PathReturnMaxRadius = 0;
        parameters.SimplifyPath = true; parameters.SimplifyEpsilon = 0; NavigationServer.QueryPath(parameters, result); Check(result.Path.Length == 2 && result.PathTypes.Length == 2 && result.PathOwnerIDs.Length == 2, "Explicit simplification selects the same point indices across all arrays."); parameters.SimplifyPath = false;
        foreach (var mode in Enum.GetValues<NavigationPathQueryParameters.PathPostProcessing>()) { parameters.PostProcessing = mode; NavigationServer.QueryPath(parameters, result); Check(result.Path[^1].X == 35 && result.PathTypes.Contains(NavigationPathQueryResult.PathSegmentType.Link), "All postprocessing modes execute on real linked topology."); }
        parameters.PostProcessing = NavigationPathQueryParameters.PathPostProcessing.CorridorFunnel;
        parameters.NavigationLayers = 0; NavigationServer.QueryPath(parameters, result, () => Check(result.Path.Length == 0 && result.PathLength == 0 && result.PathOwnerIDs.Length == 0, "Empty filtered query publishes complete empty data before callback.")); parameters.NavigationLayers = 1; NavigationServer.QueryPath(parameters, result);
        var before = result.Path; parameters.Map = a; Reject<ArgumentException>(() => NavigationServer.QueryPath(parameters, result, () => callback++)); Check(result.Path.SequenceEqual(before) && callback == 1, "Invalid map rejects before publication/callback and preserves result."); parameters.Map = map;
        Reject<InvalidOperationException>(() => NavigationServer.QueryPath(parameters, result, () => throw new InvalidOperationException("Completion"))); Check(result.Path[^1].X == 35, "Completion failure preserves the published result.");
        NavigationServer.QueryPath(parameters, result, () => { parameters.TargetPosition = new(6, 5); NavigationServer.QueryPath(parameters, result); }); Check(result.Path[^1] == new Vector2(6, 5), "Callback can stage settings and run a nested query after publication."); parameters.TargetPosition = new(35, 5);
        NavigationServer.RegionSetOwnerID(a, 404); NavigationServer.QueryPath(parameters, result); Check(result.PathOwnerIDs[0] == 101, "Owner metadata remains committed until map sync."); NavigationServer.Synchronize(); NavigationServer.QueryPath(parameters, result); Check(result.PathOwnerIDs[0] == 404, "Region owner edits republish actual result metadata.");
        parameters.PathReturnMaxLength = -2; parameters.PathReturnMaxRadius = -2; parameters.PathSearchMaxDistance = -2; parameters.SimplifyEpsilon = -2; Check(parameters.PathReturnMaxLength == 0 && parameters.PathReturnMaxRadius == 0 && parameters.PathSearchMaxDistance == 0 && parameters.SimplifyEpsilon == 0, "Float limits and epsilon clamp negative input to zero.");
        Reject<ArgumentOutOfRangeException>(() => parameters.StartPosition = new(float.NaN, 0)); Reject<ArgumentOutOfRangeException>(() => parameters.Algorithm = (NavigationPathQueryParameters.PathfindingAlgorithm)1); Reject<ArgumentOutOfRangeException>(() => parameters.PostProcessing = (NavigationPathQueryParameters.PathPostProcessing)99); Reject<ArgumentOutOfRangeException>(() => parameters.MetadataFlags = (NavigationPathQueryParameters.PathMetadataFlags)8); Reject<ArgumentOutOfRangeException>(() => parameters.PathReturnMaxRadius = float.PositiveInfinity);
        Check(parameters.GetPropertyList().Count(p => p.OwnerType == typeof(NavigationPathQueryParameters)) == 15 && result.GetPropertyList().Count(p => p.OwnerType == typeof(NavigationPathQueryResult)) == 5, "Typed discovery exposes complete own properties.");
        result.Reset(); Check(result.Path.Length == 0 && result.PathRIDs.Length == 0 && result.PathTypes.Length == 0 && result.PathOwnerIDs.Length == 0 && result.PathLength == 0, "Reset clears length and all arrays.");
        var custom = new[] { Vector2.Zero, Vector2.One }; result.Path = custom; custom[0] = new(9, 9); result.PathLength = 2; Check(result.Path[0] == Vector2.Zero && result.PathLength == 2, "Independent user result setters preserve copied data."); Reject<ArgumentOutOfRangeException>(() => result.Path = [new(float.NaN, 0)]);
        for (var i = 0; i < 64; i++) { parameters.TargetPosition = new(35 + (i & 1), 5); _ = parameters.PathSearchMaxPolygons; result.Reset(); }
        var allocated = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 2000; i++) { parameters.TargetPosition = new(35 + (i & 1), 5); _ = parameters.PathSearchMaxPolygons; result.Reset(); }
        Check(GC.GetAllocatedBytesForCurrentThread() == allocated, "2000 changing scalar settings/result-reset cycles allocate zero bytes, excluding query/array copies.");
        NavigationServer.FreeRID(link); NavigationServer.FreeRID(a); NavigationServer.FreeRID(b); NavigationServer.FreeRID(map); Reject<ArgumentException>(() => NavigationServer.QueryPath(parameters, result));
        using var disposed = new NavigationPathQueryResult(); disposed.Dispose(); Reject<ObjectDisposedException>(() => NavigationServer.QueryPath(parameters, disposed));
        Simplification(); PostProcessing(); Console.WriteLine("Typed navigation query filters, metadata, limits, modes, simplification, callbacks, lifetime and scalar allocation checks passed.");
        void Bind(RID rid, NavigationPolygon polygon, ulong owner) { NavigationServer.RegionSetMap(rid, map); NavigationServer.RegionSetNavigationPolygon(rid, polygon); NavigationServer.RegionSetOwnerID(rid, owner); }
    }
    private static void Simplification()
    {
        Check(NavigationServer.SimplifyPath([], 1).Length == 0 && NavigationServer.SimplifyPath([new(2, 3)], 0).SequenceEqual(new[] { new Vector2(2, 3) }), "Empty/singleton simplification boundaries."); var points = new Vector2[] { new(0, 0), new(1, 1), new(2, 0) }; Check(NavigationServer.SimplifyPath(points, 1).Length == 2 && NavigationServer.SimplifyPath(points, .9f).Length == 3, "RDP uses a strict epsilon distance boundary."); Check(points[1] == Vector2.One, "Simplification never mutates input."); Reject<ArgumentOutOfRangeException>(() => NavigationServer.SimplifyPath(points, float.NaN)); Reject<ArgumentOutOfRangeException>(() => NavigationServer.SimplifyPath([new(float.PositiveInfinity, 0)], 1));
        var longPath = Enumerable.Range(0, 4000).Select(i => new Vector2(i, i % 2)).ToArray(); Check(NavigationServer.SimplifyPath(longPath, 0).Length == 4000, "Iterative point decimation avoids recursive depth failure.");
    }
    private static void PostProcessing()
    {
        using var polygon = new NavigationPolygon(); polygon.SetVertices([new(0, 0), new(10, 0), new(10, 20), new(0, 20), new(20, 0), new(20, 20), new(30, 0), new(30, 20)]); polygon.AddPolygon([0, 1, 2, 3]); polygon.AddPolygon([1, 4, 5, 2]); polygon.AddPolygon([4, 6, 7, 5]); var map = NavigationServer.MapCreate(); var region = NavigationServer.RegionCreate(); NavigationServer.MapSetActive(map, true); NavigationServer.RegionSetMap(region, map); NavigationServer.RegionSetNavigationPolygon(region, polygon); NavigationServer.Synchronize(); using var p = new NavigationPathQueryParameters { Map = map, StartPosition = new(5, 5), TargetPosition = new(25, 5) }; using var r = new NavigationPathQueryResult();
        p.PostProcessing = NavigationPathQueryParameters.PathPostProcessing.None; NavigationServer.QueryPath(p, r); Check(r.Path.SequenceEqual(new Vector2[] { new(5, 5), new(10, 5), new(20, 5), new(25, 5) }), "Raw entries preserve the nearest crossed positions."); p.PostProcessing = NavigationPathQueryParameters.PathPostProcessing.EdgeCentered; NavigationServer.QueryPath(p, r); Check(r.Path.SequenceEqual(new Vector2[] { new(5, 5), new(10, 10), new(20, 10), new(25, 5) }), "Edge-centered mode moves points to actual polygon edge centers."); p.PathReturnMaxRadius = 8; NavigationServer.QueryPath(p, r); Check(r.Path[^1].IsEqualApprox(new(5 + MathF.Sqrt(39), 10)) && r.PathLength > 8, "Circle radius clips a bent path independently of traveled length."); p.PathReturnMaxLength = 8; NavigationServer.QueryPath(p, r); Check(MathF.Abs(r.PathLength - 8) < .0001f && r.Path[^1].IsEqualApprox(new(10 + 8 - MathF.Sqrt(50), 10)), "Combined limits choose the tighter traveled length on a bent segment."); p.PathReturnMaxRadius = 0; p.PathReturnMaxLength = 0;
        p.PostProcessing = NavigationPathQueryParameters.PathPostProcessing.CorridorFunnel; NavigationServer.QueryPath(p, r); Check(r.Path.SequenceEqual(new Vector2[] { new(5, 5), new(10, 5), new(20, 5), new(25, 5) }), "Funnel keeps crossed-edge provenance on a straight corridor."); p.PathReturnMaxRadius = 8; p.PathReturnMaxLength = 0; NavigationServer.QueryPath(p, r); Check(r.Path[^1].IsEqualApprox(new(13, 5)), "Circle clipping crosses an ordinary region segment."); NavigationServer.FreeRID(region); NavigationServer.FreeRID(map);
    }
    private sealed class Traveler : Entity
    {
        internal NavigationLink Link = null!; internal Vector2[] Path = []; internal bool Done; internal int Teleports; private NavigationPathQueryResult.PathSegmentType[] _types = []; private RID[] _rids = []; private ulong[] _owners = []; private int _next = 1;
        private readonly NavigationPathQueryParameters _parameters = new() { PostProcessing = NavigationPathQueryParameters.PathPostProcessing.None }; private readonly NavigationPathQueryResult _result = new();
        protected override void OnPhysicsProcess(double delta)
        {
            if (Path.Length == 0) { _parameters.Map = GetWorld()!.NavigationMap; _parameters.StartPosition = Position; _parameters.TargetPosition = new(44, 44); NavigationServer.QueryPath(_parameters, _result); Path = _result.Path; _types = _result.PathTypes; _rids = _result.PathRIDs; _owners = _result.PathOwnerIDs; Check(Path.SequenceEqual(new Vector2[] { new(12, 44), new(18, 12), new(38, 12), new(44, 44) }), "Native typed query produces the linked route."); }
            var remaining = (float)(delta * 200); while (_next < Path.Length && remaining > 0) { var difference = Path[_next] - Position; var distance = difference.Length(); if (distance > remaining) { Position += difference / distance * remaining; break; } Position = Path[_next]; remaining -= distance; if (_types[_next] == NavigationPathQueryResult.PathSegmentType.Link) { Check(_rids[_next] == Link.GetRID() && _owners[_next] == Link.InstanceID, "Native transition resolves exact link/scene owner metadata."); Position = Path[_next + 1]; _next += 2; Teleports++; } else _next++; }
            Done = _next == Path.Length;
        }
        protected override void OnDraw() => DrawRect(new(-2, -2, 4, 4), Colors.Yellow);
        protected override void Dispose(bool disposing) { if (disposing) { _parameters.Dispose(); _result.Dispose(); } base.Dispose(disposing); }
    }
    private sealed class Journey : Entity
    {
        internal Traveler Traveler = null!;
        protected override void OnDraw() { DrawRect(new(4, 4, 16, 48), new(.2f, .2f, .2f)); DrawRect(new(36, 4, 16, 48), new(.2f, .2f, .2f)); if (Traveler.Path.Length > 1) DrawPolyline(Traveler.Path, Colors.Green, 2); DrawCircle(new(18, 12), 2, Colors.Cyan); DrawCircle(new(38, 12), 2, Colors.Cyan); }
    }
    internal static void RunHost()
    {
        var backend = Environment.GetEnvironmentVariable("ELECTRON2D_RENDER_BACKEND") ?? "gpu"; ProjectSettings.Set(ProjectSettings.RenderingMethod, backend); ProjectSettings.Set(ProjectSettings.RenderingFallback, false); Engine.MaxFPS = 60; using var left = NavigationTests.Rectangle(4, 4, 16, 48); using var right = NavigationTests.Rectangle(36, 4, 16, 48); var window = new Window { Size = new(64, 64) };
        window.AddChild(new NavigationRegion { Name = "Left", NavigationPolygon = left }); window.AddChild(new NavigationRegion { Name = "Right", NavigationPolygon = right }); var link = new NavigationLink { Name = "Teleporter", StartPosition = new(18, 12), EndPosition = new(38, 12), Bidirectional = false }; window.AddChild(link); var actor = new Traveler { Link = link, Position = new(12, 44), PhysicsProcessEnabled = true }; var journey = new Journey { Traveler = actor }; window.AddChild(journey); window.AddChild(actor); var frames = 0; RID map = default;
        window.Ready += _ => { Check(RenderingServer.GetCurrentRenderingMethod() == backend && RenderingServer.GetCurrentRenderingDriverName() != "software", "Requested hardware backend."); map = window.World!.NavigationMap; RenderingServer.SetDefaultClearColor(Colors.Black); RenderingServer.FramePostDraw += () => { frames++; journey.QueueRedraw(); if (!actor.Done) { Check(frames < 180, "Bounded metadata-driven navigation host."); return; } Check(actor.Teleports == 1, "Native actor executes exactly one metadata-driven teleport."); using var pixels = window.GetTexture().GetImage()!; Check(pixels.GetPixel(44, 44).R > .9f && pixels.GetPixel(44, 44).G > .9f, "Native metadata-driven actor reaches goal pixels."); if (Environment.GetEnvironmentVariable("ELECTRON2D_NAVIGATION_QUERY_SNAPSHOT") is { } capture) pixels.SavePNG(capture); window.Tree!.Quit(); }; };
        Engine.Run(window); Check(window.IsDisposed && RenderingServer.Service is null, "Native typed-query scene teardown."); Reject<ArgumentException>(() => NavigationServer.MapGetLinks(map)); Console.WriteLine($"Typed navigation metadata teleport/pixels/cleanup passed: {backend}, {frames} frames.");
    }
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
