using Electron2D;

internal static class NavigationAgentTests
{
    internal static void Run()
    {
        var map = NavigationServer.MapCreate(); var rid = NavigationServer.AgentCreate(); Check(NavigationServer.AgentGetMap(rid) == default && !NavigationServer.AgentIsMapChanged(rid), "Detached agent identity."); NavigationServer.AgentSetMap(rid, map); Check(NavigationServer.MapGetAgents(map).SequenceEqual(new[] { rid }), "Real map membership."); NavigationServer.MapSetActive(map, true); NavigationServer.Synchronize(); Check(NavigationServer.AgentIsMapChanged(rid) && !NavigationServer.AgentIsMapChanged(rid), "Map version is consumed once."); NavigationServer.FreeRID(map); Check(NavigationServer.AgentGetMap(rid) == default, "Map release detaches agents."); NavigationServer.FreeRID(rid); Reject<ArgumentException>(() => NavigationServer.AgentGetMap(rid));
        using var polygon = NavigationTests.Rectangle(0, 0, 100, 100); var root = new SubViewport(); var region = new NavigationRegion { NavigationPolygon = polygon }; var parent = new Entity { Position = new(5, 5), Name = "Actor" }; var agent = new NavigationAgent { Name = "Agent", PathDesiredDistance = 1, TargetDesiredDistance = 1, TargetPosition = new(80, 5) }; parent.AddChild(agent); root.AddChild(parent); root.AddChild(region); using var tree = new SceneTree(root); tree.PhysicsFrame(0);
        Reject<InvalidOperationException>(() => agent.GetCurrentNavigationResult().Dispose()); var aid = agent.GetRID(); Reject<InvalidOperationException>(() => NavigationServer.FreeRID(aid)); Check(NavigationServer.AgentGetMap(aid) == root.World!.NavigationMap && agent.GetConfigurationWarnings().Length == 0, "Attached parent World membership and warnings.");
        var events = new List<string>(); agent.PathChanged += () => events.Add("path"); agent.WaypointReached += _ => events.Add("waypoint"); agent.TargetReached += () => events.Add("target"); agent.NavigationFinished += () => events.Add("finished");
        Check(agent.GetNextPathPosition() == new Vector2(80, 5) && agent.GetCurrentNavigationPathIndex() == 1 && agent.GetPathLength() == 75 && agent.IsTargetReachable(), "Initial waypoint advances and path length/target reachability execute."); Check(events.SequenceEqual(new[] { "path", "waypoint" }), "Path publication before first waypoint."); var copy = agent.GetCurrentNavigationPath(); copy[1] = Vector2.Zero; Check(agent.GetCurrentNavigationPath()[1].X == 80, "Path is copied.");
        parent.Position = new(79, 5); agent.GetNextPathPosition(); Check(!agent.IsTargetReached(), "Strict target distance boundary."); parent.Position = new(80, 5); agent.GetNextPathPosition(); Check(agent.IsTargetReached() && agent.IsNavigationFinished() && events.TakeLast(3).SequenceEqual(new[] { "waypoint", "target", "finished" }), "Final waypoint, target and completion order."); var count = events.Count; agent.GetNextPathPosition(); Check(events.Count == count, "Finished requests do not repeat events."); agent.GetCurrentNavigationResult().Path = []; Check(agent.GetNextPathPosition() == parent.Position && agent.GetCurrentNavigationPathIndex() == 0, "Completed requests safely observe external empty result edits.");
        agent.TargetPosition = agent.TargetPosition; Check(agent.GetCurrentNavigationPath().Length == 0 && !agent.IsTargetReached(), "Equal target submission repaths."); agent.GetNextPathPosition(); agent.TargetPosition = new(200, 5); agent.GetNextPathPosition(); Check(agent.GetFinalPosition() == new Vector2(100, 5) && !agent.IsTargetReachable(), "Unreachable target projects to final position."); parent.Position = new(100, 5); agent.GetNextPathPosition(); Check(agent.IsNavigationFinished() && !agent.IsTargetReached(), "Unreachable final waypoint completes without reaching target.");
        parent.Position = new(5, 5); agent.TargetPosition = new(80, 5); agent.GetNextPathPosition(); agent.PathMaxDistance = 5; parent.Position = new(5, 10); count = events.Count(x => x == "path"); agent.GetNextPathPosition(); Check(events.Count(x => x == "path") == count + 1 && agent.GetCurrentNavigationPath()[0] == parent.Position, "Inclusive off-path distance reload."); agent.PathMaxDistance = 100;
        count = events.Count(x => x == "path"); NavigationServer.RegionSetTravelCost(region.GetRID(), 2); NavigationServer.Synchronize(); agent.GetNextPathPosition(); Check(events.Count(x => x == "path") == count + 1, "Committed map edit reloads active request.");
        agent.NavigationLayers = 0; Check(agent.GetNextPathPosition() == parent.Position && agent.GetCurrentNavigationPath().Length == 0 && !agent.IsNavigationFinished(), "Empty filtered route stays unfinished."); agent.NavigationLayers = 1; agent.GetNextPathPosition(); agent.GetCurrentNavigationResult().Path = [Vector2.Zero]; agent.GetNextPathPosition(); Check(agent.GetCurrentNavigationPath().Length >= 2, "Externally replaced borrowed result safely repaths.");
        agent.PathMetadataFlags = NavigationPathQueryParameters.PathMetadataFlags.IncludeNone; agent.TargetPosition = new(70, 5); NavigationWaypoint? details = null; void Capture(NavigationWaypoint p) => details = p; agent.WaypointReached += Capture; agent.GetNextPathPosition(); Check(details is { Type: null, RID: null, OwnerID: null, Owner: null }, "Omitted metadata has typed absence."); agent.WaypointReached -= Capture;
        agent.TargetPosition = new(60, 5); var later = 0; Action fail = () => { Reject<InvalidOperationException>(() => agent.GetNextPathPosition()); Reject<InvalidOperationException>(() => agent.TargetPosition = Vector2.One); Reject<InvalidOperationException>(() => agent.Dispose()); throw new InvalidOperationException("Observer"); }; Action subsequent = () => later++; agent.PathChanged += fail; agent.PathChanged += subsequent; Reject<AggregateException>(() => agent.GetNextPathPosition()); agent.PathChanged -= fail; agent.PathChanged -= subsequent; Check(later == 1 && agent.GetCurrentNavigationPathIndex() == 1, "Reentry/mutation/disposal reject; later observers and progression still execute."); agent.GetNextPathPosition();
        agent.SetNavigationLayerValue(32, true); Check(agent.GetNavigationLayerValue(32), "High navigation bit."); Reject<ArgumentOutOfRangeException>(() => agent.GetNavigationLayerValue(0)); Reject<ArgumentOutOfRangeException>(() => agent.PathDesiredDistance = float.NaN); Reject<ArgumentOutOfRangeException>(() => agent.TargetPosition = new(float.PositiveInfinity, 0)); agent.PathReturnMaxLength = -1; Check(agent.PathReturnMaxLength == 0, "Query limit clamping."); agent.PathDesiredDistance = -1; agent.TargetPosition = new(60, 5); agent.GetNextPathPosition(); Check(agent.GetCurrentNavigationPathIndex() == 0, "Finite signed threshold preserves no-advance semantics."); agent.PathDesiredDistance = 1; agent.GetNextPathPosition();
        for (var i = 0; i < 64; i++) { agent.GetNextPathPosition(); _ = agent.GetPathLength(); }
        var allocation = GC.GetAllocatedBytesForCurrentThread(); for (var i = 0; i < 2000; i++) { agent.GetNextPathPosition(); _ = agent.GetPathLength(); }
        Check(GC.GetAllocatedBytesForCurrentThread() == allocation, "2000 warmed following updates allocate zero bytes, excluding queries and public array copies.");
        using var world = new World(); root.World = world; tree.PhysicsFrame(0); Check(agent.GetRID() == aid && NavigationServer.AgentGetMap(aid) == world.NavigationMap, "World replacement transfers node-owned agent."); var overrideMap = NavigationServer.MapCreate(); agent.SetNavigationMap(overrideMap); Check(agent.GetNavigationMap() == overrideMap, "Explicit map."); agent.SetNavigationMap(default); Check(agent.GetNavigationMap() == world.NavigationMap, "Empty restores World."); NavigationServer.FreeRID(overrideMap);
        parent.RemoveChild(agent); Check(NavigationServer.AgentGetMap(aid) == default, "Exit detaches agent."); Reject<InvalidOperationException>(() => agent.GetNextPathPosition()); parent.AddChild(agent); Check(NavigationServer.AgentGetMap(aid) == world.NavigationMap, "Reentry restores membership.");
        agent.PathReturnMaxLength = 10; agent.TargetPosition = new(80, 5); var clip = agent.GetFinalPosition(); Check(Math.Abs(agent.GetPathLength() - 10) < .001f && !agent.IsTargetReachable(), "Agent output limit executes in shared query."); parent.Position = clip; Check(agent.IsNavigationFinished(), "Clipped unreachable endpoint completes."); agent.PathReturnMaxLength = 0;
        using var callbackWorld = new World(); agent.TargetPosition = new(80, 5); Action swap = () => root.World = callbackWorld; agent.PathChanged += swap; agent.GetNextPathPosition(); agent.PathChanged -= swap; Check(agent.GetCurrentNavigationPath().Length == 0 && NavigationServer.AgentGetMap(aid) == callbackWorld.NavigationMap, "Callback World rebind aborts stale progression and invalidates after delivery."); agent.GetNextPathPosition();
        Check(Task.Run(() => { try { agent.GetNextPathPosition(); return false; } catch (InvalidOperationException) { return true; } }).GetAwaiter().GetResult(), "Attached agent requires the scene owner.");
        Storage(); Links(); WeakLifetime(); Console.WriteLine("Navigation agent path following, thresholds, events, reentry, map lifecycle, metadata, storage and allocation passed.");
    }
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static (WeakReference<NavigationAgent> Weak, RID RID) Abandon() { var agent = new NavigationAgent(); return (new(agent), agent.GetRID()); }
    private static void WeakLifetime() { var value = Abandon(); GC.Collect(); GC.WaitForPendingFinalizers(); GC.Collect(); Check(!value.Weak.TryGetTarget(out _), "Agent/result ownership cycle is collected through weak server registration."); NavigationServer.Synchronize(); Reject<ArgumentException>(() => NavigationServer.AgentGetMap(value.RID)); }
    private static void Links()
    {
        using var left = NavigationTests.Rectangle(0, 0, 10, 10); using var right = NavigationTests.Rectangle(30, 0, 10, 10); var root = new SubViewport(); root.AddChild(new NavigationRegion { Name = "Left", NavigationPolygon = left }); root.AddChild(new NavigationRegion { Name = "Right", NavigationPolygon = right }); var link = new NavigationLink { StartPosition = new(8, 5), EndPosition = new(32, 5) }; root.AddChild(link); var parent = new Entity { Position = new(5, 5) }; var agent = new NavigationAgent { TargetPosition = new(35, 5), PathDesiredDistance = .5f, TargetDesiredDistance = .5f }; parent.AddChild(agent); root.AddChild(parent); using var tree = new SceneTree(root); tree.PhysicsFrame(0); NavigationWaypoint? transition = null; agent.LinkReached += p => { transition = p; parent.Position = p.LinkExitPosition!.Value; }; agent.GetNextPathPosition(); parent.Position = new(8, 5); agent.GetNextPathPosition(); Check(transition is { Owner: NavigationLink } && transition.Value.RID == link.GetRID() && transition.Value.OwnerID == link.InstanceID && transition.Value.LinkEntryPosition == new Vector2(8, 5) && parent.Position == new Vector2(32, 5), "Typed scene owner and directional endpoints execute link transition."); agent.GetNextPathPosition(); parent.Position = new(35, 5); Check(agent.IsNavigationFinished(), "Link traveler reaches final target."); parent.Position = new(35, 5); agent.TargetPosition = new(5, 5); agent.GetNextPathPosition(); parent.Position = new(32, 5); agent.GetNextPathPosition(); Check(parent.Position == new Vector2(8, 5) && transition!.Value.LinkEntryPosition == new Vector2(32, 5), "Reverse traversal swaps typed endpoints.");
    }
    private static void Storage()
    {
        using var actor = new Entity { Name = "Actor" }; var agent = new NavigationAgent { Name = "Agent", NavigationLayers = 3, PathDesiredDistance = 2, TargetDesiredDistance = 3, PathMaxDistance = 4, TargetPosition = new(12, 13), SimplifyPath = true, SimplifyEpsilon = 2, PathReturnMaxRadius = 50, PathReturnMaxLength = 60, PathSearchMaxPolygons = -1, PathSearchMaxDistance = 70, PathPostprocessing = NavigationPathQueryParameters.PathPostProcessing.None, PathMetadataFlags = NavigationPathQueryParameters.PathMetadataFlags.IncludeOwners }; actor.AddChild(agent); agent.Owner = actor; using var packed = new PackedScene(); packed.Pack(actor); var file = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "e2d-agent-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(packed, file); RunChild(file); var start = new System.Diagnostics.ProcessStartInfo("dotnet") { RedirectStandardOutput = true, RedirectStandardError = true }; start.ArgumentList.Add(typeof(NavigationAgentTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_NAVIGATION_AGENT"); start.Environment["ELECTRON2D_TEST_NAVIGATION_AGENT_CHILD"] = file; using var child = System.Diagnostics.Process.Start(start)!; var output = child.StandardOutput.ReadToEndAsync(); var error = child.StandardError.ReadToEndAsync(); if (!child.WaitForExit(30000)) { child.Kill(true); throw new TimeoutException("Fresh agent scene."); } Check(child.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh navigation agent scene passed"), error.GetAwaiter().GetResult()); } finally { System.IO.File.Delete(file); }
    }
    internal static void RunChild(string file)
    { using var packed = ResourceLoader.Load<PackedScene>(file)!; using var actor = (Entity)packed.Instantiate(); var agent = (NavigationAgent)actor.GetChild(0); Check(agent.NavigationLayers == 3 && agent.TargetPosition == new Vector2(12, 13) && agent.PathDesiredDistance == 2 && agent.TargetDesiredDistance == 3 && agent.PathMaxDistance == 4 && agent.SimplifyPath && agent.SimplifyEpsilon == 2 && agent.PathReturnMaxLength == 60 && agent.PathReturnMaxRadius == 50 && agent.PathSearchMaxPolygons == -1 && agent.PathSearchMaxDistance == 70 && agent.PathPostprocessing == NavigationPathQueryParameters.PathPostProcessing.None && agent.PathMetadataFlags == NavigationPathQueryParameters.PathMetadataFlags.IncludeOwners && agent.GetPropertyList().Count(p => p.OwnerType == typeof(NavigationAgent)) == 25, "Fresh typed agent settings."); using var tree = new SceneTree(actor); tree.PhysicsFrame(0); Check(NavigationServer.MapGetAgents(agent.GetNavigationMap()).Contains(agent.GetRID()), "Fresh loaded agent registers real map membership."); Console.WriteLine("Fresh navigation agent scene passed."); }
    private sealed class Traveler : Entity
    {
        internal NavigationLink Link = null!; internal Vector2[] Path = []; internal bool Done; internal int Teleports; internal readonly NavigationAgent Agent = new() { PathDesiredDistance = .1f, TargetDesiredDistance = .1f, PathPostprocessing = NavigationPathQueryParameters.PathPostProcessing.None, TargetPosition = new(44, 44) };
        internal Traveler()
        {
            AddChild(Agent);
            Agent.LinkReached += details => { Check(details.Owner == Link && details.RID == Link.GetRID(), "Native agent resolves scene link."); Position = details.LinkExitPosition!.Value; Teleports++; };
        }
        protected override void OnPhysicsProcess(double delta)
        {
            var before = Teleports; var next = Agent.GetNextPathPosition(); if (Teleports != before) return; if (Path.Length == 0) Path = Agent.GetCurrentNavigationPath();
            if (Agent.IsTargetReached()) { Done = Agent.IsNavigationFinished(); return; }
            var difference = next - Position; var distance = difference.Length(); var step = (float)(delta * 200);
            if (distance <= step) Position = next; else Position += difference / distance * step;
            QueueRedraw();
        }
        protected override void OnDraw() => DrawRect(new(-2, -2, 4, 4), Colors.Yellow);
    }
    private sealed class Journey : Entity
    {
        internal Traveler Traveler = null!;
        protected override void OnDraw() { DrawRect(new(4, 4, 16, 48), new(.2f, .2f, .2f)); DrawRect(new(36, 4, 16, 48), new(.2f, .2f, .2f)); if (Traveler.Path.Length > 1) DrawPolyline(Traveler.Path, Colors.Green, 2); DrawCircle(new(18, 12), 2, Colors.Cyan); DrawCircle(new(38, 12), 2, Colors.Cyan); }
    }
    internal static void RunHost()
    {
        var backend = Environment.GetEnvironmentVariable("ELECTRON2D_RENDER_BACKEND") ?? "gpu"; ProjectSettings.Set(ProjectSettings.RenderingMethod, backend); ProjectSettings.Set(ProjectSettings.RenderingFallback, false); Engine.MaxFPS = 60; using var left = NavigationTests.Rectangle(4, 4, 16, 48); using var right = NavigationTests.Rectangle(36, 4, 16, 48); var window = new Window { Size = new(64, 64) };
        window.AddChild(new NavigationRegion { Name = "Left", NavigationPolygon = left }); window.AddChild(new NavigationRegion { Name = "Right", NavigationPolygon = right }); var link = new NavigationLink { Name = "Teleporter", StartPosition = new(18, 12), EndPosition = new(38, 12), Bidirectional = false }; window.AddChild(link); var actor = new Traveler { Link = link, Position = new(12, 44), PhysicsProcessEnabled = true }; var journey = new Journey { Traveler = actor }; window.AddChild(journey); window.AddChild(actor); var frames = 0; RID map = default;
        window.Ready += _ => { Check(RenderingServer.GetCurrentRenderingMethod() == backend && RenderingServer.GetCurrentRenderingDriverName() != "software", "Requested hardware backend."); map = window.World!.NavigationMap; RenderingServer.SetDefaultClearColor(Colors.Black); RenderingServer.FramePostDraw += () => { frames++; journey.QueueRedraw(); if (!actor.Done) { Check(frames < 180, "Bounded metadata-driven navigation host."); return; } Check(actor.Agent.IsTargetReached() && actor.Agent.IsNavigationFinished(), "Agent emits target and navigation completion."); Check(actor.Teleports == 1, "Native actor executes exactly one metadata-driven teleport."); using var pixels = window.GetTexture().GetImage()!; Check(pixels.GetPixel(44, 44).R > .9f && pixels.GetPixel(44, 44).G > .9f, "Native metadata-driven actor reaches goal pixels."); if (Environment.GetEnvironmentVariable("ELECTRON2D_NAVIGATION_AGENT_SNAPSHOT") is { } capture) pixels.SavePNG(capture); window.Tree!.Quit(); }; };
        Engine.Run(window); Check(window.IsDisposed && RenderingServer.Service is null, "Native navigation-agent scene teardown."); Reject<ArgumentException>(() => NavigationServer.MapGetLinks(map)); Console.WriteLine($"Navigation agent teleport/pixels/cleanup passed: {backend}, {frames} frames.");
    }
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
