using Electron2D;

internal static class OptionButtonTests
{
    internal static void Run()
    {
        using var detached = new OptionButton(); Check(detached.ItemCount == 0 && detached.Selected == -1 && detached.FitToLongestItem && !detached.AllowReselect && detached.ToggleMode && detached.ActionMode == ButtonActionMode.ButtonPress && detached.Alignment == HorizontalAlignment.Left, "Option defaults.");
        detached.AddSeparator("Group"); detached.AddItem("One", 42); detached.AddItem("Two", 84); Check(detached.Selected == 1 && detached.GetSelectedID() == 42 && detached.GetPopup().IsItemChecked(1), "First selectable item selects with radio decoration.");
        detached.Select(2); detached.RemoveItem(0); Check(detached.Selected == 1 && detached.Text == "Two" && detached.GetSelectedID() == 84, "Removal before selection preserves identity."); detached.SetItemText(-1, "Changed"); Check(detached.Text == "Changed", "End-relative selected edits refresh caption."); detached.SetItemMetadata<string?>(1, null); Check(detached.GetSelectedMetadata<string?>() == null, "Exact typed null metadata."); Reject<KeyNotFoundException>(() => detached.GetSelectedMetadata<int>()); detached.RemoveItem(1); Check(detached.Selected == -1 && detached.Text == "" && detached.GetSelectedID() == -1, "Selected removal clears caption and identity.");
        detached.Selected = 2; detached.ItemCount = 3; Check(detached.Selected == 2 && detached.GetPopup().IsItemRadioCheckable(2), "Initial queued selection applies to count configuration."); detached.Select(1); detached.ItemCount = 5; Check(detached.Selected == 1, "Count growth preserves selection."); detached.ItemCount = 1; Check(detached.Selected == 0, "Count shrink clamps selected record."); Reject<ArgumentOutOfRangeException>(() => detached.Select(-2)); Reject<ArgumentOutOfRangeException>(() => detached.ItemCount = -1); Reject<ArgumentOutOfRangeException>(() => detached.SearchBarFuzzySearchMaxMisses = -1);
        var root = new SubViewport { Size = new(500, 260), GUIEmbedSubwindows = true }; var option = new OptionButton { Name = "Choice", Size = new(180, 40), Position = new(20, 20) }; option.AddItem("Short", 10); option.AddItem("A much longer option title", 20); option.AddSeparator("Group"); option.AddItem("Last", 30); root.AddChild(option); using var tree = new SceneTree(root); tree.ProcessFrame(.01);
        var longest = option.GetCombinedMinimumSize(); option.FitToLongestItem = false; var current = option.GetCombinedMinimumSize(); Check(longest.X > current.X, "Longest item measures more than the current caption."); option.FitToLongestItem = true;
        var selected = new List<int>(); var focused = new List<int>(); option.ItemSelected += selected.Add; option.ItemFocused += focused.Add; option.Select(1); Check(selected.Count == 0, "Programmatic selection has no user event."); option.ShowPopup(); Check(option.GetPopup().Visible && option.GetPopup().GetFocusedItem() == 1, "Programmatic opening focuses selection after menu preparation."); ActionKey(root, "ui_accept"); Check(!option.GetPopup().Visible && selected.Count == 0, "Reselect is silent by default."); option.AllowReselect = true; option.ShowPopup(); ActionKey(root, "ui_accept"); Check(selected.SequenceEqual(new[] { 1 }), "Allowed reselect reports user activation.");
        selected.Clear(); option.ShowPopup(); ActionKey(root, "ui_down"); Check(option.GetPopup().GetFocusedItem() == 3 && focused.Last() == 3, "Navigation skips separator and reports focused item index."); ActionKey(root, "ui_accept"); Check(option.Selected == 3 && option.Text == "Last" && selected.SequenceEqual(new[] { 3 }), "User activation updates selected caption and radio checks.");
        Click(root, option.GetGlobalRect().GetCenter()); Check(option.GetPopup().Visible && option.ButtonPressed, "Pointer press opens owned popup and pressed state."); option.GetPopup().Hide(); Check(!option.ButtonPressed, "Popup hide resets toggle state."); option.ShowPopup(); option.Hide(); Check(!option.GetPopup().Visible, "Hidden owner hides its popup."); option.Show();
        using var keyEvent = new InputEventKey { Keycode = Key.L }; using var shortcut = new Shortcut { Events = [keyEvent] }; option.GetPopup().SetItemShortcut(3, shortcut); using (var key = new InputEventKey { Keycode = Key.L, Pressed = true }) root.PushInput(key, true); Check(selected.Count == 2, "Owned menu shortcut uses ordinary shortcut input stage."); option.SetDisableShortcuts(true); using (var key = new InputEventKey { Keycode = Key.L, Pressed = true }) root.PushInput(key, true); Check(selected.Count == 2, "Shortcut disable gate."); option.SetDisableShortcuts(false);
        option.SearchBarEnabled = true; option.SearchBarFuzzySearchEnabled = false; option.ShowPopup(); tree.ProcessFrame(.01); tree.DispatchCommittedText(option.GetPopup(), "Short"); ActionKey(root, "ui_down"); Check(option.GetPopup().GetFocusedItem() == 0, "Owned real search field filters options."); option.GetPopup().Hide();
        using var icon = new ImageTexture(); option.SetItemIcon(0, icon); option.Select(0); Task.Run(icon.Dispose).GetAwaiter().GetResult(); tree.ProcessFrame(.01); Check(option.Icon == null && option.GetItemIcon(0) == null, "Worker icon disposal updates borrowed popup and button caption.");
        Reject<InvalidOperationException>(() => Task.Run(() => option.Select(1)).GetAwaiter().GetResult()); Reentrancy(); Packing(); Console.WriteLine("OptionButton items, selection identity, counts, caption, radio, popup input, shortcuts/search, lifetime and fresh scene passed.");
    }
    private static void Reentrancy()
    {
        var root = new SubViewport { Size = new(350, 200), GUIEmbedSubwindows = true }; var option = new OptionButton(); option.AddItem("A"); option.AddItem("B"); option.AddItem("C"); root.AddChild(option); using var tree = new SceneTree(root); var nested = false;
        option.GetPopup().MenuChanged += () => { if (!nested) { nested = true; option.Select(2); } }; option.Select(1); Check(option.Selected == 2 && option.Text == "C" && option.GetPopup().IsItemChecked(2) && !option.GetPopup().IsItemChecked(1), "Nested selection suppresses stale outer radio and caption updates.");
        using var failureModel = new OptionButton(); Action mutationFail = () => throw new InvalidOperationException("mutation observer"); failureModel.GetPopup().MenuChanged += mutationFail; Reject<AggregateException>(() => failureModel.AddItem("Committed")); Check(failureModel.ItemCount == 1 && failureModel.Selected == 0 && failureModel.Text == "Committed", "First item selection and caption complete despite menu observer failure."); failureModel.GetPopup().MenuChanged -= mutationFail;
        var delivered = false; option.ItemSelected += _ => delivered = true; Action failure = () => throw new InvalidOperationException("popup observer"); option.GetPopup().PopupHide += failure; option.ShowPopup(); option.GetPopup().SetFocusedItem(0); Reject<AggregateException>(() => ActionKey(root, "ui_accept")); Check(delivered && option.Selected == 0 && !option.GetPopup().Visible, "Hide observer failure still delivers committed choice."); option.GetPopup().PopupHide -= failure;
    }
    private static void Packing()
    {
        using var source = new OptionButton { Name = "Stored", ItemCount = 3, AllowReselect = true, SearchBarEnabled = true }; source.SetItemText(0, "Saved"); source.SetItemText(1, "Disabled"); source.SetItemDisabled(1, true); source.SetItemText(2, "Chosen"); source.SetItemID(2, 77); source.Select(2); source.SetItemMetadata(2, 42); using var packed = new PackedScene(); packed.Pack(source); using var copy = (OptionButton)packed.Instantiate(); Check(copy.ItemCount == 3 && copy.Selected == 2 && copy.Text == "Chosen" && copy.GetSelectedID() == 77 && copy.IsItemDisabled(1) && copy.GetChildCount(true) == 1 && copy.ChildCount == 0, "Count/index/selection restore with independent owned menu."); Reject<KeyNotFoundException>(() => copy.GetSelectedMetadata<int>());
        var path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "electron2d-options-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(packed, path); FreshProcess(path); } finally { File.Delete(path); }
    }
    private static void FreshProcess(string path)
    {
        var start = new System.Diagnostics.ProcessStartInfo(Environment.ProcessPath!) { RedirectStandardOutput = true, RedirectStandardError = true }; if (System.IO.Path.GetFileNameWithoutExtension(Environment.ProcessPath) == "dotnet") start.ArgumentList.Add(typeof(OptionButtonTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_OPTION"); start.Environment["ELECTRON2D_TEST_OPTION_CHILD"] = path; using var process = System.Diagnostics.Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("Option fresh scene process."); }
        Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh option scene passed"), "Fresh option scene: " + error.GetAwaiter().GetResult());
    }
    internal static void RunChild(string path)
    { using var scene = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); var option = (OptionButton)scene.Instantiate(); var root = new SubViewport { Size = new(350, 220), GUIEmbedSubwindows = true }; root.AddChild(option); using var tree = new SceneTree(root); tree.ProcessFrame(.01); Check(option.Selected == 2 && option.Text == "Chosen" && option.GetSelectedID() == 77, "Fresh option caption executes."); option.ShowPopup(); Check(option.GetPopup().Visible && option.GetPopup().GetFocusedItem() == 2, "Fresh option opens real reconstructed menu."); option.GetPopup().Hide(); Console.WriteLine("Fresh option scene passed"); }
    private static void ActionKey(Viewport root, string action) { using var input = new InputEventAction { Action = action, Pressed = true }; root.PushInput(input, true); }
    private static void Click(Viewport root, Vector2 point) { using var down = new InputEventMouseButton { Position = point, ButtonIndex = MouseButton.Left, Pressed = true }; using var up = new InputEventMouseButton { Position = point, ButtonIndex = MouseButton.Left }; root.PushInput(down, true); root.PushInput(up, true); }
    private static void Check(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
