using Electron2D;
using Path = System.IO.Path;
internal static class RichTextTests
{
    private sealed class Root : Viewport { public override Rect2 GetVisibleRect() => new(0, 0, 640, 400); }
    private sealed class Effect : RichTextEffect
    { internal int Calls; internal bool SawOutline; internal Effect() { BBCode = "paint"; } protected override bool OnProcessCustomFX(CharFXTransform state) { Calls++; SawOutline |= state.Outline; state.Color = Colors.Red; state.Offset = new(0, 1); return true; } }
    private sealed class Inspector : RichTextEffect
    {
        internal RichTextLabel Owner = null!; internal CharFXTransform? Last; internal Inspector() { BBCode = "inspect"; }
        protected override bool OnProcessCustomFX(CharFXTransform state) { Check(state.Font != null && state.GetGlyphIndex('X') > 0 && state.Range.Y > state.Range.X, "bound face and scalar metadata"); try { Owner.AddText("bad"); throw new Exception("drawing mutation"); } catch (InvalidOperationException) { } try { state.Dispose(); throw new Exception("borrowed state disposal"); } catch (InvalidOperationException) { } state.Font = null; state.GlyphCount = 777; state.Range = new(1000, 1001); state.Outline = !state.Outline; state.GlyphIndex = state.GetGlyphIndex('X'); state.Color = Colors.Lime; Last = state; return false; }
    }
    internal static void Run()
    {
        using var rich = new RichTextLabel { Size = new(300, 180) }; Check(rich.FocusMode == FocusMode.Accessibility && rich.GetParagraphCount() == 1, "defaults"); rich.PushBold(); rich.AddText("bold"); rich.Pop(); rich.Newline(); rich.AddText("plain"); Check(rich.GetParsedText() == "bold\nplain" && rich.GetTotalCharacterCount() == 10, "manual stack scalar count"); Check(rich.GetLineCount() == 2 && rich.GetCharacterParagraph(6) == 1, "paragraph shape mapping"); Check(rich.GetCharacterLine(4) == 0 && rich.GetCharacterParagraph(4) == 0, "newline scalar ownership"); rich.Text = "[b]raw[/b]"; Check(rich.GetParsedText() == "[b]raw[/b]", "plain source property"); rich.BBCodeEnabled = true; Check(rich.GetParsedText() == "raw", "source parsing"); rich.ParseBBCode("[b]A[i]B[/i][/b][color=red]C[/color][lb]x[rb]"); Check(rich.GetParsedText() == "ABC[x]", "nested syntax and brackets"); rich.Clear(); rich.AppendText("[b]a"); rich.AppendText("[/b]b"); Check(rich.GetParsedText() == "a[/b]b", "append boundaries"); rich.ParseBBCode("[missing]x[/missing]"); Check(rich.GetParsedText() == "[missing]x[/missing]", "unknown tags remain literal");
        var env = rich.ParseExpressionsForValues(["number=42", "fraction=0.5", "flag=true", "color=#f00", "node=$actor", "mixed=42,true,#fff", "bad=equal=pair", "lost=2"]); Check(env.TryGet<long>("number", out var integer) && integer == 42 && env.TryGet<double>("fraction", out var fraction) && fraction == .5 && env.TryGet<bool>("flag", out var flag) && flag && env.TryGet<Color>("color", out var color) && color == Colors.Red, "typed parsed arguments"); Check(env.TryGet<string>("node", out var node) && node == "actor" && env.TryGetElement<bool>("mixed", 1, out var member) && member && !env.TryGet<long>("lost", out _), "paths, mixed arrays and malformed termination");
        rich.Clear(); rich.PushTable(2); rich.PushCell(); rich.AddText("left"); rich.Pop(); rich.PushCell(); rich.AddText("right"); rich.Pop(); rich.Pop(); Check(rich.GetTotalCharacterCount() == 9 && rich.GetParsedText() == "leftright" && rich.GetLineCount() == 1, "table cells and shape"); rich.SelectionEnabled = true; rich.SelectAll(); Check(rich.GetSelectedText() == "leftright", "table selection"); rich.Deselect(); Check(rich.GetSelectionFrom() == -1, "deselection");
        rich.Text = "one\ntwo\nthree"; rich.Size = new(70, 30); Check(rich.GetContentHeight() > 30, "scrollable shape"); rich.ScrollToParagraph(2); Check(rich.GetVScrollBar().Value > 0, "scroll producer"); Check(rich.RemoveParagraph(1) && rich.GetParsedText() == "one\nthree", "paragraph removal");
        var root = new Root(); var link = new RichTextLabel { Size = new(220, 100), BBCodeEnabled = true, Text = "[url=target]link[/url]", SelectionEnabled = true }; root.AddChild(link); using var scene = new SceneTree(root); scene.FlushDeferred(); var clicks = 0; link.MetaClicked += meta => { Check(meta.TryGet<string>(out var value) && value == "target", "typed metadata"); clicks++; }; using (var input = new InputEventMouseButton { Position = new(9, 10), ButtonIndex = MouseButton.Left, Pressed = true }) root.PushInput(input, true); using (var release = new InputEventMouseButton { Position = new(9, 10), ButtonIndex = MouseButton.Left, Pressed = false }) root.PushInput(release, true); Check(clicks == 1, "routed metadata click"); link.SelectAll(); using (var press = new InputEventMouseButton { Position = new(9, 10), ButtonIndex = MouseButton.Left, Pressed = true }) root.PushInput(press, true); Check(link.GetDragData(new(9, 10)) is DragPayload<string> { Value: "link" }, "selected text drag retains its payload"); using (var releaseDrag = new InputEventMouseButton { Position = new(9, 10), ButtonIndex = MouseButton.Left, Pressed = false }) root.PushInput(releaseDrag, true); Check(link.GetSelectedText() == "link", "completed drag retains selection");
        using var threaded = new RichTextLabel { Size = new(120, 100), Text = "one two three four five", Threaded = true }; threaded.GetLineCount(); var deadline = DateTime.UtcNow.AddSeconds(10); while (!threaded.IsFinished() && DateTime.UtcNow < deadline) Thread.Yield(); Check(threaded.IsFinished() && threaded.GetLineCount() > 1, "threaded publication"); Packed(); Edges(); Progressive(); Console.WriteLine("Rich text stack, markup, typed arguments, tables, selection, links and threaded shaping passed.");
    }

    private sealed class BlockingFont : Font
    {
        internal readonly ManualResetEventSlim Entered = new(), Release = new(); internal bool Armed; private readonly int _owner = Environment.CurrentManagedThreadId;
        internal override FontData? PrimaryData => null;
        internal BlockingFont(Font fallback) { Fallbacks = [fallback]; }
        public override int GetSpacing(TextSpacingType spacing) { if (Armed && Environment.CurrentManagedThreadId != _owner) { Entered.Set(); if (!Release.Wait(TimeSpan.FromSeconds(10))) throw new TimeoutException("blocked paragraph shaping"); } return base.GetSpacing(spacing); }
        protected override void Dispose(bool disposing) { if (disposing) { Release.Set(); Entered.Dispose(); Release.Dispose(); } base.Dispose(disposing); }
    }
    private static void Progressive()
    {
        using var rich = new RichTextLabel { Size = new(400, 200), FitContent = true }; using var font = new BlockingFont(rich.GetThemeFont("normal_font")!); rich.AddText("first"); rich.Newline(); rich.PushFont(font); rich.AddText("second"); rich.Pop(); font.Armed = true; var complete = 0; rich.Finished += () => complete++; rich.Threaded = true;
        try { rich.GetLineCount(); Check(font.Entered.Wait(TimeSpan.FromSeconds(10)), "worker reached second paragraph"); Check(!rich.IsFinished() && rich.GetLineCount() == 1 && rich.GetCharacterParagraph(6) == -1, "only completed paragraph geometry is published"); } finally { font.Release.Set(); }
        var deadline = DateTime.UtcNow.AddSeconds(10); while (!rich.IsFinished() && DateTime.UtcNow < deadline) Thread.Yield(); Check(rich.IsFinished() && complete == 1 && rich.GetLineCount() == 2, "incremental owner publication and final completion"); rich.Text = "replacement"; rich.GetLineCount(); rich.Text = "newer"; while (!rich.IsFinished() && DateTime.UtcNow < deadline) Thread.Yield(); Check(rich.GetParsedText() == "newer", "worker invalidation replacement");
        using var synchronous = new RichTextLabel { Size = new(200, 60), Text = "before" }; var calls = 0; synchronous.Finished += () => { if (calls++ == 0) synchronous.AddText("after"); }; synchronous.GetLineCount(); synchronous.GetLineCount(); Check(synchronous.GetParsedText() == "beforeafter" && calls == 2, "completion callbacks may mutate after publication");
    }
    private static void Edges()
    {
        using var rich = new RichTextLabel { Size = new(160, 120), SelectionEnabled = true }; Check(rich.GetLineCount() == 1 && !rich.IsMenuVisible(), "empty paragraph and closed menu"); rich.PushContext(); rich.PushIndent(2); rich.AddText("A😀"); rich.PopContext(); rich.AddText("B"); Check(rich.GetParsedText() == "\tA😀\nB" && rich.GetTotalCharacterCount() == 4, "structural markers and Unicode scalars"); rich.SelectAll(); Check(rich.GetSelectedText() == "A😀\nB", "selection excludes structural markers"); rich.ParseBBCode("[hint=\"has ] bracket\"]x[/hint][char=1F600][br]y"); Check(rich.GetParsedText() == "x😀\ny", "quoted brackets and character syntax"); rich.Text = "one\n\nthree"; Check(rich.GetLineCount() == 3 && rich.GetLineRange(1) == new Vector2i(4, 4), "empty middle paragraph"); rich.ScrollToLine(999); rich.ScrollToParagraph(-1); Check(rich.GetVScrollBar().Value == 0, "scroll bounds"); rich.VisibleRatio = .5f; Check(rich.VisibleCharacters == 5, "scalar ratio rounding"); rich.Text = "abc"; rich.VisibleCharacters = 1; Check(rich.GetLineRange(0) == new Vector2i(0, 1), "reveal before shaping"); rich.VisibleCharactersBehavior = TextVisibleCharactersBehavior.CharsAfterShaping; Check(rich.GetLineRange(0) == new Vector2i(0, 3), "reveal after shaping preserves layout");
        for (var h = 0; h < 16; h++) { var rgb = OkColor.HSVToSRGB(h / 16f, .8f, .8f); Check(float.IsFinite(rgb.R) && float.IsFinite(rgb.G) && float.IsFinite(rgb.B), "perceptual rainbow gamut"); }
        using (var image = Image.CreateEmpty(12, 10, false, Image.Format.Rgba8)) using (var texture = ImageTexture.CreateFromImage(image)) { rich.Clear(); rich.AddImage(texture, 32, 24); Check(rich.GetContentWidth() == 32 && rich.GetContentHeight() >= 24, "integer image dimensions resolve the unkeyed overload"); rich.Clear(); rich.AddImage("key", texture, 32, 24); rich.UpdateImage("key", RichTextLabel.ImageUpdateMask.Color, null, color: Colors.Red); Check(rich.GetContentWidth() == 32, "color-only keyed image update needs no replacement texture"); }
        using var state = new CharFXTransform(); state.Dispose(); try { _ = state.GlyphFlags; throw new Exception("disposed glyph state"); } catch (ObjectDisposedException) { }
    }
    private static void Packed()
    {
        using var effect = new RichTextEffect { BBCode = "saved_fx" }; using var rich = new RichTextLabel { Size = new(300, 100), Text = "[b]saved[/b]", BBCodeEnabled = true, SelectionEnabled = true, FitContent = true, TabSize = 6, CustomEffects = [effect] }; using var packed = new PackedScene(); packed.Pack(rich); using var copy = (RichTextLabel)packed.Instantiate(); Check(copy.GetParsedText() == "saved" && copy.SelectionEnabled && copy.CustomEffects[0].BBCode == "saved_fx", "packed rich configuration"); var path = Path.Combine(Path.GetTempPath(), "e2d-rich-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(packed, path); var start = new System.Diagnostics.ProcessStartInfo(Environment.ProcessPath!) { RedirectStandardOutput = true, RedirectStandardError = true }; if (Path.GetFileNameWithoutExtension(Environment.ProcessPath) == "dotnet") start.ArgumentList.Add(typeof(RichTextTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_RICH_TEXT"); start.Environment.Remove("ELECTRON2D_TEST_RICH_TEXT_HOST"); start.Environment["ELECTRON2D_TEST_RICH_TEXT_CHILD"] = path; using var process = System.Diagnostics.Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("fresh rich scene"); } Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh RichTextLabel scene passed"), error.GetAwaiter().GetResult()); } finally { File.Delete(path); }
    }
    internal static void RunChild(string path) { using var packed = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); using var rich = (RichTextLabel)packed.Instantiate(); Check(rich.Text == "[b]saved[/b]" && rich.GetParsedText() == "saved" && rich.TabSize == 6 && rich.CustomEffects[0].BBCode == "saved_fx" && rich.GetLineCount() == 1, "fresh rich factories and codecs"); rich.SelectAll(); Check(rich.GetSelectedText() == "saved", "fresh executable selection"); Console.WriteLine("Fresh RichTextLabel scene passed"); }
    internal static void RunHost()
    {
        Run(); var backend = Environment.GetEnvironmentVariable("ELECTRON2D_RICH_RENDERER") ?? "gpu"; var previous = ProjectSettings.Get(ProjectSettings.RenderingMethod); ProjectSettings.Set(ProjectSettings.RenderingMethod, backend); try { Pixels(); Warm(false); Warm(true); } finally { ProjectSettings.Set(ProjectSettings.RenderingMethod, previous); }
        Console.WriteLine("Rich text native rendering passed (" + backend + ").");
    }
    private static void Pixels()
    {
        var window = new Window { Size = new(540, 380) }; var rich = new RichTextLabel { Size = new(520, 350), BBCodeEnabled = true, SelectionEnabled = true }; using var effect = new Effect(); rich.InstallEffect(effect); using var inspector = new Inspector { Owner = rich }; rich.InstallEffect(inspector); rich.Text = "[b]Bold[/b] [i]italic[/i] [code]mono[/code]\n[color=#70c0ff]Multilingual: مرحبا мир[/color]\n[paint speed=1]Effect glyphs[/paint]\n[table=2][cell padding=4,4,4,4 bg=#333333]cell one[/cell][cell]cell two[/cell][/table]\n[url=target]Clickable link[/url]"; rich.Newline(); using var badge = Image.CreateEmpty(12, 10, false, Image.Format.Rgba8); badge.Fill(Colors.Cyan); using var texture = ImageTexture.CreateFromImage(badge); rich.AddImage(key: "badge", image: texture, width: 32, height: 24, inlineAlign: InlineAlignment.Center); rich.AddText(" inline image"); rich.Newline(); rich.PushDropcap("D", rich.GetThemeFont("normal_font")!, 40); rich.AddText("rop cap follows wrapped text over the shared paragraph layout."); rich.AppendText("\n[paint][inspect]replacement[/inspect][/paint]"); window.AddChild(rich); var frames = 0; window.Ready += _ => { RenderingServer.FramePostDraw += () => { using var pixels = RenderingServer.Service!.Readback(); if (frames == 1) { if (Environment.GetEnvironmentVariable("ELECTRON2D_RICH_CAPTURE") is { } debugPath) pixels.SavePNG(debugPath); var red = 0; var cyan = 0; var lime = 0; for (var y = 0; y < 250; y++) for (var x = 0; x < 300; x++) { var color = pixels.GetPixel(x, y); if (color.R > .7f && color.G < .35f && color.B < .35f) red++; if (color.R < .2f && color.G > .7f && color.B > .7f) cyan++; if (color.R < .2f && color.G > .7f && color.B < .2f) lime++; } Check(effect.Calls > 0 && red > 30 && cyan > 500 && lime > 30 && inspector.Last?.GetGlyphIndex('X') == 0, "rendered glyph effect and inline texture pixels: red=" + red + " cyan=" + cyan + " lime=" + lime + " inspector=" + (inspector.Last != null) + " unbound=" + inspector.Last?.GetGlyphIndex('X')); } if (frames == 2) { Check(rich.RemoveParagraph(rich.GetParagraphCount() - 1) && inspector.Last!.IsDisposed, "removed effect block releases owned callback state"); } if (++frames == 4) window.Tree!.Quit(); }; }; Check(Engine.Run(window) == 0 && frames == 4, "native lifecycle");
    }
    private static void Warm(bool beforeShaping)
    {
        var window = new Window { Size = new(420, 240) }; var rich = new RichTextLabel { Size = new(400, 220), BBCodeEnabled = true, SelectionEnabled = true }; using var effect = new Effect(); rich.InstallEffect(effect); rich.Text = "[ol]Heading\nnext[/ol]\n[paint]Animated glyphs[/paint]\n[table=2][cell]left[/cell][cell]right[/cell][/table]"; window.AddChild(rich); rich.VisibleCharactersBehavior = beforeShaping ? TextVisibleCharactersBehavior.CharsBeforeShaping : TextVisibleCharactersBehavior.CharsAfterShaping; var frame = 0; long before = 0, total = 0; window.Ready += _ => { RenderingServer.FramePreDraw += () => before = GC.GetAllocatedBytesForCurrentThread(); RenderingServer.FramePostDraw += () => { var after = GC.GetAllocatedBytesForCurrentThread(); if (frame >= 64) total += after - before; if (frame % 2 == 0) rich.SelectAll(); else rich.Deselect(); rich.VisibleCharacters = frame % 2 == 0 ? 20 : -1; if (frame >= 64) total += GC.GetAllocatedBytesForCurrentThread() - after; if (++frame == 128) window.Tree!.Quit(); }; }; Check(Engine.Run(window) == 0 && total == 0, "64 prepared rich render/selection intervals allocated " + total); Console.WriteLine("64 prepared rich text effect/selection/render intervals: " + total + " managed bytes.");
    }
    private static void Check(bool condition, string message) { if (!condition) throw new Exception("RichText: " + message); }
}
