using Electron2D;

internal static class SpinBoxTests
{
    internal static void Run()
    {
        using var detached = new SpinBox(); Check(detached.Step == 1 && detached.SizeFlagsVertical == Control.SizeFlags.Fill && detached.Editable && !detached.UpdateOnTextChanged && !detached.CustomArrowRound && detached.CustomArrowStep == 0 && detached.GetChildCount() == 0 && detached.GetChildCount(true) == 1, "Numeric field defaults and internal ownership."); Reject<InvalidOperationException>(detached.GetLineEdit().Dispose);
        var root = new SubViewport { Size = new(600, 320) }; var spin = new SpinBox { Name = "Number", Position = new(20, 20), Size = new(220, 40), MaxValue = 10000 }; root.AddChild(spin); using var tree = new SceneTree(root); tree.ProcessFrame(.01);
        var field = spin.GetLineEdit(); var changes = 0; spin.ValueChanged += _ => changes++;
        foreach (var pair in new[] { ("5 + 2 * 3", 11d), ("pow(2, 4)", 16d), ("5/2", 2d), ("5.0/2", 2.5d), ("PI + sin(0.5)", Math.PI + Math.Sin(.5)), ("-2**2", -4d), ("2**3**2", 64d), ("0xff + 0b10", 257d), ("(2 < 3) and not false", 1d), ("min(4,2,9)", 2d), ("maxf(5,2)/2", 2.5d), ("9007199254740993 == 9007199254740992", 0d), ("fmod(5.5,2)", 1.5d), ("min(9007199254740993,9007199254740992)%2", 0d), ("clampf(5,0,9)/2", 2.5d) }) { spin.MinValue = -10000; spin.Step = 0; field.Text = pair.Item1; spin.Apply(); Check(Math.Abs(spin.Value - pair.Item2) < 1e-10, "Numeric expression: " + pair.Item1); }
        foreach (var bad in new[] { "bad", "2+", "1/0", "sqrt(", new string('-', 1000) + "1", "pow(1,2,3)", "mini(1,2,3)", "clamp(1,2,0)" }) { var before = spin.Value; field.Text = bad; spin.Apply(); Check(spin.Value == before && field.Text != bad, "Malformed expression preserves value and restores text."); }
        spin.Step = .01; spin.Value = 1.25; spin.Prefix = "$"; spin.Suffix = "kg"; Check(field.Text == "$ 1.25 kg", "Affixes and step-dependent display outside editing."); field.GrabFocus(); tree.ProcessFrame(.01); Check(field.IsEditing() && field.Text == "1.25", "Editing removes affixes."); field.Text = "pow(2; 3)"; using (var key = new InputEventKey { Keycode = Key.Enter, Pressed = true }) root.PushInput(key, true); tree.ProcessFrame(.01); Check(spin.Value == 8 && !field.IsEditing(), "Submitted field evaluates with deferred delivery.");
        spin.Step = 1; spin.MinValue = 0; spin.MaxValue = 100; spin.Value = 0; spin.Prefix = spin.Suffix = "";
        Click(root, spin.Position + new Vector2(spin.Size.X - 8, 5), MouseButton.Left, true); Check(spin.Value == 1, "Upper arrow steps on press."); tree.ProcessFrame(.61); Check(spin.Value == 2, "Initial held repeat executes."); tree.ProcessFrame(.076); Check(spin.Value == 3, "Held repeat interval executes."); Click(root, spin.Position + new Vector2(spin.Size.X - 8, 5), MouseButton.Left, false); tree.ProcessFrame(1); Check(spin.Value == 3, "Release cancels repeat.");
        spin.CustomArrowStep = 10; spin.CustomArrowRound = true; spin.Value = 3; Click(root, spin.Position + new Vector2(spin.Size.X - 8, 5), MouseButton.Left, true); Click(root, spin.Position + new Vector2(spin.Size.X - 8, 5), MouseButton.Left, false); Check(spin.Value == 10, "Custom arrow grid uses Range min-offset snapping."); Click(root, spin.Position + new Vector2(spin.Size.X - 8, 35), MouseButton.Right, true); Check(spin.Value == 0, "Lower right arrow chooses minimum.");
        spin.Editable = false; Click(root, spin.Position + new Vector2(spin.Size.X - 8, 5), MouseButton.Left, true); Check(spin.Value == 0 && !field.Editable, "Read-only arrows and field remain inactive."); spin.Editable = true; Reject<ArgumentOutOfRangeException>(() => spin.CustomArrowStep = double.NaN);
        spin.Value = 10; spin.CustomArrowStep = 0; spin.CustomArrowRound = false; var at = spin.Position + new Vector2(spin.Size.X - 8, 5); Click(root, at, MouseButton.Left, true); Motion(root, at + new Vector2(0, 5), new(0, 5)); Motion(root, at + new Vector2(0, -15), new(0, -20)); Check(spin.Value > 11, "Headless routed accelerated drag changes real Range value."); Click(root, at, MouseButton.Left, false);
        spin.Step = .01; var peer = new HSlider { Step = .01, MaxValue = 100 }; root.AddChild(peer); spin.Share(peer); peer.Value = 31.25; Check(spin.Value == 31.25 && field.Text.Contains("31.25", StringComparison.Ordinal), "Slider and numeric field share the existing range behavior."); peer.Unshare(); peer.Dispose();
        Action<double> failed = _ => throw new InvalidOperationException("subscriber"); spin.ValueChanged += failed; Reject<AggregateException>(() => spin.Value = 21); Check(spin.Value == 21 && field.Text.Contains("21", StringComparison.Ordinal), "Failed observer preserves numeric value and formatted field."); spin.ValueChanged -= failed;
        var culture = TranslationServer.Culture; try { TranslationServer.Culture = System.Globalization.CultureInfo.GetCultureInfo("ar-EG"); spin.Step = .01; spin.Value = 12.5; spin.GetLineEdit().Unedit(); spin.LocalizeNumeralSystem = false; spin.LocalizeNumeralSystem = true; Check(field.Text.Contains('١') && field.Text.Contains('٫'), "Localized generated numerals use the selected locale."); field.Text = "٢٫٥"; spin.Apply(); Check(spin.Value == 2.5, "Localized numeric input parses to Range double."); spin.LocalizeNumeralSystem = false; Check(field.Text == "2.50", "Disabling numeral localization redraws generated text."); } finally { TranslationServer.Culture = culture; spin.LocalizeNumeralSystem = true; }
        var old = spin.Value; spin.UpdateOnTextChanged = true; field.GrabFocus(); tree.ProcessFrame(.01); field.Clear(); field.InsertTextAtCaret("3"); field.DeleteCharAtCaret(); field.InsertTextAtCaret("7"); field.DeleteCharAtCaret(); tree.ProcessFrame(.01); Check(spin.Value == old, "Empty immediate edit preserves numeric value."); spin.UpdateOnTextChanged = false;
        NumberSystems(); Packing(spin); Console.WriteLine("SpinBox expressions, deferred text, numeric arrows/repeat/drag, affixes, ownership and scene defaults passed.");
    }
    private static void NumberSystems()
    {
        foreach (var pair in new[] { ("ar", "٠١٢٣٤٥٦٧٨٩٫"), ("fa", "۰۱۲۳۴۵۶۷۸۹٫"), ("bn", "০১২৩৪৫৬৭৮৯."), ("ne", "०१२३४५६७८९."), ("dz", "༠༡༢༣༤༥༦༧༨༩."), ("sat", "᱐᱑᱒᱓᱔᱕᱖᱗᱘᱙."), ("my", "၀၁၂၃၄၅၆၇၈၉."), ("ccp", "𑄶𑄷𑄸𑄹𑄺𑄻𑄼𑄽𑄾𑄿."), ("ff", "𞥐𞥑𞥒𞥓𞥔𞥕𞥖𞥗𞥘𞥙.") })
        { var localized = TranslationServer.FormatNumber("0123456789.", pair.Item1); Check(localized == pair.Item2 && TranslationServer.ParseNumber(localized, pair.Item1) == "0123456789.", "Independent numeral-system vector: " + pair.Item1); }
        Check(TranslationServer.FormatNumber("1.2e3", "ar-EG") == "١٫٢اس٣" && TranslationServer.ParseNumber("١٫٢اس٣", "ar_EG") == "1.2e3" && TranslationServer.GetPercentSign("ar_EG") == "٪", "Locale separators, exponent markers and percent family execute."); var unknown = "12.5"; Check(ReferenceEquals(TranslationServer.FormatNumber(unknown, "unsupported"), unknown), "Unlisted locale preserves input identity."); Reject<ArgumentException>(() => TranslationServer.GetPercentSign(""));
    }
    private static void Packing(SpinBox source)
    {
        using var scene = new PackedScene(); scene.Pack(source); using var copy = (SpinBox)scene.Instantiate(); Check(copy.Step == source.Step && copy.MaxValue == source.MaxValue && copy.GetLineEdit() != source.GetLineEdit() && !copy.GetPropertyList().Any(p => p.Name == "ExpEdit"), "Numeric scene rebuilds its field and concrete schema.");
        var path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "electron2d-spinbox-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(scene, path); var start = new System.Diagnostics.ProcessStartInfo(Environment.ProcessPath!) { RedirectStandardOutput = true, RedirectStandardError = true }; if (System.IO.Path.GetFileNameWithoutExtension(Environment.ProcessPath) == "dotnet") start.ArgumentList.Add(typeof(SpinBoxTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_SPINBOX"); start.Environment["ELECTRON2D_TEST_SPINBOX_CHILD"] = path; using var process = System.Diagnostics.Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("Fresh SpinBox scene."); } Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh numeric scene passed"), "Fresh SpinBox: " + error.GetAwaiter().GetResult()); } finally { File.Delete(path); }
    }
    internal static void RunChild(string path) { using var scene = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); var spin = (SpinBox)scene.Instantiate(); var root = new SubViewport { Size = new(500, 250) }; root.AddChild(spin); using var tree = new SceneTree(root); tree.ProcessFrame(.01); spin.GetLineEdit().Text = "pow(3,2)"; spin.Apply(); Check(spin.Value == 9 && spin.Step == .01 && spin.LocalizeNumeralSystem, "Fresh scene preserves numeric schema and executes formulas."); Console.WriteLine("Fresh numeric scene passed"); }
    private static void Action(Viewport root, string action) { using var down = new InputEventAction { Action = action, Pressed = true }; using var up = new InputEventAction { Action = action }; root.PushInput(down, true); root.PushInput(up, true); }
    private static void Click(Viewport root, Vector2 point, MouseButton button, bool pressed) { using var input = new InputEventMouseButton { Position = point, ButtonIndex = button, Pressed = pressed }; root.PushInput(input, true); }
    private static void Motion(Viewport root, Vector2 point, Vector2 relative) { using var input = new InputEventMouseMotion { Position = point, Relative = relative, ButtonMask = MouseButtonMask.Left }; root.PushInput(input, true); }
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new InvalidOperationException("Expected " + typeof(T).Name); }
}
