using Electron2D;
using Path = System.IO.Path;
internal static class TreeTests
{
    private sealed class Root : Viewport { public override Rect2 GetVisibleRect() => new(0, 0, 480, 320); }
    internal static void Run() { Model(); Cells(); Routing(); Failures(); ExpandedCells(); ReentrantSelection(); Drag(); Storage(); Console.WriteLine("Tree hierarchy, typed cells, selection, checks, columns, routing and stored configuration passed."); }
    private static void Model()
    {
        using var tree = new Tree { Columns = 2, Size = new(320, 180) }; var root = tree.CreateItem(); var a = root.CreateChild(); var b = root.CreateChild(); var child = a.CreateChild(); Check(tree.GetRoot() == root && root.GetChildCount() == 2 && a.GetNext() == b && b.GetPrev() == a && child.GetPrevInTree() == a && a.GetNextInTree() == child, "hierarchy traversal"); a.Collapsed = true; Check(a.GetNextVisible() == b && root.IsAnyCollapsed(), "fold traversal"); child.UncollapseTree(); Check(!a.Collapsed && !root.Collapsed, "uncollapse"); a.Visible = false; Check(!child.IsVisibleInTree() && root.GetNextInTree() == b, "local branch visibility"); a.Visible = true; root.RemoveChild(a); Check(a.GetTree() == null && child.GetTree() == null && a.GetChildCount() == 1, "detached retained branch"); root.AddChild(a); Check(a.GetTree() == tree && child.GetTree() == tree, "reattach"); a.MoveBefore(b); Check(root.GetChild(0) == a, "move before"); Reject<InvalidOperationException>(() => a.MoveBefore(child)); Reject<InvalidOperationException>(() => a.AddChild(root));
        var visited = new List<TreeItem>(); a.CallRecursive(visited.Add); Check(visited.SequenceEqual(new[] { a, child }), "recursive subtree boundary"); tree.SelectionMode = Tree.SelectMode.Multi; a.Select(0); b.Select(1, false); Check(a.IsSelected(0) && b.IsSelected(1) && tree.GetSelected() == a && tree.GetNextSelected(a) == b, "multi select and cursor"); b.Deselect(1); Check(tree.GetSelected() == a, "multiple deselection preserves cursor"); b.Select(1, false); tree.SetSelected(b, 1); Check(!a.IsSelected(0) && b.IsSelected(1) && tree.GetSelected() == b, "SetSelected replaces multiple selection"); tree.DeselectAll(); Check(tree.GetSelected() == null && !a.IsSelected(0), "multi deselect"); tree.SelectionMode = Tree.SelectMode.Row; tree.SetSelected(a, 1); Check(a.IsSelected(0) && a.IsSelected(1), "row selection");
        root.SetCellMode(0, TreeItem.TreeCellMode.Check); a.SetCellMode(0, TreeItem.TreeCellMode.Check); b.SetCellMode(0, TreeItem.TreeCellMode.Check); child.SetCellMode(0, TreeItem.TreeCellMode.Check); a.SetChecked(0, true); a.PropagateCheck(0); Check(child.IsChecked(0) && root.IsIndeterminate(0), "tri-state propagation"); b.SetChecked(0, true); b.PropagateCheck(0, false); Check(root.IsChecked(0) && !root.IsIndeterminate(0), "all children checked");
        root.RemoveChild(a); tree.Clear(); Check(root.IsDisposed && b.IsDisposed && !a.IsDisposed, "owned cleanup preserves detached branch"); a.Dispose(); Check(child.IsDisposed, "branch deterministic cleanup");
    }
    private static void Cells()
    {
        using var tree = new Tree { Columns = 2, Size = new(360, 180), ColumnTitlesVisible = true }; var root = tree.CreateItem(); root.SetText(0, "root"); var row = root.CreateChild(); row.SetText(0, "A😀אב e\u0301"); row.SetMetadata(0, 42); Check(row.GetMetadata<int>(0) == 42, "typed metadata"); Reject<KeyNotFoundException>(() => row.GetMetadata<string>(0)); row.SetStructuredTextBIDIOverrideOptions(0, ["/"]); var options = row.GetStructuredTextBIDIOverrideOptions(0); options[0] = "bad"; Check(row.GetStructuredTextBIDIOverrideOptions(0)[0] == "/", "copied options");
        row.SetCellMode(1, TreeItem.TreeCellMode.Range); row.SetRangeConfig(1, 1, 10, .5, true); row.SetRange(1, 3.3); Check(row.GetRange(1) == 3.5 && row.GetRangeConfig(1).Exponential, "numeric snapping and complete typed config"); row.SetText(1, "Low:2,High:8"); Check(row.GetRangeConfig(1).Min == 2 && row.GetRangeConfig(1).Max == 8 && row.GetRangeConfig(1).Step == 0, "choice-defined bounds"); row.SetRange(1, 8);
        tree.SetColumnTitle(0, "Name"); tree.SetColumnTitle(1, "Value"); tree.SetColumnCustomMinimumWidth(0, 140); var rect = tree.GetItemAreaRect(row, 0); Check(rect.Size.Y > 0 && tree.GetItemAtPosition(rect.Position + rect.Size / 2) == row && tree.GetColumnAtPosition(rect.Position + rect.Size / 2) == 0, "shaped hit geometry");
        using (var wide = new Tree { Columns = 2, Size = new(600, 200) }) { wide.SetColumnExpandRatio(0, int.MaxValue); wide.SetColumnExpandRatio(1, 1); Check(wide.GetColumnWidth(0) > 500, "positive expansion ratios do not overflow their sum"); wide.SetColumnCustomMinimumWidth(0, int.MaxValue); Check(wide.GetColumnWidth(0) == int.MaxValue, "unrepresentable fitted float width saturates the integer query"); }
        using var image = Image.CreateEmpty(8, 8, false, Image.Format.Rgba8); image.Fill(Colors.Red); using var icon = ImageTexture.CreateFromImage(image); row.AddButton(0, icon, 77); var button = tree.GetItemAreaRect(row, 0, 0); Check(tree.GetButtonIDAtPosition(button.Position + button.Size / 2) == 77 && row.GetButtonByID(0, 77) == 0, "button geometry and ID"); row.SetButtonDisabled(0, 0, true); Check(row.IsButtonDisabled(0, 0), "button activation policy"); tree.HideRoot = true; Check(tree.GetItemAreaRect(root) == default && tree.GetItemAreaRect(row).Position.Y < rect.Position.Y, "hidden root layout"); Reject<ArgumentOutOfRangeException>(() => tree.Columns = 0); Reject<ArgumentException>(() => row.SetRangeConfig(1, double.NaN, 1, 1));
    }
    private static void Routing()
    {
        InputMap.LoadFromProjectSettings(); var root = new Root(); var tree = new Tree { Size = new(320, 160), HideRoot = true }; root.AddChild(tree); var baseItem = tree.CreateItem(); var a = baseItem.CreateChild(); a.SetText(0, "Alpha"); var b = baseItem.CreateChild(); b.SetText(0, "Beta"); using var scene = new SceneTree(root); scene.FlushDeferred(); var point = tree.GetItemAreaRect(a).Position + new Vector2(30, 8); using (var press = new InputEventMouseButton { Position = point, ButtonIndex = MouseButton.Left, Pressed = true }) root.PushInput(press, true); Check(tree.GetSelected() == a && tree.HasFocus(), "pointer selection"); using (var down = new InputEventKey { Keycode = Key.Down, Pressed = true }) root.PushInput(down, true); Check(tree.GetSelected() == b, "keyboard row movement"); tree.SelectionMode = Tree.SelectMode.Multi; tree.SetSelected(a, 0); using (var shiftDown = new InputEventKey { Keycode = Key.Down, Pressed = true, ShiftPressed = true }) root.PushInput(shiftDown, true); Check(a.IsSelected(0) && b.IsSelected(0), "shift range keyboard navigation"); tree.SelectionMode = Tree.SelectMode.Single; var order = ""; tree.CellSelected += () => order += "cell;"; tree.ItemSelected += () => order += "item;"; tree.SetSelected(a, 0); Check(order == "cell;item;", "single selection signal order"); a.SetCellMode(0, TreeItem.TreeCellMode.Check); a.SetEditable(0, true); tree.SetSelected(a, 0); Check(tree.EditSelected() && a.IsChecked(0) && tree.GetEdited() == a, "executable check editor");
        using var image = Image.CreateEmpty(8, 8, false, Image.Format.Rgba8); image.Fill(Colors.Red); using var texture = ImageTexture.CreateFromImage(image); a.AddButton(0, texture, 7, true); a.AddButton(0, texture, 7); var buttonPoint = tree.GetItemAreaRect(a, 0, 1).GetCenter(); var buttonCalls = 0; tree.ButtonClicked += (item, column, id, mouse) => { Check(item == a && id == 7 && tree.GetPressedButton() == 1, "button index is independent of duplicate ID"); buttonCalls++; }; using (var press = new InputEventMouseButton { Position = buttonPoint, ButtonIndex = MouseButton.Left, Pressed = true }) root.PushInput(press, true); using (var release = new InputEventMouseButton { Position = buttonPoint, ButtonIndex = MouseButton.Left, Pressed = false }) root.PushInput(release, true); Check(buttonCalls == 1, "enabled duplicate-ID button activates"); Reject<InvalidOperationException>(() => Task.Run(() => a.SetText(0, "worker")).GetAwaiter().GetResult()); tree.ButtonClicked += (item, column, id, mouse) => tree.Dispose(); using (var pressAgain = new InputEventMouseButton { Position = buttonPoint, ButtonIndex = MouseButton.Left, Pressed = true }) root.PushInput(pressAgain, true); using (var releaseAgain = new InputEventMouseButton { Position = buttonPoint, ButtonIndex = MouseButton.Left, Pressed = false }) root.PushInput(releaseAgain, true); Check(tree.IsDisposed && a.IsDisposed, "button observer may dispose its hierarchy");
    }
    private static void Failures()
    {
        using var tree = new Tree { Columns = 2 }; var root = tree.CreateItem(); var a = root.CreateChild(); var b = root.CreateChild(); a.CreateChild(); var delivered = 0; tree.CheckPropagatedToItem += (item, column) => { delivered++; if (item == a) throw new InvalidOperationException("observer"); }; a.SetChecked(0, true); Reject<AggregateException>(() => a.PropagateCheck(0)); Check(delivered == 3 && a.GetChild(0).IsChecked(0) && root.IsIndeterminate(0), "check state commits before failing observer and later items continue");
        tree.ItemSelected += () => throw new InvalidOperationException("selected"); Reject<AggregateException>(() => tree.SetSelected(b, 1)); Check(tree.GetSelected() == b && b.IsSelected(1), "selection commits before observer failure"); Reject<InvalidOperationException>(() => root.MoveBefore(a));
        var visits = 0; Reject<AggregateException>(() => root.CallRecursive(item => { visits++; if (item == a) throw new InvalidOperationException("visit"); })); Check(visits == 4, "recursive visitor continues after failure");
        tree.SelectionMode = Tree.SelectMode.Multi; tree.MultiSelected += (item, column, selected) => throw new InvalidOperationException("multi"); b.Select(0); Reject<AggregateException>(() => tree.SetSelected(root, 0)); Check(root.IsSelected(0) && !b.IsSelected(0) && tree.GetSelected() == root, "multiple selection commits before failing observers");
        using var other = new Tree { Columns = 1 }; var otherRoot = other.CreateItem(); var target = otherRoot.CreateChild(); a.MoveBefore(target); Check(a.GetTree() == other && a.GetChild(0).GetTree() == other && otherRoot.GetChild(0) == a, "cross-tree ownership and column resize"); Reject<ArgumentOutOfRangeException>(() => a.GetText(1));
    }
    private static void ExpandedCells()
    {
        using var tree = new Tree { Columns = 3, Size = new(480, 160), HideRoot = true }; var row = tree.CreateItem().CreateChild(); row.SetText(0, "text"); tree.SetColumnClipContent(0, true); row.SetExpandRight(0, true); var rect = tree.GetItemAreaRect(row, 0); Check(rect.Size.X > tree.GetColumnWidth(0) * 2 && tree.GetColumnAtPosition(rect.GetCenter()) == 0, "expanded cell owns merged geometry"); row.SetEditable(1, true); Check(Math.Abs(tree.GetItemAreaRect(row, 0).Size.X - tree.GetColumnWidth(0)) < 1, "editable cells stop expansion"); row.SetEditable(1, false); row.SetCellMode(1, TreeItem.TreeCellMode.Range); Check(Math.Abs(tree.GetItemAreaRect(row, 0).Size.X - tree.GetColumnWidth(0)) < 1, "numeric cells stop expansion even with empty source text"); row.SetCellMode(1, TreeItem.TreeCellMode.String); row.SetExpandRight(0, false); Check(tree.GetItemAreaRect(row, 2).HasArea(), "merged cell geometry returns after disabling expansion");
    }
    private static void ReentrantSelection()
    {
        using var tree = new Tree { SelectionMode = Tree.SelectMode.Multi }; var root = tree.CreateItem(); var a = root.CreateChild(); var b = root.CreateChild(); a.Select(0); var reentered = false; var delivered = 0;
        tree.MultiSelected += (item, column, selected) => delivered++;
        tree.CellSelected += () => { if (!reentered && tree.GetSelected() == b) { reentered = true; tree.SetSelected(a, 0); } };
        tree.SetSelected(b, 0); Check(reentered && delivered == 4 && tree.GetSelected() == a && a.IsSelected(0) && !b.IsSelected(0), "reentrant selection preserves separate notification buffers and latest cursor");
    }
    private static void Drag()
    {
        var viewport = new Root(); var tree = new Tree { Size = new(300, 160), HideRoot = true, DropModeFlags = TreeDropModeFlags.OnItem | TreeDropModeFlags.Inbetween }; viewport.AddChild(tree); var producer = new Control { Size = new(1, 1) }; viewport.AddChild(producer); var branch = tree.CreateItem().CreateChild(); branch.SetText(0, "Branch"); branch.CreateChild().SetText(0, "child"); branch.Collapsed = true; using var scene = new SceneTree(viewport); scene.FlushDeferred(); var rect = tree.GetItemAreaRect(branch); var point = rect.GetCenter(); using (var motion = new InputEventMouseMotion { Position = point }) viewport.PushInput(motion, true); Check(tree.GetDropSectionAtPosition(point) == 0 && tree.GetDropSectionAtPosition(rect.Position + new Vector2(30, 1)) == -1, "drop thirds"); producer.ForceDrag(new DragPayload<int>(42)); scene.ProcessFrame(.6); Check(!branch.Collapsed, "timed drag unfolding"); viewport.CancelGUIDrag(); branch.SetAcceptChildren(false); Check(tree.GetDropSectionAtPosition(point) == -100, "rejected child-drop area"); tree.DropModeFlags = TreeDropModeFlags.Disabled; Check(tree.GetDropSectionAtPosition(point) == -100, "disabled drop presentation");
    }
    private static void Storage()
    {
        using var tree = new Tree { Columns = 2, HideRoot = true, ColumnTitlesVisible = true, HintMode = VerticalScrollHintMode.Both }; tree.SetColumnTitle(1, "Stored"); tree.SetColumnExpandRatio(1, 3); tree.CreateItem().CreateChild().SetText(0, "runtime"); using var packed = new PackedScene(); packed.Pack(tree); using var copy = (Tree)packed.Instantiate(); Check(copy.Columns == 2 && copy.HideRoot && copy.GetColumnTitle(1) == "Stored" && copy.GetColumnExpandRatio(1) == 3 && copy.GetRoot() == null, "stored columns and runtime-only item graph");
        var path = Path.Combine(Path.GetTempPath(), "electron2d-tree-" + Guid.NewGuid() + ".e2dscene"); try { ResourceSaver.Save(packed, path); var start = new System.Diagnostics.ProcessStartInfo(Environment.ProcessPath!) { RedirectStandardOutput = true, RedirectStandardError = true }; if (Path.GetFileNameWithoutExtension(Environment.ProcessPath) == "dotnet") start.ArgumentList.Add(typeof(TreeTests).Assembly.Location); start.Environment.Remove("ELECTRON2D_TEST_TREE"); start.Environment.Remove("ELECTRON2D_TEST_TREE_HOST"); start.Environment["ELECTRON2D_TEST_TREE_CHILD"] = path; using var process = System.Diagnostics.Process.Start(start)!; var output = process.StandardOutput.ReadToEndAsync(); var error = process.StandardError.ReadToEndAsync(); if (!process.WaitForExit(30000)) { process.Kill(true); throw new TimeoutException("fresh Tree scene"); } Check(process.ExitCode == 0 && output.GetAwaiter().GetResult().Contains("Fresh Tree scene passed"), "fresh process: " + error.GetAwaiter().GetResult()); } finally { File.Delete(path); }
    }
    internal static void RunChild(string path)
    {
        using var packed = ResourceLoader.Load<PackedScene>(path, ResourceLoader.CacheMode.Ignore); using var tree = (Tree)packed.Instantiate(); Check(tree.Columns == 2 && tree.GetColumnTitle(1) == "Stored" && tree.GetColumnExpandRatio(1) == 3 && tree.HintMode == VerticalScrollHintMode.Both && tree.GetRoot() == null, "fresh process columns"); var row = tree.CreateItem().CreateChild(); row.SetText(0, "fresh"); tree.SetSelected(row, 0); Check(tree.GetItemAreaRect(row).HasArea() && tree.GetSelected() == row, "fresh executable authoring"); Console.WriteLine("Fresh Tree scene passed");
    }
    internal static void RunHost()
    {
        Run(); var backend = Environment.GetEnvironmentVariable("ELECTRON2D_TREE_RENDERER") ?? "gpu"; var prior = ProjectSettings.Get(ProjectSettings.RenderingMethod); ProjectSettings.Set(ProjectSettings.RenderingMethod, backend); try { Pixels(); Editors(); Warm(); Warm(true); } finally { ProjectSettings.Set(ProjectSettings.RenderingMethod, prior); }
        Console.WriteLine("Tree native UI and prepared rendering passed (" + backend + ").");
    }
    private static void Pixels()
    {
        using var image = Image.CreateEmpty(12, 12, false, Image.Format.Rgba8); image.Fill(Colors.Red); using var icon = ImageTexture.CreateFromImage(image); var window = new Window { Size = new(420, 280) }; var tree = new Tree { Name = "hierarchy", Position = new(8, 8), Size = new(400, 260), Columns = 3, HideRoot = true, ColumnTitlesVisible = true }; tree.SetColumnTitle(0, "Scene"); tree.SetColumnTitle(1, "State"); tree.SetColumnTitle(2, "Value"); tree.SetColumnClipContent(0, true); tree.SetColumnCustomMinimumWidth(0, 180); var root = tree.CreateItem(); var branch = root.CreateChild(); branch.SetText(0, "Actor Aאב"); branch.SetCellMode(1, TreeItem.TreeCellMode.Check); branch.SetEditable(1, true); branch.SetCellMode(2, TreeItem.TreeCellMode.Range); branch.SetRange(2, 42); var child = branch.CreateChild(); child.SetText(0, "Sprite 😀"); child.SetExpandRight(0, true); child.SetIcon(0, icon); child.AddButton(0, icon, 17); child.SetCellMode(2, TreeItem.TreeCellMode.Custom); child.SetCustomDrawCallback(2, (item, rect) => item.GetTree()!.DrawRect(new(rect.Position + new Vector2(2, 2), new(20, 10)), Colors.Green)); for (var i = 0; i < 14; i++) root.CreateChild().SetText(0, "Other " + i); window.AddChild(tree); var phase = 0;
        window.Ready += _ => { tree.GrabFocus(); tree.SetSelected(child, 0); RenderingServer.FramePostDraw += () => { using var pixels = RenderingServer.Service!.Readback(); var red = 0; var green = 0; var ink = 0; for (var y = 8; y < 268; y++) for (var x = 8; x < 408; x++) { var color = pixels.GetPixel(x, y); if (color.R > .7 && color.G < .2) red++; if (color.G > .7 && color.R < .2) green++; if (color.R > .6 && color.G > .6) ink++; } if (phase == 0) { Check(red > 0 && green > 0 && ink > 0, "icons, custom drawing and shaped glyph pixels"); if (Environment.GetEnvironmentVariable("ELECTRON2D_TREE_CAPTURE") is { } path) pixels.SavePNG(path); branch.Collapsed = true; } else if (phase == 1) { Check(tree.GetItemAreaRect(child) == default, "fold removes child hit area"); branch.Collapsed = false; tree.ScrollToItem(root.GetChild(-1)); Check(tree.GetScroll().Y > 0, "native scrollbar integration"); } else if (phase == 2) { tree.LayoutDirection = LayoutDirection.RTL; tree.ScrollToItem(branch); } else { Check(tree.GetColumnAtPosition(tree.GetItemAreaRect(branch, 0).Position + new Vector2(2, 2)) == 0, "RTL hit geometry"); window.Tree!.Quit(); } phase++; }; }; Check(Engine.Run(window) == 0 && phase == 4, "native tree lifecycle");
    }
    private static void Editors()
    {
        var window = new Window { Size = new(360, 240), GUIEmbedSubwindows = true }; var tree = new Tree { Size = new(340, 220), HideRoot = true }; var root = tree.CreateItem(); var row = root.CreateChild(); row.SetText(0, "original"); row.SetEditable(0, true); window.AddChild(tree); var driver = new EditorDriver(tree, row); window.AddChild(driver); Check(Engine.Run(window) == 0 && driver.Frame == 12, "cell editor lifecycle");
    }
    private sealed class EditorDriver(Tree tree, TreeItem row) : Node
    {
        internal int Frame;
        private uint _windowID;
        protected override void OnReady() { _windowID = SDL3.SDL.GetWindowID(SDL3.SDL.GetWindows(out var count)![0]); ProcessEnabled = true; tree.SetSelected(row, 0); Check(tree.EditSelected(), "open single line editor"); }
        private void PushKey(SDL3.SDL.Keycode key, SDL3.SDL.Scancode scan, bool control = false)
        {
            var input = new SDL3.SDL.Event { Key = new SDL3.SDL.KeyboardEvent { Type = SDL3.SDL.EventType.KeyDown, WindowID = _windowID, Key = key, Scancode = scan, Mod = control ? SDL3.SDL.Keymod.Ctrl : SDL3.SDL.Keymod.None, Down = true } }; Check(SDL3.SDL.PushEvent(ref input), "queue cell-editor key");
        }
        protected override void OnProcess(double delta)
        {
            if (Frame++ == 0) { var popup = tree.GetChildren(true).OfType<PopupPanel>().Single(); var field = popup.GetChildren().OfType<LineEdit>().Single(); field.Text = "changed"; PushKey(SDL3.SDL.Keycode.Return, SDL3.SDL.Scancode.Return); }
            else if (Frame == 2) { Check(row.GetText(0) == "changed" && tree.GetEdited() == row, "single line commit"); row.SetEditMultiline(0, true); Check(tree.EditSelected(), "open multiline editor"); }
            else if (Frame == 3) { var popup = tree.GetChildren(true).OfType<PopupPanel>().Single(); var text = popup.GetChildren().OfType<TextEdit>().Single(); text.Text = "first\nsecond"; PushKey(SDL3.SDL.Keycode.Return, SDL3.SDL.Scancode.Return, true); }
            else if (Frame == 4) { Check(row.GetText(0) == "first\nsecond", "multiline commit"); row.SetCellMode(0, TreeItem.TreeCellMode.Range); row.SetRangeConfig(0, 0, 100, .5); Check(tree.EditSelected(), "open numeric editor"); }
            else if (Frame == 5) { var popup = tree.GetChildren(true).OfType<PopupPanel>().Single(); var field = popup.GetChildren().OfType<LineEdit>().Single(); field.Text = "pow(3,2)"; PushKey(SDL3.SDL.Keycode.Return, SDL3.SDL.Scancode.Return); }
            else if (Frame == 6) { Check(row.GetRange(0) == 9, "numeric expression commit"); Check(tree.EditSelected(), "reopen range editor"); }
            else if (Frame == 7) { var popup = tree.GetChildren(true).OfType<PopupPanel>().Single(); popup.GetChildren().OfType<HSlider>().Single().Value = 18.5; PushKey(SDL3.SDL.Keycode.Return, SDL3.SDL.Scancode.Return); }
            else if (Frame == 8) { Check(row.GetRange(0) == 18.5, "slider value survives Enter"); row.SetText(0, "Low:2,High:8"); Check(tree.EditSelected(), "open range choices"); }
            else if (Frame == 9) { var popup = tree.GetChildren(true).OfType<PopupMenu>().Single(); popup.SetFocusedItem(1); PushKey(SDL3.SDL.Keycode.Return, SDL3.SDL.Scancode.Return); }
            else if (Frame == 10) { Check(row.GetRange(0) == 8 && tree.GetEdited() == row, "choice ID commits after popup hide"); row.SetCellMode(0, TreeItem.TreeCellMode.String); row.SetText(0, "keep"); Check(tree.EditSelected(), "open cancellable string editor"); }
            else if (Frame == 11) { var popup = tree.GetChildren(true).OfType<PopupPanel>().Single(); popup.GetChildren().OfType<LineEdit>().Single().Text = "discard"; PushKey(SDL3.SDL.Keycode.Escape, SDL3.SDL.Scancode.Escape); }
            else { Check(row.GetText(0) == "keep", "Escape cancels without string commit"); Tree!.Quit(); }
        }
    }
    private static void Warm(bool multiple = false)
    {
        var window = new Window { Size = new(320, 180) }; var tree = new Tree { Size = new(300, 160), HideRoot = true, Columns = 2, ColumnTitlesVisible = true }; if (multiple) { tree.SelectionMode = Tree.SelectMode.Multi; tree.MultiSelected += static (_, _, _) => { }; }
        var root = tree.CreateItem(); var a = root.CreateChild(); a.SetText(0, "Actor Aאב"); a.SetText(1, "first"); var b = root.CreateChild(); b.SetText(0, "Other e\u0301"); b.SetText(1, "second"); window.AddChild(tree); var frame = 0; long before = 0, total = 0;
        window.Ready += _ => { tree.GrabFocus(); RenderingServer.FramePreDraw += () => before = GC.GetAllocatedBytesForCurrentThread(); RenderingServer.FramePostDraw += () => { var now = GC.GetAllocatedBytesForCurrentThread(); if (frame >= 64) total += now - before; tree.SetSelected(frame % 2 == 0 ? a : b, frame % 2); if (frame >= 64) total += GC.GetAllocatedBytesForCurrentThread() - now; if (++frame == 128) window.Tree!.Quit(); }; }; Check(Engine.Run(window) == 0 && total == 0, "prepared tree bytes " + total); Console.WriteLine("64 prepared Tree " + (multiple ? "multiple" : "single") + " selection/render intervals: " + total + " managed bytes.");
    }
    private static void Check(bool value, string message) { if (!value) throw new Exception("Tree: " + message); }
    private static void Reject<T>(Action action) where T : Exception { try { action(); } catch (T) { return; } throw new Exception("Expected " + typeof(T).Name); }
}
